export default {
  Profile: 'Set your preferences or change your password as needed.',
  AuditLog: 'Audit logs maintain a record of certain activities in your flows, including the fields that were changed, the type of change, and who’s responsible for the change. <a href="https://docs.celigo.com/hc/en-us/articles/6514515710107-Manage-your-audit-logs">Learn more about audit logs</a>.',
  Transfers: 'Transfer individual integrations between integrator.io accounts. Send integrations by specifying the email of the owner of the integrator.io account you want to send the integration to. The receiving account owner needs to accept the transfer. Once accepted, the integration will be removed from your account and instead reside in the receiver’s account. Note: the receiver needs to be an account owner and cannot be part of the same organization as the sender.',
  Subscription: 'See details of your product subscription and request an upgrade when needed. An endpoint refers to each application or technology service that you create a connection to in integrator.io. Unlimited connections to each application are allowed and only count as one endpoint.',
  Users: 'Invite users to either Administer your account, or Manage or Monitor your integrations. A user who has been invited to Administer an account will have all the same permissions as the account Owner, including inviting users and changing their access rights. A user who has been invited to Manage an integration will have permissions to edit existing flows or create flows within an integration tile. A user who has Monitor permissions will only be allowed to view the integration, they do not have permissions to make any changes. They are however allowed to run the flows within the integration. The user will see only those integrations that you have invited them to.',
  MFA: 'Enhanced security for integrator.io account access is available through multifactor authentication (MFA). Once MFA is enabled, you are required to enter a six-digit code sent to your mobile device to sign in to your account. Alternatively, you can set the option to trust the device you are using to sign in to integrator.io. <a href="https://docs.celigo.com/hc/en-us/articles/7127009384987" target="_blank">Learn more</a>.',
  SSO: 'Configure single sign-on settings in this section',
  General: 'Describe your integration here so that other users can quickly understand the high-level business problems being solved.',
  Readme: 'Add documentation or links to articles you want other users to reference. <a href="https://docs.celigo.com/hc/en-us/articles/7703422519707-Update-your-integration-Admin-tab" target="_blank">Learn more</a>',
};

