export default {
  preSave: formValues => ({
    ...formValues,
    '/type': 'http',
    '/assistant': 'concur',
    '/http/auth/type': 'token',
    '/http/mediaType': 'json',
    '/http/baseURI': 'https://www.concursolutions.com',
    '/http/auth/token/location': 'header',
    '/http/auth/token/scheme': 'OAuth',
    '/http/auth/token/headerName': 'Authorization',
    '/https/ping/method': 'GET',
    '/http/ping/relativeURI': '/api/expense/expensereport/v1.1/report/Forms/RPTINFO',
    '/http/headers': [
      { name: 'authorization', value: 'Basic {{{base64Encode (join ":" connection.http.unencrypted.username connection.http.encrypted.password)}}}' },
      { name: 'X-ConsumerKey', value: '{{{connection.http.unencrypted.consumerKey}}}' },
      { name: 'Accept', value: 'application/json' }],
    '/http/auth/token/refreshTokenURI': 'https://www.concursolutions.com/net2/oauth2/accesstoken.ashx',
    '/http/auth/token/refreshMethod': 'GET',
    '/http/auth/token/refreshMediaType': 'json',
    '/https/auth/token/refresPath': 'Access_Token.Token',
    '/http/auth/token/refreshHeaders': [{ name: 'authorization', value: 'Basic {{{base64Encode (join ":" connection.http.unencrypted.username connection.http.encrypted.password)}}}' }, { name: 'X-ConsumerKey', value: '{{{connection.http.unencrypted.consumerKey}}}' }, { name: 'Accept', value: 'application/json' }],
  }),
  fieldMap: {
    name: { fieldId: 'name' },
    'http.unencrypted.username': {
      id: 'http.unencrypted.username',
      type: 'text',
      label: 'Username',
      required: true,
      helpKey: 'concur.connection.http.unencrypted.username',
    },
    'http.encrypted.password': {
      id: 'http.encrypted.password',
      type: 'text',
      inputType: 'password',
      defaultValue: '',
      label: 'Password',
      required: true,
      helpKey: 'concur.connection.http.encrypted.password',
    },
    'http.unencrypted.consumerKey': {
      id: 'http.unencrypted.consumerKey',
      type: 'text',
      label: 'Consumer key',
      inputType: 'password',
      defaultValue: '',
      required: true,
      helpKey: 'concur.connection.http.unencrypted.consumerKey',
    },
    'http.auth.token.token': {
      fieldId: 'http.auth.token.token',
      type: 'tokengen',
      inputType: 'password',
      resourceId: r => r._id,
      label: 'Generate token',
      defaultValue: '',
      required: true,
      disabledWhen: [
        { field: 'http.unencrypted.username', is: [''] },
        { field: 'http.encrypted.password', is: [''] },
        { field: 'http.unencrypted.consumerKey', is: [''] },
      ],
    },
    httpAdvanced: { formId: 'httpAdvanced' },
  },
  layout: {
    fields: [
      'name',
      'http.unencrypted.username',
      'http.encrypted.password',
      'http.unencrypted.consumerKey',
      'http.auth.token.token',
    ],
    type: 'collapse',
    containers: [
      { collapsed: true, label: 'Advanced Settings', fields: ['httpAdvanced'] },
    ],
  },
};
