export default {
  preSave: formValues => ({
    ...formValues,
    '/type': 'http',
    '/assistant': 'github',
    '/http/auth/type': 'oauth',
    '/http/mediaType': 'json',
    '/http/baseURI': 'https://api.github.com',
    '/http/auth/oauth/authURI': 'http://github.com/login/oauth/authorize',
    '/http/auth/oauth/tokenURI': 'https://github.com/login/oauth/access_token',
    '/http/auth/oauth/scopeDelimiter': ' ',
    '/http/headers': [{ name: 'User-Agent', value: 'Awesome-Octocat-App' }],
  }),
  fieldMap: {
    name: { fieldId: 'name' },
    'http.auth.oauth.scope': {
      fieldId: 'http.auth.oauth.scope',
      scopes: [
        'user',
        'user:email',
        'user:follow',
        'public_repo',
        'repo',
        'repo_deployment',
        'repo:status',
        'repo:invite',
        'delete_repo',
        'notifications',
        'gist',
        'read:repo_hook',
        'write:repo_hook',
        'admin:repo_hook',
        'read:org',
        'write:org',
        'admin:org',
        'read:public_key',
        'write:public_key',
        'admin:public_key',
        'read:gpg_key',
        'write:gpg_key',
        'admin:gpg_key',
      ],
    },
    httpAdvanced: { formId: 'httpAdvanced' },
  },
  layout: {
    fields: ['name', 'http.auth.oauth.scope'],
    type: 'collapse',
    containers: [
      { collapsed: true, label: 'Advanced Settings', fields: ['httpAdvanced'] },
    ],
  },
};
