export default {
  preSave: formValues => ({
    ...formValues,
    '/type': 'http',
    '/assistant': 'github',
    '/http/auth/type': 'oauth',
    '/http/mediaType': 'json',
    '/http/baseURI': 'https://api.github.com',
    '/http/auth/oauth/authURI': 'http://github.com/login/oauth/authorize',
    '/http/auth/oauth/tokenURI': 'https://github.com/login/oauth/access_token',
    '/http/auth/oauth/scopeDelimiter': ' ',
    '/http/auth/token/refreshMethod': 'POST',
    '/http/auth/token/refreshMediaType': 'urlencoded',
    '/http/headers': [{ name: 'User-Agent', value: 'Awesome-Octocat-App' }],
  }),
  fieldMap: {
    name: { fieldId: 'name' },
    application: {
      id: 'application',
      type: 'text',
      label: 'Application',
      defaultValue: r => r && r.assistant ? r.assistant : r.type,
      defaultDisabled: true,
    },
    'http.auth.oauth.scope': {
      fieldId: 'http.auth.oauth.scope',
      scopes: [
        'user',
        'user:email',
        'user:follow',
        'public_repo',
        'repo',
        'repo_deployment',
        'repo:status',
        'repo:invite',
        'delete_repo',
        'notifications',
        'gist',
        'read:repo_hook',
        'write:repo_hook',
        'admin:repo_hook',
        'read:org',
        'write:org',
        'admin:org',
        'read:public_key',
        'write:public_key',
        'admin:public_key',
        'read:gpg_key',
        'write:gpg_key',
        'admin:gpg_key',
      ],
    },
    httpAdvanced: { formId: 'httpAdvanced' },
  },
  layout: {
    type: 'collapse',
    containers: [
      { collapsed: true, label: 'General', fields: ['name', 'application'] },
      { collapsed: true,
        label: 'Application details',
        fields: ['http.auth.oauth.scope'] },
      { collapsed: true, label: 'Advanced Settings', fields: ['httpAdvanced'] },
    ],
  },
};
