export default {
  preSave: formValues => ({
    ...formValues,
    '/type': 'http',
    '/assistant': 'mercadolibre',
    '/http/auth/type': 'oauth',
    '/http/mediaType': 'json',
    '/http/baseURI': 'https://api.mercadolibre.com/',
    '/http/ping/relativeURI': '/users/me',
    '/http/ping/method': 'GET',
    '/http/auth/oauth/useIClientFields': false,
    '/http/auth/oauth/authURI': `https://auth.${
      formValues['/http/unencrypted/region'] === 'br' ? 'mercadolivre' : 'mercadolibre'}${
      formValues['/http/unencrypted/region'] === 'cr' ? '.co' : `${formValues['/http/unencrypted/region'] === 'cl' ? '' : '.com'}`}.${formValues['/http/unencrypted/region']}/authorization`,
    '/http/auth/oauth/tokenURI': 'https://api.mercadolibre.com/oauth/token',
    '/http/auth/token/location': 'header',
    '/http/auth/token/headerName': 'Authorization',
    '/http/auth/token/scheme': 'Bearer',
    '/http/auth/oauth/clientCredentialsLocation': 'body',
    '/http/auth/oauth/grantType': 'authorizecode',
    '/http/auth/token/refreshMethod': 'POST',
    '/http/auth/token/refreshMediaType': 'urlencoded',
  }),
  fieldMap: {
    name: { fieldId: 'name' },
    'http.unencrypted.region': {
      id: 'http.unencrypted.region',
      type: 'select',
      label: 'Region',
      helpKey: 'mercadolibre.connection.http.unencrypted.region',
      required: true,
      options: [
        {
          items: [
            { label: 'Argentina', value: 'ar' },
            { label: 'Bolivia', value: 'bo' },
            { label: 'Brasil', value: 'br' },
            { label: 'Chile', value: 'cl' },
            { label: 'Colombia', value: 'co' },
            { label: 'Costa Rica', value: 'cr' },
            { label: 'Dominicana', value: 'do' },
            { label: 'Ecuador', value: 'ec' },
            { label: 'Guatemala', value: 'gt' },
            { label: 'Honduras', value: 'hn' },
            { label: 'Mexico', value: 'mx' },
            { label: 'Nicaragua', value: 'ni' },
            { label: 'Panama', value: 'pa' },
            { label: 'Paraguay', value: 'py' },
            { label: 'Perú', value: 'pe' },
            { label: 'Salvador', value: 'sv' },
            { label: 'Uruguay', value: 'uy' },
            { label: 'Venezuela', value: 've' },
          ],
        },
      ],
    },
    'http._iClientId': {
      fieldId: 'http._iClientId',
      required: true,
      filter: { provider: 'custom_oauth2' },
      type: 'dynaiclient',
      connectionId: r => r && r._id,
      connectorId: r => r && r._connectorId,
      ignoreEnvironmentFilter: true,
      helpKey: 'mercadolibre.connection.http._iClientId',
    },
    'http.auth.oauth.callbackURL': {
      fieldId: 'http.auth.oauth.callbackURL',
      copyToClipboard: true,
    },
    application: {
      fieldId: 'application',
    },
    httpAdvanced: { formId: 'httpAdvanced' },
  },
  layout: {
    type: 'collapse',
    containers: [
      { collapsed: true, label: 'General', fields: ['name', 'application'] },
      { collapsed: true,
        label: 'Application details',
        fields: ['http.unencrypted.region',
          'http._iClientId',
          'http.auth.oauth.callbackURL'] },
      { collapsed: true, label: 'Advanced', fields: ['httpAdvanced'] },
    ],
  },
};
