export default {
  preSave: formValues => ({
    ...formValues,
    '/type': 'http',
    '/assistant': 'microsoftteams',
    '/http/auth/type': 'oauth',
    '/http/mediaType': 'json',
    '/http/baseURI': 'https://graph.microsoft.com/v1.0',
    '/http/auth/oauth/authURI':
        `https://login.microsoftonline.com/${
          formValues['/http/unencrypted/tenantId']}/oauth2/v2.0/authorize?prompt=consent`,
    '/http/auth/oauth/tokenURI':
        `https://login.microsoftonline.com/${
          formValues['/http/unencrypted/tenantId']}/oauth2/v2.0/token`,
    '/http/auth/oauth/scope': [
      ...['openid', 'offline_access'],
      ...formValues['/http/auth/oauth/scope'],
    ],
    '/http/auth/oauth/scopeDelimiter': ' ',
    '/http/auth/token/refreshMethod': 'POST',
    '/http/auth/token/refreshMediaType': 'urlencoded',
  }),
  fieldMap: {
    name: { fieldId: 'name' },
    'http.unencrypted.tenantId': {
      id: 'http.unencrypted.tenantId',
      type: 'text',
      label: 'Tenant ID',
      required: true,
      helpKey: 'microsoftteams.connection.http.unencrypted.tenantId',
    },
    'http._iClientId': {
      fieldId: 'http._iClientId',
      required: true,
      filter: { provider: 'custom_oauth2' },
      type: 'dynaiclient',
      connectionId: r => r && r._id,
      connectorId: r => r && r._connectorId,
      helpKey: 'precisely.http._iClientId',
      ignoreEnvironmentFilter: true,
      visibleWhen: [
        { field: 'accountType', is: ['generic'] },
      ],
    },
    'http.auth.oauth.scope': {
      fieldId: 'http.auth.oauth.scope',
      required: true,
      scopes: [
        'AppCatalog.Read.All',
        'AppCatalog.ReadWrite.All',
        'Application.Read.All',
        'Calendars.Read',
        'Calendars.Read.Shared',
        'Calendars.ReadWrite',
        'Calendars.ReadWrite.Shared',
        'Channel.Create',
        'Channel.Delete.All',
        'Channel.ReadBasic.All',
        'ChannelMember.Read.All',
        'ChannelMember.ReadWrite.All',
        'ChannelMessage.Delete',
        'ChannelMessage.Edit',
        'ChannelMessage.Read.All',
        'ChannelMessage.Send',
        'ChannelSettings.Read.All',
        'ChannelSettings.ReadWrite.All',
        'Chat.Create',
        'Chat.Read',
        'Chat.ReadBasic',
        'Chat.ReadWrite',
        'ChatMessage.Read',
        'ChatMessage.Send',
        'Directory.AccessAsUser.All',
        'Directory.Read.All',
        'Directory.ReadWrite.All',
        'email',
        'Files.Read',
        'Files.Read.All',
        'Files.ReadWrite',
        'Files.ReadWrite.All',
        'Group.Read.All',
        'Group.ReadWrite.All',
        'GroupMember.ReadWrite.All',
        'Notes.Create',
        'Notes.Read',
        'Notes.Read.All',
        'Notes.ReadWrite',
        'Notes.ReadWrite.All',
        'offline_access',
        'openid',
        'profile',
        'Schedule.Read.All',
        'Schedule.ReadWrite.All',
        'Sites.Read.All',
        'Sites.ReadWrite.All',
        'Team.Create',
        'Team.ReadBasic.All',
        'TeamMember.Read.All',
        'TeamMember.ReadWrite.All',
        'TeamMember.ReadWriteNonOwnerRole.All',
        'TeamsApp.Read',
        'TeamsApp.Read.All',
        'TeamsApp.ReadWrite',
        'TeamsApp.ReadWrite.All',
        'TeamsAppInstallation.ReadForChat',
        'TeamsAppInstallation.ReadForTeam',
        'TeamsAppInstallation.ReadForUser',
        'TeamsAppInstallation.ReadWriteForChat',
        'TeamsAppInstallation.ReadWriteForTeam',
        'TeamsAppInstallation.ReadWriteForUser',
        'TeamsAppInstallation.ReadWriteSelfForChat',
        'TeamsAppInstallation.ReadWriteSelfForUser',
        'TeamSettings.Read.All',
        'TeamSettings.ReadWrite.All',
        'TeamsTab.Create',
        'TeamsTab.Read.All',
        'TeamsTab.ReadWrite.All',
        'TeamsTab.ReadWriteForChat',
        'TeamsTab.ReadWriteForTeam',
        'TeamsTab.ReadWriteForUser',
        'User.Read',
        'User.Read.All',
        'User.ReadBasic.All',
        'User.ReadWrite.All',
        'WorkforceIntegration.Read.All',
        'WorkforceIntegration.ReadWrite.All',
      ],
    },
    application: {
      fieldId: 'application',
    },
    'http.auth.oauth.callbackURL': {
      fieldId: 'http.auth.oauth.callbackURL',
      copyToClipboard: true,
    },
    httpAdvanced: { formId: 'httpAdvanced' },
  },
  layout: {
    type: 'collapse',
    containers: [
      { collapsed: true, label: 'General', fields: ['name', 'application'] },
      { collapsed: true,
        label: 'Application details',
        fields: [
          'http.unencrypted.tenantId',
          'http._iClientId',
          'http.auth.oauth.callbackURL',
          'http.auth.oauth.scope'] },
      { collapsed: true, label: 'Advanced', fields: ['httpAdvanced'] },
    ],
  },
};
