export default {
  preSave: formValues => ({
    ...formValues,
    '/type': 'http',
    '/assistant': 'smartsheet',
    '/http/auth/type': 'oauth',
    '/http/mediaType': 'json',
    '/http/baseURI': 'https://api.smartsheet.com',
    '/http/token/location': 'header',
    '/http/auth/oauth/authURI': 'https://app.smartsheet.com/b/authorize',
    '/http/auth/oauth/tokenURI': 'https://api.smartsheet.com/2.0/token',
    '/http/auth/oauth/scopeDelimiter': ' ',
    '/http/ping/relativeURI': '/2.0/users/me',
    '/http/ping/method': 'GET',
    '/http/auth/token/refreshMethod': 'POST',
    '/http/auth/token/refreshMediaType': 'urlencoded',
  }),

  fieldMap: {
    name: { fieldId: 'name' },
    'http.auth.oauth.scope': {
      fieldId: 'http.auth.oauth.scope',
      scopes: [
        'ADMIN_SHEETS',
        'ADMIN_SIGHTS',
        'ADMIN_USERS',
        'ADMIN_WEBHOOKS',
        'ADMIN_WORKSPACES',
        'CREATE_SHEETS',
        'CREATE_SIGHTS',
        'DELETE_SHEETS',
        'DELETE_SIGHTS',
        'READ_CONTACTS',
        'READ_SHEETS',
        'READ_SIGHTS',
        'READ_USERS',
        'SHARE_SHEETS',
        'SHARE_SIGHTS',
        'WRITE_SHEETS',
      ],
    },
    application: {
      fieldId: 'application',
    },
    httpAdvanced: { formId: 'httpAdvanced' },
  },
  layout: {
    type: 'collapse',
    containers: [
      { collapsed: true, label: 'General', fields: ['name', 'application'] },
      { collapsed: true,
        label: 'Application details',
        fields: ['http.auth.oauth.scope'] },
      { collapsed: true, label: 'Advanced', fields: ['httpAdvanced'] },
    ],
  },
};
