export default {
  preSave: formValues => ({
    ...formValues,
    '/type': 'http',
    '/assistant': 'zohocrm',
    '/http/auth/type': 'oauth',
    '/http/mediaType': 'json',
    '/http/baseURI': `https://www.zohoapis${
      formValues['/http/zohoSubdomain']
    }/crm`,
    '/http/ping/relativeURI': '/v2/settings/profiles',
    '/http/auth/token/location': 'header',
    '/http/auth/oauth/authURI':
      formValues['/http/zohoSubdomain'] === '.com.cn'
        ? 'https://accounts.zoho.com.cn/oauth/v2/auth'
        : 'https://accounts.zoho.com/oauth/v2/auth',
    '/http/auth/oauth/tokenURI': `https://accounts.zoho${
      formValues['/http/zohoSubdomain']
    }/oauth/v2/token`,
    '/http/auth/oauth/scopeDelimiter': ',',
    '/http/auth/token/refreshMethod': 'POST',
    '/http/auth/token/refreshMediaType': 'urlencoded',
    '/http/headers': [{ name: 'Accept', value: 'application/json' }],
  }),
  fieldMap: {
    name: { fieldId: 'name' },
    'http.zohoSubdomain': {
      id: 'http.zohoSubdomain',
      type: 'text',
      helpKey: 'zohocrm.connection.http.zohoSubdomain',
      startAdornment: 'https://www.zohoapis',
      endAdornment: '/crm',
      label: 'Subdomain',
      required: true,
      validWhen: {
        matchesRegEx: {
          pattern: '^[\\S]+$',
          message: 'Subdomain should not contain spaces.',
        },
      },
      defaultValue: r => {
        const baseUri = r && r.http && r.http.baseURI;
        const subdomain =
          baseUri &&
          baseUri.substring(
            baseUri.indexOf('https://www.zohoapis') + 20,
            baseUri.indexOf('/crm')
          );

        return subdomain;
      },
    },
    'http.auth.oauth.scope': {
      fieldId: 'http.auth.oauth.scope',
      scopes: [
        {
          subHeader: 'Required',
          scopes: [
            'ZohoCRM.settings.profiles.READ',
          ],
        },
        {
          subHeader: 'Optional',
          scopes: [
            'ZohoCRM.settings.currencies.READ',
            'ZohoCRM.settings.currencies.CREATE',
            'ZohoCRM.settings.currencies.UPDATE',
            'ZohoCRM.settings.ALL',
            'ZohoCRM.settings.tags.ALL',
            'ZohoCRM.settings.territories.ALL',
            'ZohoCRM.settings.territories.READ',
            'ZohoCRM.settings.modules.ALL',
            'ZohoCRM.settings.modules.READ',
            'ZohoCRM.users.ALL',
            'ZohoCRM.users.READ',
            'ZohoCRM.users.CREATE',
            'ZohoCRM.users.UPDATE',
            'ZohoCRM.users.DELETE',
            'ZohoCRM.settings.roles.ALL',
            'ZohoCRM.settings.roles.READ',
            'ZohoCRM.settings.profiles.ALL',
            'ZohoCRM.settings.fields.read',
            'ZohoCRM.settings.fields.all',
            'ZohoCRM.settings.layouts.read',
            'ZohoCRM.settings.layouts.all',
            'ZohoCRM.settings.related_lists.read',
            'ZohoCRM.settings.related_lists.all',
            'ZohoCRM.settings.custom_views.read',
            'ZohoCRM.settings.custom_views.all',
            'ZohoCRM.org.ALL',
            'ZohoCRM.org.READ',
            'ZohoCRM.notifications.ALL',
            'ZohoCRM.notifications.READ',
            'ZohoCRM.notifications.CREATE',
            'ZohoCRM.notifications.WRITE',
            'ZohoCRM.notifications.UPDATE',
            'ZohoCRM.notifications.DELETE',
            'ZohoCRM.modules.ALL',
            'ZohoCRM.modules.leads.ALL',
            'ZohoCRM.modules.leads.CREATE',
            'ZohoCRM.modules.leads.UPDATE',
            'ZohoCRM.modules.leads.WRITE',
            'ZohoCRM.modules.leads.READ',
            'ZohoCRM.modules.leads.DELETE',
            'ZohoCRM.modules.accounts.ALL',
            'ZohoCRM.modules.accounts.CREATE',
            'ZohoCRM.modules.accounts.UPDATE',
            'ZohoCRM.modules.accounts.WRITE',
            'ZohoCRM.modules.accounts.READ',
            'ZohoCRM.modules.accounts.DELETE',
            'ZohoCRM.modules.contacts.ALL',
            'ZohoCRM.modules.contacts.CREATE',
            'ZohoCRM.modules.contacts.UPDATE',
            'ZohoCRM.modules.contacts.WRITE',
            'ZohoCRM.modules.contacts.READ',
            'ZohoCRM.modules.contacts.DELETE',
            'ZohoCRM.modules.deals.ALL',
            'ZohoCRM.modules.deals.CREATE',
            'ZohoCRM.modules.deals.UPDATE',
            'ZohoCRM.modules.deals.WRITE',
            'ZohoCRM.modules.deals.READ',
            'ZohoCRM.modules.deals.DELETE',
            'ZohoCRM.modules.campaigns.ALL',
            'ZohoCRM.modules.campaigns.CREATE',
            'ZohoCRM.modules.campaigns.UPDATE',
            'ZohoCRM.modules.campaigns.WRITE',
            'ZohoCRM.modules.campaigns.READ',
            'ZohoCRM.modules.campaigns.DELETE',
            'ZohoCRM.modules.tasks.ALL',
            'ZohoCRM.modules.tasks.CREATE',
            'ZohoCRM.modules.tasks.UPDATE',
            'ZohoCRM.modules.tasks.WRITE',
            'ZohoCRM.modules.tasks.READ',
            'ZohoCRM.modules.tasks.DELETE',
            'ZohoCRM.modules.cases.ALL',
            'ZohoCRM.modules.cases.CREATE',
            'ZohoCRM.modules.cases.UPDATE',
            'ZohoCRM.modules.cases.WRITE',
            'ZohoCRM.modules.cases.READ',
            'ZohoCRM.modules.cases.DELETE',
            'ZohoCRM.modules.events.ALL',
            'ZohoCRM.modules.events.CREATE',
            'ZohoCRM.modules.events.UPDATE',
            'ZohoCRM.modules.events.WRITE',
            'ZohoCRM.modules.events.READ',
            'ZohoCRM.modules.events.DELETE',
            'ZohoCRM.modules.calls.ALL',
            'ZohoCRM.modules.calls.CREATE',
            'ZohoCRM.modules.calls.UPDATE',
            'ZohoCRM.modules.calls.WRITE',
            'ZohoCRM.modules.calls.READ',
            'ZohoCRM.modules.calls.DELETE',
            'ZohoCRM.modules.solutions.ALL',
            'ZohoCRM.modules.solutions.CREATE',
            'ZohoCRM.modules.solutions.UPDATE',
            'ZohoCRM.modules.solutions.WRITE',
            'ZohoCRM.modules.solutions.READ',
            'ZohoCRM.modules.solutions.DELETE',
            'ZohoCRM.modules.products.ALL',
            'ZohoCRM.modules.products.CREATE',
            'ZohoCRM.modules.products.UPDATE',
            'ZohoCRM.modules.products.WRITE',
            'ZohoCRM.modules.products.READ',
            'ZohoCRM.modules.products.DELETE',
            'ZohoCRM.modules.vendors.ALL',
            'ZohoCRM.modules.vendors.CREATE',
            'ZohoCRM.modules.vendors.UPDATE',
            'ZohoCRM.modules.vendors.WRITE',
            'ZohoCRM.modules.vendors.READ',
            'ZohoCRM.modules.vendors.DELETE',
            'ZohoCRM.modules.pricebooks.ALL',
            'ZohoCRM.modules.pricebooks.CREATE',
            'ZohoCRM.modules.pricebooks.UPDATE',
            'ZohoCRM.modules.pricebooks.WRITE',
            'ZohoCRM.modules.pricebooks.READ',
            'ZohoCRM.modules.pricebooks.DELETE',
            'ZohoCRM.modules.quotes.ALL',
            'ZohoCRM.modules.quotes.CREATE',
            'ZohoCRM.modules.quotes.UPDATE',
            'ZohoCRM.modules.quotes.WRITE',
            'ZohoCRM.modules.quotes.READ',
            'ZohoCRM.modules.quotes.DELETE',
            'ZohoCRM.modules.salesorders.ALL',
            'ZohoCRM.modules.salesorders.CREATE',
            'ZohoCRM.modules.salesorders.UPDATE',
            'ZohoCRM.modules.salesorders.WRITE',
            'ZohoCRM.modules.salesorders.READ',
            'ZohoCRM.modules.salesorders.DELETE',
            'ZohoCRM.modules.purchaseorders.ALL',
            'ZohoCRM.modules.purchaseorders.CREATE',
            'ZohoCRM.modules.purchaseorders.UPDATE',
            'ZohoCRM.modules.purchaseorders.WRITE',
            'ZohoCRM.modules.purchaseorders.READ',
            'ZohoCRM.modules.purchaseorders.DELETE',
            'ZohoCRM.modules.invoices.ALL',
            'ZohoCRM.modules.invoices.CREATE',
            'ZohoCRM.modules.invoices.UPDATE',
            'ZohoCRM.modules.invoices.WRITE',
            'ZohoCRM.modules.invoices.READ',
            'ZohoCRM.modules.invoices.DELETE',
            'ZohoCRM.modules.approvals.ALL',
            'ZohoCRM.modules.approvals.CREATE',
            'ZohoCRM.modules.approvals.UPDATE',
            'ZohoCRM.modules.approvals.WRITE',
            'ZohoCRM.modules.approvals.READ',
            'ZohoCRM.modules.approvals.DELETE',
            'ZohoCRM.modules.activities.ALL',
            'ZohoCRM.modules.activities.CREATE',
            'ZohoCRM.modules.activities.UPDATE',
            'ZohoCRM.modules.activities.WRITE',
            'ZohoCRM.modules.activities.READ',
            'ZohoCRM.modules.activities.DELETE',
            'ZohoCRM.bulk.read',
            'ZohoCRM.modules.notes.ALL',
            'ZohoCRM.modules.notes.READ',
            'ZohoCRM.modules.notes.CREATE',
            'ZohoCRM.modules.notes.WRITE',
            'ZohoCRM.modules.notes.UPDATE',
            'ZohoCRM.modules.notes.DELETE',
            'ZohoCRM.modules.custom.all',
            'ZohoCRM.modules.custom.CREATE',
            'ZohoCRM.modules.custom.UPDATE',
            'ZohoCRM.modules.custom.WRITE',
            'ZohoCRM.modules.custom.READ',
            'ZohoCRM.modules.custom.DELETE',
            'ZohoCRM.mass_update.leads.READ',
            'ZohoCRM.mass_update.leads.UPDATE',
            'ZohoCRM.mass_update.accounts.READ',
            'ZohoCRM.mass_update.accounts.UPDATE',
            'ZohoCRM.mass_update.contacts.READ',
            'ZohoCRM.mass_update.contacts.UPDATE',
            'ZohoCRM.mass_update.deals.READ',
            'ZohoCRM.mass_update.deals.UPDATE',
            'ZohoCRM.mass_update.campaigns.READ',
            'ZohoCRM.mass_update.campaigns.UPDATE',
            'ZohoCRM.mass_update.activities.READ',
            'ZohoCRM.mass_update.activities.UPDATE',
            'ZohoCRM.mass_update.solutions.READ',
            'ZohoCRM.mass_update.solutions.UPDATE',
            'ZohoCRM.mass_update.products.READ',
            'ZohoCRM.mass_update.products.UPDATE',
            'ZohoCRM.mass_update.vendors.READ',
            'ZohoCRM.mass_update.vendors.UPDATE',
            'ZohoCRM.mass_update.salesorders.READ',
            'ZohoCRM.mass_update.salesorders.UPDATE',
            'ZohoCRM.mass_update.quotes.READ',
            'ZohoCRM.mass_update.quotes.UPDATE',
            'ZohoCRM.mass_update.pricebooks.READ',
            'ZohoCRM.mass_update.pricebooks.UPDATE',
            'ZohoCRM.mass_update.invoices.READ',
            'ZohoCRM.mass_update.invoices.UPDATE',
            'ZohoCRM.mass_update.purchaseorders.READ',
            'ZohoCRM.mass_update.purchaseorders.UPDATE',
            'ZohoCRM.mass_update.custom.READ',
            'ZohoCRM.mass_update.custom.UPDATE',
            'ZohoCRM.share.leads.ALL',
            'ZohoCRM.share.leads.READ',
            'ZohoCRM.share.leads.UPDATE',
            'ZohoCRM.share.leads.CREATE',
            'ZohoCRM.share.leads.DELETE',
            'ZohoCRM.share.accounts.ALL',
            'ZohoCRM.share.accounts.READ',
            'ZohoCRM.share.accounts.UPDATE',
            'ZohoCRM.share.accounts.CREATE',
            'ZohoCRM.share.accounts.DELETE',
            'ZohoCRM.share.contacts.ALL',
            'ZohoCRM.share.contacts.READ',
            'ZohoCRM.share.contacts.UPDATE',
            'ZohoCRM.share.contacts.CREATE',
            'ZohoCRM.share.contacts.DELETE',
            'ZohoCRM.share.deals.ALL',
            'ZohoCRM.share.deals.READ',
            'ZohoCRM.share.deals.UPDATE',
            'ZohoCRM.share.deals.CREATE',
            'ZohoCRM.share.deals.DELETE',
            'ZohoCRM.share.campaigns.ALL',
            'ZohoCRM.share.campaigns.READ',
            'ZohoCRM.share.campaigns.UPDATE',
            'ZohoCRM.share.campaigns.CREATE',
            'ZohoCRM.share.campaigns.DELETE',
            'ZohoCRM.share.activities.ALL',
            'ZohoCRM.share.activities.READ',
            'ZohoCRM.share.activities.UPDATE',
            'ZohoCRM.share.activities.CREATE',
            'ZohoCRM.share.activities.DELETE',
            'ZohoCRM.share.solutions.ALL',
            'ZohoCRM.share.solutions.READ',
            'ZohoCRM.share.solutions.UPDATE',
            'ZohoCRM.share.solutions.CREATE',
            'ZohoCRM.share.solutions.DELETE',
            'ZohoCRM.share.products.ALL',
            'ZohoCRM.share.products.READ',
            'ZohoCRM.share.products.UPDATE',
            'ZohoCRM.share.products.CREATE',
            'ZohoCRM.share.products.DELETE',
            'ZohoCRM.share.vendors.ALL',
            'ZohoCRM.share.vendors.READ',
            'ZohoCRM.share.vendors.UPDATE',
            'ZohoCRM.share.vendors.CREATE',
            'ZohoCRM.share.vendors.DELETE',
            'ZohoCRM.share.salesorders.ALL',
            'ZohoCRM.share.salesorders.READ',
            'ZohoCRM.share.salesorders.UPDATE',
            'ZohoCRM.share.salesorders.CREATE',
            'ZohoCRM.share.salesorders.DELETE',
            'ZohoCRM.share.quotes.ALL',
            'ZohoCRM.share.quotes.READ',
            'ZohoCRM.share.quotes.UPDATE',
            'ZohoCRM.share.quotes.CREATE',
            'ZohoCRM.share.quotes.DELETE',
            'ZohoCRM.share.pricebooks.ALL',
            'ZohoCRM.share.pricebooks.READ',
            'ZohoCRM.share.pricebooks.UPDATE',
            'ZohoCRM.share.pricebooks.CREATE',
            'ZohoCRM.share.pricebooks.DELETE',
            'ZohoCRM.share.invoices.ALL',
            'ZohoCRM.share.invoices.READ',
            'ZohoCRM.share.invoices.UPDATE',
            'ZohoCRM.share.invoices.CREATE',
            'ZohoCRM.share.invoices.DELETE',
            'ZohoCRM.share.purchaseorders.ALL',
            'ZohoCRM.share.purchaseorders.READ',
            'ZohoCRM.share.purchaseorders.UPDATE',
            'ZohoCRM.share.purchaseorders.CREATE',
            'ZohoCRM.share.purchaseorders.DELETE',
            'ZohoCRM.share.custom.ALL',
            'ZohoCRM.share.custom.READ',
            'ZohoCRM.share.custom.UPDATE',
            'ZohoCRM.share.custom.CREATE',
            'ZohoCRM.share.custom.DELETE',
            'ZohoCRM.Files.READ',
            'ZohoCRM.Files.CREATE',
            'ZohoCRM.settings.functions.all',
            'ZohoCRM.functions.execute.read',
            'ZohoCRM.functions.execute.create',
            'ZohoCRM.settings.layout_rules.read',
            'ZohoCRM.coql.READ',
            'ZohoCRM.settings.scoring_rules.ALL',
            'ZohoCRM.settings.scoring_rules.READ',
            'ZohoCRM.settings.scoring_rules.CREATE',
            'ZohoCRM.settings.scoring_rules.UPDATE',
            'ZohoCRM.settings.scoring_rules.DELETE',
            'ZohoCRM.settings.assignment_rules.ALL',
            'ZohoCRM.settings.assignment_rules.READ',
            'ZohoCRM.settings.wizards.READ',
            'ZohoCRM.templates.email.READ',
            'ZohoCRM.templates.inventory.READ',
            'ZohoCRM.settings.emails.READ',
            'ZohoCRM.send_mail.all.CREATE',
            'ZohoCRM.change_owner.CREATE',
            'ZohoCRM.settings.users_unavailability.ALL',
            'ZohoCRM.settings.users_unavailability.READ',
            'ZohoCRM.settings.users_unavailability.WRITE',
            'ZohoCRM.settings.users_unavailability.UPDATE',
            'ZohoCRM.settings.users_unavailability.DELETE',
          ],
        },
      ],
      defaultValue: r => (r?.http?.auth?.oauth.scope) || ['ZohoCRM.settings.profiles.READ'],
    },
    application: {
      fieldId: 'application',
    },
    httpAdvanced: { formId: 'httpAdvanced' },
  },
  layout: {
    type: 'collapse',
    containers: [
      { collapsed: true, label: 'General', fields: ['name', 'application'] },
      { collapsed: true,
        label: 'Application details',
        fields: ['http.zohoSubdomain', 'http.auth.oauth.scope'] },
      { collapsed: true, label: 'Advanced', fields: ['httpAdvanced'] },
    ],
  },
};
