export default {
  preSave: formValues => ({
    ...formValues,
    '/type': 'http',
    '/assistant': 'zohomail',
    '/http/auth/type': 'oauth',
    '/http/mediaType': 'json',
    '/http/baseURI': 'https://mail.zoho.com/api',
    '/http/auth/token/location': 'header',
    '/http/auth/oauth/authURI': 'https://accounts.zoho.com/oauth/v2/auth',
    '/http/auth/oauth/tokenURI': 'https://accounts.zoho.com/oauth/v2/token',
    '/http/auth/oauth/scopeDelimiter': ',',
    '/http/auth/failStatusCode': 404,
    '/http/auth/failPath': 'data.errorCode',
    '/http/auth/failValues': ['INVALID_OAUTHTOKEN'],
  }),
  fieldMap: {
    name: { fieldId: 'name' },
    'http.auth.oauth.scope': {
      fieldId: 'http.auth.oauth.scope',
      scopes: [
        'VirtualOffice.accounts.READ',
        'VirtualOffice.accounts.UPDATE',
        'VirtualOffice.partner.organization.READ',
        'VirtualOffice.partner.organization.UPDATE',
        'VirtualOffice.organization.subscriptions.READ',
        'VirtualOffice.organization.subscriptions.UPDATE',
        'VirtualOffice.organization.spam.READ',
        'VirtualOffice.organization.accounts.READ',
        'VirtualOffice.organization.accounts.CREATE',
        'VirtualOffice.organization.accounts.UPDATE',
        'VirtualOffice.messages.CREATE',
        'VirtualOffice.messages.READ',
        'VirtualOffice.messages.UPDATE',
        'VirtualOffice.messages.DELETE',
        'VirtualOffice.attachments.CREATE',
        'VirtualOffice.attachments.READ',
        'VirtualOffice.attachments.UPDATE',
        'VirtualOffice.attachments.DELETE',
        'VirtualOffice.organization.groups.CREATE',
        'VirtualOffice.organization.groups.READ',
        'VirtualOffice.organization.groups.UPDATE',
        'VirtualOffice.organization.groups.DELETE',
        'VirtualOffice.tags.CREATE',
        'VirtualOffice.tags.READ',
        'VirtualOffice.tags.UPDATE',
        'VirtualOffice.tags.DELETE',
        'VirtualOffice.folders.CREATE',
        'VirtualOffice.folders.READ',
        'VirtualOffice.folders.UPDATE',
        'VirtualOffice.folders.DELETE',
        'VirtualOffice.organization.domains.CREATE',
        'VirtualOffice.organization.domains.READ',
        'VirtualOffice.organization.domains.UPDATE',
        'VirtualOffice.organization.domains.DELETE',
      ],
    },
    httpAdvanced: { formId: 'httpAdvanced' },
  },
  layout: {
    fields: ['name', 'http.auth.oauth.scope'],
    type: 'collapse',
    containers: [
      { collapsed: true, label: 'Advanced Settings', fields: ['httpAdvanced'] },
    ],
  },
};
