export default {
  fields: [
    { id: 'connectionType' },
    { id: 'connectionName' },
    { id: 'connectionAssistant' },
    { id: 'connectionFtpHostURI' },
    { id: 'connectionFtpUsername' },
    { id: 'connectionFtpPassword' },
    { id: 'connectionFtpAuthKey' },
    { id: 'connectionFtpPort' },
    { id: 'connectionFtpUsePassiveMode' },
    { id: 'connectionFtpEntryParser' },
    { id: 'connectionFtpUserDirectoryIsRoot' },
    { id: 'connectionFtpUseImplicitFtps' },
    { id: 'connectionFtpRequireSocketReUse' },
    { id: 'connectionFtpPgpEncryptKey' },
    { id: 'connectionFtpPgpDecryptKey' },
    { id: 'connectionFtpPgpPassphrase' },
  ],
  fieldSets: [],
};
