export default {
  fields: [
    { id: 'connectionType' },
    { id: 'connectionName' },
    { id: 'connectionAssistant' },
    { id: 'connectionHttpMediaType' },
    { id: 'connectionHttpBaseURI' },
    { id: 'connectionHttpDisableStrictSSL' },
    { id: 'connectionHttpConcurrencyLevel' },
    { id: 'connectionHttpRetryHeader' },
    { id: 'connectionHttpHeaders' },
    { id: 'connectionHttpUnencrypted' },
    { id: 'connectionHttpEncrypted' },
    { id: 'connectionHttpEncrypteds' },
  ],
  fieldSets: [
    {
      header: 'ping',
      collapsed: false,
      fields: [
        { id: 'connectionHttpPingRelativeURI' },
        { id: 'connectionHttpPingMethod' },
        { id: 'connectionHttpPingBody' },
        { id: 'connectionHttpPingSuccessPath' },
        { id: 'connectionHttpPingSuccessValuess' },
        { id: 'connectionHttpPingErrorPath' },
      ],
    },
    {
      header: 'auth',
      collapsed: false,
      fields: [
        { id: 'connectionHttpAuthFailStatusCode' },
        { id: 'connectionHttpAuthFailPath' },
        { id: 'connectionHttpAuthFailValuess' },
        { id: 'connectionHttpAuthBasicUsername' },
        { id: 'connectionHttpAuthBasicPassword' },
        { id: 'connectionHttpAuthOauthAuthURI' },
        { id: 'connectionHttpAuthOauthTokenURI' },
        { id: 'connectionHttpAuthOauthScopes' },
        { id: 'connectionHttpAuthOauthScopeDelimiter' },
        { id: 'connectionHttpAuthOauthAccessTokenPath' },
        { id: 'connectionHttpAuthOauthGrantType' },
        { id: 'connectionHttpAuthOauthUsername' },
        { id: 'connectionHttpAuthOauthPassword' },
        { id: 'connectionHttpAuthTokenToken' },
        { id: 'connectionHttpAuthTokenLocation' },
        { id: 'connectionHttpAuthTokenHeaderName' },
        { id: 'connectionHttpAuthTokenScheme' },
        { id: 'connectionHttpAuthTokenParamName' },
        { id: 'connectionHttpAuthTokenRefreshMethod' },
        { id: 'connectionHttpAuthTokenRefreshRelativeURI' },
        { id: 'connectionHttpAuthTokenRefreshBody' },
        { id: 'connectionHttpAuthTokenRefreshTokenPath' },
        { id: 'connectionHttpAuthTokenRefreshMediaType' },
        { id: 'connectionHttpAuthTokenRefreshHeaders' },
        { id: 'connectionHttpAuthTokenRefreshToken' },
      ],
    },
    {
      header: 'rateLimit',
      collapsed: false,
      fields: [
        { id: 'connectionHttpRateLimitFailStatusCode' },
        { id: 'connectionHttpRateLimitFailPath' },
        { id: 'connectionHttpRateLimitFailValuess' },
        { id: 'connectionHttpRateLimitLimit' },
      ],
    },
  ],
};
