export default {
  fields: [
    { id: 'connection.type' },
    { id: 'connection.name' },
    { id: 'connection.assistant' },
    { id: 'connection.http.mediaType' },
    { id: 'connection.http.baseURI' },
    { id: 'connection.http.disableStrictSSL' },
    { id: 'connection.http.concurrencyLevel' },
    { id: 'connection.http.retryHeader' },
    { id: 'connection.http.headers' },
    { id: 'connection.http.unencrypted' },
    { id: 'connection.http.encrypted' },
    { id: 'connection.http.encrypteds' },
  ],
  fieldSets: [
    {
      header: 'ping',
      collapsed: false,
      fields: [
        { id: 'connection.http.ping.relativeURI' },
        { id: 'connection.http.ping.method' },
        { id: 'connection.http.ping.body' },
        { id: 'connection.http.ping.successPath' },
        { id: 'connection.http.ping.successValuess' },
        { id: 'connection.http.ping.errorPath' },
      ],
    },
    {
      header: 'auth',
      collapsed: false,
      fields: [
        { id: 'connection.Http.Auth.Fail.Status.Code' },
        { id: 'connection.Http.Auth.Fail.Path' },
        { id: 'connection.Http.Auth.Fail.Valuess' },
        { id: 'connection.Http.Auth.Basic.Username' },
        { id: 'connection.Http.Auth.Basic.Password' },
        { id: 'connection.Http.Auth.Oauth.Auth.URI' },
        { id: 'connection.Http.Auth.Oauth.Token.URI' },
        { id: 'connection.Http.Auth.Oauth.Scopes' },
        { id: 'connection.Http.Auth.Oauth.Scope.Delimiter' },
        { id: 'connection.Http.Auth.Oauth.Access.Token.Path' },
        { id: 'connection.Http.Auth.Oauth.Grant.Type' },
        { id: 'connection.Http.Auth.Oauth.Username' },
        { id: 'connection.Http.Auth.Oauth.Password' },
        { id: 'connection.Http.Auth.Token.Token' },
        { id: 'connection.Http.Auth.Token.Location' },
        { id: 'connection.Http.Auth.Token.Header.Name' },
        { id: 'connection.Http.Auth.Token.Scheme' },
        { id: 'connection.Http.Auth.Token.Param.Name' },
        { id: 'connection.Http.Auth.Token.Refresh.Method' },
        { id: 'connection.Http.Auth.Token.Refresh.Relative.URI' },
        { id: 'connection.Http.Auth.Token.Refresh.Body' },
        { id: 'connection.Http.Auth.Token.Refresh.Token.Path' },
        { id: 'connection.Http.Auth.Token.Refresh.Media.Type' },
        { id: 'connection.Http.Auth.Token.Refresh.Headers' },
        { id: 'connection.Http.Auth.Token.Refresh.Token' },
      ],
    },
    {
      header: 'rate.Limit',
      collapsed: false,
      fields: [
        { id: 'connection.Http.Rate.Limit.Fail.Status.Code' },
        { id: 'connection.Http.Rate.Limit.Fail.Path' },
        { id: 'connection.Http.Rate.Limit.Fail.Valuess' },
        { id: 'connection.Http.Rate.Limit.Limit' },
      ],
    },
  ],
};
