export default {
  fieldMap: {
    name: { fieldId: 'name' },
    description: { fieldId: 'description' },
    applications: { fieldId: 'applications' },
    sourceIntegration: { fieldId: 'sourceIntegration' },
    contactEmail: { fieldId: 'contactEmail' },
    websiteURL: { fieldId: 'websiteURL' },
    editions: { fieldId: 'editions' },
    _stackId: { fieldId: '_stackId' },
    installerFunction: { fieldId: 'installerFunction' },
    uninstallerFunction: { fieldId: 'uninstallerFunction' },
    updateFunction: { fieldId: 'updateFunction' },
    framework: { fieldId: 'framework' },
  },
  layout: {
    type: 'box',
    containers: [{
      fields: [
        'name',
        'description',
        'applications',
        'sourceIntegration',
        'contactEmail',
        'websiteURL',
        'editions',
        '_stackId',
        'installerFunction',
        'uninstallerFunction',
        'updateFunction',
        'framework',
      ],
    }],
  },
};
