dist: focal
language: node_js
node_js:
  - '18.12.1'
git:
  depth: 1
  submodules: false
before_install: git fetch --depth=50 origin refs/heads/$TRAVIS_BRANCH:refs/heads/$TRAVIS_BRANCH
install:
  - echo @celigo:registry=https://npm.pkg.github.com >> ~/.npmrc
  - echo //npm.pkg.github.com/:_authToken=$GIT_READ_PAT >> ~/.npmrc
  - yarn --frozen-lockfile
cache: yarn
jobs:
  fast_finish: true
  include:
    - stage: UI/UX test cases
      name: 'Data layer test cases and lint errors'
      script:
        - if [[ $TRAVIS_BRANCH == "master" ]]; then yarn test "src/(utils|reducers|sagas|forms|App|hooks)/" --changedSince=$TRAVIS_BRANCH && 
              yarn run lint; fi
        - if [[ $TRAVIS_BRANCH != "master" ]]; then yarn test "src/(utils|reducers|sagas|forms|App|hooks)/" && 
              yarn run lint; fi
    - script: 
      - if [[ $TRAVIS_BRANCH == "master" ]]; then yarn test "src/(views|components)/[A-CEa-ce0-9].*" --changedSince=$TRAVIS_BRANCH; fi
      - if [[ $TRAVIS_BRANCH != "master" ]]; then yarn test "src/(views|components)/[A-CEa-ce0-9].*"; fi

      name: 'UX test cases - part 1'
    - script: 
      - if [[ $TRAVIS_BRANCH == "master" ]]; then yarn test "src/(views|components)/(D|d).*" --changedSince=$TRAVIS_BRANCH; fi
      - if [[ $TRAVIS_BRANCH != "master" ]]; then yarn test "src/(views|components)/(D|d).*"; fi

      name: 'UX test cases - part 2'
    - script: 
      - if [[ $TRAVIS_BRANCH == "master" ]]; then yarn test "src/(views|components)/[F-If-i].*" --changedSince=$TRAVIS_BRANCH; fi
      - if [[ $TRAVIS_BRANCH != "master" ]]; then yarn test "src/(views|components)/[F-If-i].*"; fi

      name: 'UX test cases - part 3'
    - script: 
      - if [[ $TRAVIS_BRANCH == "master" ]]; then yarn test "src/(views|components)/[RrSs].*" --changedSince=$TRAVIS_BRANCH; fi
      - if [[ $TRAVIS_BRANCH != "master" ]]; then yarn test "src/(views|components)/[RrSs].*"; fi

      name: 'UX test cases - part 4'
    - script: 
      - if [[ $TRAVIS_BRANCH == "master" ]]; then yarn test "src/(views|components)/[J-QT-Zj-qt-z].*" --changedSince=$TRAVIS_BRANCH; fi
      - if [[ $TRAVIS_BRANCH != "master" ]]; then yarn test "src/(views|components)/[J-QT-Zj-qt-z].*"; fi

      name: 'UX test cases - part 5'
    - stage: build storybook
      if: branch = storybook
      script:
        - yarn build-storybook
      # Deployment information
      deploy:
        provider: pages # Tell Travis we want to deploy to Github Pages
        skip-cleanup: true
        github-token: $GITHUB_TOKEN # Will take the environment variable you created on step 5
        local_dir: storybook-static # The folder that needs to be deployed
        repo: celigo/integrator-ui # Add your username/project_name here
        target_branch: gh-pages # Tell Travis to deploy on the gh-pages branch
        on:
          branch: storybook # Tell Travis to trigger a deploy only when we push to this branch
