language: node_js
node_js:
  - '14'
git:
  depth: 1
  submodules: false
cache: false
jobs:
  fast_finish: true
  include:
    - stage: ui/ux test cases
      name: 'Data layer test cases'
      script: yarn test ".*\/(utils|reducers|sagas)\/.*.test.js"
    - script: yarn test --testPathIgnorePatterns=".*\/(utils|reducers|sagas)\/.*.test.js"
      name: 'UX test cases'
    - script: yarn run lint
      name: 'Linting errors'
    - stage: build storybook
      if: branch = storybook
      script:
        - yarn build-storybook
      # Deployment information
      deploy:
        provider: pages # Tell Travis we want to deploy to Github Pages
        skip-cleanup: true 
        github-token: $GITHUB_TOKEN # Will take the environment variable you created on step 5
        local_dir: storybook-static # The folder that needs to be deployed
        repo: celigo/integrator-ui # Add your username/project_name here
        target_branch: gh-pages # Tell Travis to deploy on the gh-pages branch
        on:
          branch: storybook # Tell Travis to trigger a deploy only when we push to this branch

