export default [
  {
    id: 'category1099misc',
    name: '1099-MISC Category',
    type: 'select',
    label: 'category1099misc',
  },
  { id: 'balance', name: 'Balance', type: 'currency', label: 'balance' },
  {
    id: 'cashflowratetype',
    name: 'Cash Flow Rate Type',
    type: 'select',
    label: 'cashflowratetype',
  },
  {
    id: 'description',
    name: 'Description',
    type: 'text',
    label: 'description',
  },
  {
    id: 'externalidstring',
    name: 'External ID (Text)',
    type: 'text',
    label: 'externalidstring',
  },
  { id: 'externalid', name: 'ExternalId', type: 'select', label: 'externalid' },
  {
    id: 'formuladate',
    name: 'Formula (Date)',
    type: 'date',
    label: 'formuladate',
  },
  {
    id: 'formulanumeric',
    name: 'Formula (Numeric)',
    type: 'float',
    label: 'formulanumeric',
  },
  {
    id: 'formulatext',
    name: 'Formula (Text)',
    type: 'text',
    label: 'formulatext',
  },
  {
    id: 'generalratetype',
    name: 'General Rate Type',
    type: 'select',
    label: 'generalratetype',
  },
  { id: 'isinactive', name: 'Inactive', type: 'checkbox', label: 'isinactive' },
  {
    id: 'internalid',
    name: 'Internal ID',
    type: 'select',
    label: 'internalid',
  },
  {
    id: 'internalidnumber',
    name: 'Internal ID (Number)',
    type: 'integer',
    label: 'internalidnumber',
  },
  { id: 'name', name: 'Name', type: 'text', label: 'name' },
  { id: 'number', name: 'Number', type: 'text', label: 'number' },
  {
    id: 'custrecord_fam_account_showinfixedasset',
    name: 'Show in Fixed Assets Management',
    type: 'multiselect',
    label: 'custrecord_fam_account_showinfixedasset',
  },
  { id: 'parent', name: 'Subaccount of', type: 'select', label: 'parent' },
  {
    id: 'subsidiary',
    name: 'Subsidiaries',
    type: 'select',
    label: 'subsidiary',
  },
  { id: 'type', name: 'Type', type: 'select', label: 'type' },
];
