export default {
  fieldMap: {
    name: { fieldId: 'name' },
    description: { fieldId: 'description' },
    // TODO: double check why we have ftp stuff here @Surya. (talk to dave)
    ftp: {
      formId: 'ftp',
      visibleWhenAll: [{ field: 'assistant', is: ['ftp'] }],
    },
    asynchronous: { fieldId: 'asynchronous' },
    apiIdentifier: { fieldId: 'apiIdentifier' },
    type: { fieldId: 'type' },
    pageSize: { fieldId: 'pageSize' },
    dataURITemplate: { fieldId: 'dataURITemplate' },
    oneToMany: { fieldId: 'oneToMany' },
    pathToMany: { fieldId: 'pathToMany' },
    sampleData: { fieldId: 'sampleData' },
    originSampleData: { fieldId: 'originSampleData' },
    assistantMetadata: { fieldId: 'assistantMetadata' },
    isLookup: { fieldId: 'isLookup' },
    useTechAdaptorForm: { fieldId: 'useTechAdaptorForm' },
    adaptorType: { fieldId: 'adaptorType' },
  },
  layout: {
    fields: [
      'name',
      'description',
      'ftp',
      'asynchronous',
      'apiIdentifier',
      'type',
      'pageSize',
      'dataURITemplate',
      'oneToMany',
      'pathToMany',
      'sampleData',
      'originSampleData',
      'assistantMetadata',
      'isLookup',
      'useTechAdaptorForm',
      'adaptorType',
    ],
  },
};
