export default {
  fields: [
    { fieldId: 'file.encoding' },
    { fieldId: 'file.output' },
    { fieldId: 'file.skipDelete' },
    { fieldId: 'file.compressionFormat' },
    { fieldId: 'file.csv.columnDelimiter' },
    { fieldId: 'file.csv.rowDelimiter' },
    { fieldId: 'file.csv.keyColumns' },
    { fieldId: 'file.csv.hasHeaderRow' },
    { fieldId: 'file.csv.trimSpaces' },
    { fieldId: 'file.csv.rowsToSkip' },
    { fieldId: 'file.json.resourcePath' },
    { fieldId: 'file.xlsx.hasHeaderRow' },
    { fieldId: 'file.xlsx.keyColumns' },
    { fieldId: 'file.xml.resourcePath' },
    { fieldId: 'file.fileDefinition.resourcePath' },
    { fieldId: 'file.fileDefinition._fileDefinitionId' },
    { fieldId: 'file.purgeInternalBackup' },
  ],
  fieldSets: [],
};
