export default {
  fields: [
    { fieldId: 'http.successMediaType' },
    { fieldId: 'http.errorMediaType' },
    { fieldId: 'http.relativeURI' },
    { fieldId: 'http.method' },
    { fieldId: 'http.body' },
    { fieldId: 'http.headers' },
    { fieldId: 'http.paging.method' },
    { fieldId: 'http.paging.skip' },
    { fieldId: 'http.paging.page' },
    { fieldId: 'http.paging.token' },
    { fieldId: 'http.paging.path' },
    { fieldId: 'http.paging.relativeURI' },
    { fieldId: 'http.paging.pathAfterFirstRequest' },
    { fieldId: 'http.paging.resourcePath' },
    { fieldId: 'http.paging.maxPagePath' },
    { fieldId: 'http.paging.maxCountPath' },
    { fieldId: 'http.paging.lastPageStatusCode' },
    { fieldId: 'http.paging.lastPagePath' },
    { fieldId: 'http.paging.lastPageValues' },
    { fieldId: 'http.paging.linkHeaderRelation' },
    { fieldId: 'http._asyncHelperId' },
    { fieldId: 'http.once.relativeURI' },
    { fieldId: 'http.once.method' },
    { fieldId: 'http.once.body' },
    { fieldId: 'http.response.resourcePath' },
    { fieldId: 'http.response.resourceIdPath' },
    { fieldId: 'http.response.successPath' },
    { fieldId: 'http.response.successValues' },
    { fieldId: 'http.response.errorPath' },
    { fieldId: 'http.response.blobFormat' },
  ],
  fieldSets: [],
};
