export default {
  fields: [
    { fieldId: 'netsuite.searches' },
    { fieldId: 'netsuite.metadata' },
    { fieldId: 'netsuite.selectoption' },
    { fieldId: 'netsuite.customFieldMetadata' },
    { fieldId: 'netsuite.skipGrouping' },
    { fieldId: 'netsuite.statsOnly' },
    { fieldId: 'netsuite.internalId' },
    { fieldId: 'netsuite.restlet.recordType' },
    { fieldId: 'netsuite.restlet.searchId' },
    { fieldId: 'netsuite.restlet.criteria[*].field' },
    { fieldId: 'netsuite.restlet.criteria[*].join' },
    { fieldId: 'netsuite.restlet.criteria[*].operator' },
    { fieldId: 'netsuite.restlet.criteria[*].searchValue' },
    { fieldId: 'netsuite.restlet.criteria[*].searchValue2' },
    { fieldId: 'netsuite.restlet.batchSize' },
    { fieldId: 'netsuite.restlet.hooks.batchSize' },
    { fieldId: 'netsuite.restlet.hooks.preSend.fileInternalId' },
    { fieldId: 'netsuite.restlet.hooks.preSend.function' },
    { fieldId: 'netsuite.restlet.hooks.preSend.configuration' },
    { fieldId: 'netsuite.distributed.recordType' },
    { fieldId: 'netsuite.distributed.executionContext' },
    { fieldId: 'netsuite.distributed.disabled' },
    { fieldId: 'netsuite.distributed.executionType' },
    { fieldId: 'netsuite.distributed.qualifier' },
    { fieldId: 'netsuite.distributed.hooks.preSend.fileInternalId' },
    { fieldId: 'netsuite.distributed.hooks.preSend.function' },
    { fieldId: 'netsuite.distributed.hooks.preSend.configuration' },
    { fieldId: 'netsuite.distributed.sublists' },
    { fieldId: 'netsuite.distributed.forceReload' },
    { fieldId: 'netsuite.distributed.ioEnvironment' },
    { fieldId: 'netsuite.distributed.lastSyncedDate' },
    { fieldId: 'netsuite.distributed.settings' },
    { fieldId: 'netsuite.getList[*].typeId' },
    { fieldId: 'netsuite.getList[*].internalId' },
    { fieldId: 'netsuite.getList[*].externalId' },
    { fieldId: 'netsuite.searchPreferences.bodyFieldsOnly' },
    { fieldId: 'netsuite.searchPreferences.pageSize' },
    { fieldId: 'netsuite.searchPreferences.returnSearchColumns' },
  ],
  fieldSets: [],
};
