export default {
  fields: [
    { formId: 'common' },
    { fieldId: 'exportData' },
    { fieldId: 'rest.method' },
    { fieldId: 'rest.headers' },
    { fieldId: 'rest.relativeURI' },
    { fieldId: 'rest.postBody' },
    { fieldId: 'rest.resourcePath' },
    { fieldId: 'rest.successPath' },
    { fieldId: 'rest.successValues' },
    { fieldId: 'type' },
    { fieldId: 'delta.dateFormat' },
    { fieldId: 'delta.lagOffset' },
    { fieldId: 'once.booleanField' },
    { fieldId: 'rest.once.relativeURI' },
    { fieldId: 'rest.once.method' },
    { fieldId: 'rest.once.postBody' },

    // { fieldId: 'rest.allowUndefinedResource' },

    { fieldId: 'pagingData' },
    { fieldId: 'rest.pagingMethod' },
    { fieldId: 'rest.nextPagePath' },
    { fieldId: 'rest.linkHeaderRelation' },
    { fieldId: 'rest.skipArgument' },
    { fieldId: 'rest.nextPageRelativeURI' },
    { fieldId: 'rest.pageArgument' },
    { fieldId: 'rest.pagingPostBody' },
    { fieldId: 'rest.maxPagePath' },
    { fieldId: 'rest.maxCountPath' },
    // { fieldId: 'rest.blobFormat' },
    { fieldId: 'rest.lastPageStatusCode' },
    { fieldId: 'rest.lastPagePath' },
    { fieldId: 'rest.lastPageValue' },
    { fieldId: 'exportTransformRecords' },
    { fieldId: 'transform.expression.rules' },
    { fieldId: 'exportHooks' },
    { formId: 'hooks' },
  ],
  fieldSets: [
    {
      header: 'Advanced Settings',
      collapsed: 'true',
      fields: [{ formId: 'advancedSettings' }],
    },
  ],
};
