export default {
  fields: [
    { fieldId: 'rest.relativeURI' },
    { fieldId: 'rest.method' },
    { fieldId: 'rest.postBody' },
    { fieldId: 'rest.resourcePath' },
    { fieldId: 'rest.headers' },
    { fieldId: 'rest.allowUndefinedResource' },
    { fieldId: 'rest.pagingMethod' },
    { fieldId: 'rest.nextPagePath' },
    { fieldId: 'rest.linkHeaderRelation' },
    { fieldId: 'rest.nextPageRelativeURI' },
    { fieldId: 'rest.pageArgument' },
    { fieldId: 'rest.pagingPostBody' },
    { fieldId: 'rest.maxPagePath' },
    { fieldId: 'rest.maxCountPath' },
    { fieldId: 'rest.skipArgument' },
    { fieldId: 'rest.blobFormat' },
    { fieldId: 'rest.successPath' },
    { fieldId: 'rest.successValues' },
    { fieldId: 'rest.lastPageStatusCode' },
    { fieldId: 'rest.lastPagePath' },
    { fieldId: 'rest.lastPageValue' },
    { fieldId: 'rest.once.relativeURI' },
    { fieldId: 'rest.once.method' },
    { fieldId: 'rest.once.postBody' },
  ],
  fieldSets: [],
};
