export default {
  Settings: 'With Developer mode enabled, the Settings tab is visible for each integration. Provided you also have Manager (write) access, you can define specific settings to apply to the integration. Enter valid JSON objects directly in the Settings editor. <a href="https://docs.celigo.com/hc/en-us/articles/360045461272#specify-simple" target="_blank">Learn more</a>',
  Profile: 'Set your preferences or change your password as needed.',
  AuditLog: 'Audit logs maintain a record of certain activities in your flows, including the fields that were changed, the type of change, and who’s responsible for the change. <a href="https://docs.celigo.com/hc/en-us/articles/6514515710107-Manage-your-audit-logs">Learn more about audit logs</a>.',
  Transfers: 'Transfer individual integrations between integrator.io accounts. Send integrations by specifying the email of the owner of the integrator.io account you want to send the integration to. The receiving account owner needs to accept the transfer. Once accepted, the integration will be removed from your account and instead reside in the receiver’s account. Note: the receiver needs to be an account owner and cannot be part of the same organization as the sender.',
  Subscription: 'See details of your product subscription and request an upgrade when needed. An endpoint refers to each application or technology service that you create a connection to in integrator.io. Unlimited connections to each application are allowed and only count as one endpoint.',
  Users: 'Invite users to either Administer your account, or Manage or Monitor your integrations. A user who has been invited to Administer an account will have all the same permissions as the account Owner, including inviting users and changing their access rights. A user who has been invited to Manage an integration will have permissions to edit existing flows or create flows within an integration tile. A user who has Monitor permissions will only be allowed to view the integration, they do not have permissions to make any changes. They are however allowed to run the flows within the integration. The user will see only those integrations that you have invited them to.',
  MFA: 'Enhanced security for integrator.io account access is available through multifactor authentication (MFA). Once MFA is enabled, you are required to enter a six-digit code sent to your mobile device to sign in to your account. Alternatively, you can set the option to trust the device you are using to sign in to integrator.io. <a href="https://docs.celigo.com/hc/en-us/articles/7127009384987" target="_blank">Learn more</a>',
  OwnerAdminSSO: 'Enhanced security for integrator.io account access is available through single sign-on (SSO). To enable SSO for your account, you must configure settings based on the details available in your SSO provider. These details are available after you have created an account with the SSO provider. <a href="https://docs.celigo.com/hc/en-us/articles/360060937871-Set-up-single-sign-on-SSO-for-an-account" target="_blank">Learn more</a>',
  AccountUserSSO: 'Enhanced security for integrator.io account access is available through single sign-on (SSO). If you are a part of multiple SSO-enabled accounts, then you must select one account to use for SSO before you authenticate for the first time. This account is also known as the primary SSO account, and you will use it for SSO sign in to integrator.io. <a href="https://docs.celigo.com/hc/en-us/articles/6720519866395-Sign-in-using-single-sign-on-SSO-" target="_blank">Learn more</a>',
  General: 'Describe your integration here so that other users can quickly understand the high-level business problems being solved.',
  Readme: 'Add documentation or links to articles you want other users to reference. <a href="https://docs.celigo.com/hc/en-us/articles/7703422519707-Update-your-integration-Admin-tab" target="_blank">Learn more</a>',
  Dashboard: 'You can view the flows that have  run or are currently running for each flow in your integration, as well as how long it took and when each job completed. If there are errors, click the number of errors in the Error column to resolve errors. You can edit jobs, and resolve errors directly from this view.',
};

