export default {
  AuditLog: 'Keep track of changes to your integration, enabling you to track down problems based on changes to your integration or its flows. Know exactly who made the change, what the change was, and when it happened.',
  Analytics: 'The Analytics tab shows graphs of total stats (success, error, ignore count) produced in the flow steps, helping you to see trends and identify performance issues or unexpected spikes in integration activity. You can visualize, for example, how many successes vs. errors did my integration experience over the last 30 days? Integration flow stats are available for up to one year.',
  integrationDashboard: 'This dashboard offers a comprehensive view of all running and completed flows in each integration.',
  accountDashboard: 'This dashboard offers a comprehensive view of all running and completed flows in your account.',
  Connections: 'In order to import or export data from a source app or a destination app, you must create a connection to that system. A connection stores the login credentials and other information needed to retrieve or send data through the application\'s API. If a connection is offline, all flows using that connection are paused until connectivity is restored.',
  Dashboard: 'You can view the flows that have run or are currently running for each flow in your integration, as well as how many pages of data were sent, how long it took and when each job completed. If there are child jobs within a parent job, you can expand the parent to view the children. If there are errors, click the number of errors in the Error column to retry and resolve errors. You can cancel jobs that are in progress, edit jobs, and resolve errors directly from this view.',
  Flow: 'You can see the status, scheduling info, and when a flow was last modified, as well as mapping fields, enabling, and running your flow. You can view any changes to a flow, as well as what is contained within the flow, and even clone or download a flow.',
  Notifications: 'Get notified via email if your flow encounters an error, or if a connection goes offline. These notifications will only be sent to you. If any other users in your account wish to receive the same notifications, then they will need to subscribe from their account.',
  Revisions: 'You can monitor and manage changes that anyone in your team makes to an integration over time (based on the access and permissions in an account or integration). The list displays every revision made to the integration as the result of a snapshot, pull, or revert. You can view details and perform actions on a revision based on the options available when you click the Actions overflow (...) menu for a revision. <a href="https://docs.celigo.com/hc/en-us/articles/5349100943003-Integration-Lifecycle-Management-ILM-overview">Learn more about Integration Lifecycle Management (ILM)</a>.',
};
