export const REST_ASSISTANTS = [
  '3dcart',
  'certify',
  'chargify',
  'docusign',
  'jet',
  'jira',
  'jobvite',
  'magento',
  'namely',
  'servicenow',
  'squareup',
  'stripe',
  'twilio',
  'woocommerce',
  'zendesk',
  'liquidplanner',
  'shipstation',
  'shipwire',
  'asana',
  'shopify',
  'slack',
  'eventbrite',
  'smartsheet',
  'campaignmonitor',
  'mailchimp',
  'chargebee',
  'googlesheets',
  'googlemail',
  'googlecontactspeople',
  'hubspot',
  'freshdesk',
  'harvest',
  'integratorio',
  'bigcommerce',
  'github',
  'shiphawk',
  'atera',
  'freshbooks',
  'yammer',
  'pulseway',
  'newrelic',
  'tableau',
  'sageone',
  'googleanalytics',
  'lightspeed',
  'tesco',
  'accelo',
  'fieldaware',
  'avalara',
  'googleshopping',
  'taxjar',
  'zuora',
  'snapfulfil',
  'coupa',
  'microsoftdynamics365',
  'zohodesk',
  'quip',
  'greenhouse',
  'zohocrm',
  'shippo',
  'easypost',
  'microsoftbusinesscentral',
  'microsoftoutlookcalendar',
  'microsoftoutlookmail',
  'microsoftoutlookcontacts',
  'microsoftonenote',
  'zohobooks',
  'pitneybowes',
  'insightly',
  'pdffiller',
  'ebay',
  'ebayfinance',
  'expensify',
  'wish',
  'exacterp',
  'acumatica',
  'acumaticaecommerce',
  'acumaticamanufacturing',
  'myobessentials',
  'zohomail',
  'bronto',
  'returnly',
  'klaviyo',
  'postmark',
  'procurify',
  'mailgun',
  'aptrinsic',
  'acton',
  'strata',
  'concur',
  'oandav20fxtrade',
  'tophatter',
  'spreecommerce',
  'concurv4',
  'powerbi',
  'sugarcrm',
  'oandaexchangerates',
  'marketo',
  'parseur',
  'grms',
  'sharepoint',
  'retailops',
  'concurall',
  'dunandbradstreet',
  'miva',
];
export const CONNECTORS_TO_IGNORE = [
  'yammer',
  'hybris',
  'concur',
  'concurall',
  'concurv4',
  'constantcontactv2',
  'constantcontactv3',
  'amazonsellingpartner',
  'ebayfinance',
  'recurlyv3',
  'loopreturnsv2',
  'acumaticaecommerce',
  'acumaticamanufacturing',
];

export const WEBHOOK_ONLY_APPLICATIONS = ['travis-org', 'helpscout', 'errorception', 'aha', 'mailparser-io', 'travis', 'sapariba'];
export const FILE_PROVIDER_ASSISTANTS = ['googledrive', 'azurestorageaccount', 'box', 'dropbox'];
export const RDBMS_TYPES = ['mysql', 'postgresql', 'mssql', 'snowflake', 'oracle', 'bigquerydatawarehouse', 'redshiftdatawarehouse', 'netsuitejdbc'];

export const MULTIPLE_AUTH_TYPE_ASSISTANTS = [
  'constantcontact',
  'constantcontactv2',
  'constantcontactv3',
  'zoom',
  'amazonmws',
  'ebay',
  'ebayfinance',
  'amazonsellingpartner',
  'recurly',
  'recurlyv3',
  'loopreturns',
  'loopreturnsv2',
  'acumatica',
  'acumaticaecommerce',
  'acumaticamanufacturing',
];
export const CONSTANT_CONTACT_VERSIONS = ['v2', 'v3'];
export const EBAY_TYPES = ['ebay', 'ebayfinance'];
export const AUTHENTICATION_LABELS = Object.freeze({
  basic: 'Basic',
  token: 'Token',
  oauth: 'OAuth 2.0',
  custom: 'Custom',
  cookie: 'Cookie',
  digest: 'Digest',
  wsse: 'WSSE',
  oauth1: 'OAuth 1.0',
});

export const SHOPIFY_SCOPES = [
  'read_content',
  'write_content',
  'read_themes',
  'write_themes',
  'read_products',
  'write_products',
  'read_product_listings',
  'read_customers',
  'write_customers',
  'read_orders',
  'write_orders',
  'read_all_orders',
  'read_draft_orders',
  'write_draft_orders',
  'read_inventory',
  'write_inventory',
  'read_locations',
  'read_script_tags',
  'write_script_tags',
  'read_fulfillments',
  'write_fulfillments',
  'read_shipping',
  'write_shipping',
  'read_analytics',
  'read_reports',
  'write_reports',
  'read_price_rules',
  'write_price_rules',
  'read_marketing_events',
  'write_marketing_events',
  'read_resource_feedbacks',
  'write_resource_feedbacks',
  'read_shopify_payments_payouts',
  'unauthenticated_read_product_listings',
  'unauthenticated_write_customers',
  'unauthenticated_read_content',
  'read_assigned_fulfillment_orders',
  'write_assigned_fulfillment_orders',
  'read_merchant_managed_fulfillment_orders',
  'write_merchant_managed_fulfillment_orders',
  'read_third_party_fulfillment_orders',
  'write_third_party_fulfillment_orders',
  'read_shopify_payments_disputes',
];
