export default {
  MERGE_BRANCH: 'MERGE_BRANCH',
  ADD_NEW_ROUTER: 'ADD_NEW_ROUTER',
  ADD_NEW_STEP: 'ADD_NEW_STEP',
  UNMERGE_BRANCH: 'UNMERGE_BRANCH',
  DELETE_STEP: 'DELETE_STEP',
  DELETE_EDGE: 'DELETE_EDGE',
  DRAG_START: 'DRAG_START',
  DRAG_END: 'DRAG_END',
  MERGE_TARGET_SET: 'MERGE_TARGET_SET',
  MERGE_TARGET_CLEAR: 'MERGE_TARGET_CLEAR',
  MERGE_BRANCH_NEW: 'MERGE_BRANCH_NEW',
};
