export default {
  fieldMap: {
    name: { fieldId: 'name' },
    description: { fieldId: 'description' },
    apiIdentifier: { fieldId: 'apiIdentifier' },
    sampleData: { fieldId: 'sampleData' },
    distributed: { fieldId: 'distributed' },
    maxAttempts: { fieldId: 'maxAttempts' },
    ignoreExisting: { fieldId: 'ignoreExisting' },
    ignoreMissing: { fieldId: 'ignoreMissing' },
    idLockTemplate: { fieldId: 'idLockTemplate' },
    dataURITemplate: { fieldId: 'dataURITemplate' },
    oneToMany: { fieldId: 'oneToMany' },
    pathToMany: { fieldId: 'pathToMany' },
    blobKeyPath: { fieldId: 'blobKeyPath' },
    deleteAfterImport: { fieldId: 'deleteAfterImport' },
    assistantMetadata: { fieldId: 'assistantMetadata' },
    useTechAdaptorForm: { fieldId: 'useTechAdaptorForm' },
    sampleResponseData: { fieldId: 'sampleResponseData' },
    modelMetadata: { fieldId: 'modelMetadata' },
    adaptorType: { fieldId: 'adaptorType' },
  },
  layout: {
    fields: [
      'name',
      'description',
      'apiIdentifier',
      'sampleData',
      'distributed',
      'maxAttempts',
      'ignoreExisting',
      'ignoreMissing',
      'idLockTemplate',
      'dataURITemplate',
      'oneToMany',
      'pathToMany',
      'blobKeyPath',
      'deleteAfterImport',
      'assistantMetadata',
      'useTechAdaptorForm',
      'sampleResponseData',
      'modelMetadata',
      'adaptorType',
    ],
  },
};
