export default {
  fields: [
    { fieldId: 'name' },
    { fieldId: 'description' },
    { fieldId: 'apiIdentifier' },
    { fieldId: 'sampleData' },
    { fieldId: 'distributed' },
    { fieldId: 'maxAttempts' },
    { fieldId: 'ignoreExisting' },
    { fieldId: 'ignoreMissing' },
    { fieldId: 'idLockTemplate' },
    { fieldId: 'dataURITemplate' },
    { fieldId: 'oneToMany' },
    { fieldId: 'pathToMany' },
    { fieldId: 'blobKeyPath' },
    { fieldId: 'deleteAfterImport' },
    { fieldId: 'assistantMetadata' },
    { fieldId: 'useTechAdaptorForm' },
    { fieldId: 'sampleResponseData' },
    { fieldId: 'modelMetadata' },
    { fieldId: 'adaptorType' },
  ],
  fieldSets: [],
};
