export default {
  fields: [
    { fieldId: 'file.delete' },
    { fieldId: 'file.skipAggregation' },
    { fieldId: 'file.compressionFormat' },
    { fieldId: 'file.purgeInternalBackup' },
    { fieldId: 'file.csv.rowDelimiter' },
    { fieldId: 'file.csv.columnDelimiter' },
    { fieldId: 'file.csv.includeHeader' },
    { fieldId: 'file.csv.wrapWithQuotes' },
    { fieldId: 'file.csv.replaceTabWithSpace' },
    { fieldId: 'file.csv.replaceNewlineWithSpace' },
    { fieldId: 'file.csv.customHeaderRows' },
    { fieldId: 'file.csv.headerRow' },
    { fieldId: 'file.xlsx.includeHeader' },
    { fieldId: 'file.xlsx.headerRow' },
    { fieldId: 'file.json.prettyPrint' },
    { fieldId: 'file.xml.body' },
    { fieldId: 'file.fileDefinition._fileDefinitionId' },
    { fieldId: 'file.lookups' },
    { fieldId: 'file.lookups[*].map' },
    { fieldId: 'file.lookups[*].default' },
    { fieldId: 'file.lookups[*].allowFailures' },
  ],
  fieldSets: [],
};
