export default {
  fields: [
    { formId: 'common' },
    { fieldId: 'ftp.directoryPath' },
    { fieldId: 'ftp.fileType' },
    { fieldId: 'ftp.fileName' },
    { fieldId: 'ftp.sampleFile' },
    { fieldId: 'ftp.columnDelimiter' },
    { fieldId: 'ftp.includeHeader' },
    { fieldId: 'ftp.advanceOption' },
    { fieldId: 'ftp.childRecords' },
    { fieldId: 'ftp.rowDelimiter' },
    { fieldId: 'ftp.useTempFile' },
    { fieldId: 'ftp.inProgressFileName' },
    { fieldId: 'ftp.skipAggregation' },
    { fieldId: 'ftp.compressFiles' },
    { fieldId: 'ftp.compressionFormat' },
    { fieldId: 'ftp.wrapWithQuotes' },
    { fieldId: 'ftp.replaceTabWithSpace' },
    { fieldId: 'ftp.replaceNewLineWithSpace' },
    { fieldId: 'hookType' },
    { fieldId: 'hooks.preMap.function' },
    { fieldId: 'hooks.preMap._scriptId' },
    { fieldId: 'hooks.preMap._stackId' },
    { fieldId: 'hooks.postMap.function' },
    { fieldId: 'hooks.postMap._scriptId' },
    { fieldId: 'hooks.postMap._stackId' },
    { fieldId: 'hooks.postSubmit.function' },
    { fieldId: 'hooks.postSubmit._scriptId' },
    { fieldId: 'hooks.postSubmit._stackId' },
    { fieldId: 'hooks.postAggregate.function' },
    { fieldId: 'hooks.postAggregate._scriptId' },
    { fieldId: 'hooks.postAggregate._stackId' },
  ],
  fieldSets: [],
};
