export default {
  fields: [
    { formId: 'common' },
    {
      id: 'importData',
      type: 'labeltitle',
      label: 'What would you like the data imported?',
    },
    { fieldId: 'file.parentOption' },
    { fieldId: 'file.childRecords' },
    { fieldId: 'http.method' },
    { fieldId: 'http.headers' },
    { fieldId: 'http.requestMediaType' },
    { fieldId: 'http.compositeType' },
    { fieldId: 'http.relativeUri' },
    { fieldId: 'http.successPath' },
    { fieldId: 'http.successValues' },
    { fieldId: 'http.responseIdPath' },
    { fieldId: 'http.responsePath' },
    { fieldId: 'http.errorPath' },
    { fieldId: 'http.batchSizeLimit' },
    {
      id: 'createNewData',
      type: 'labeltitle',
      label: 'Create New Data',
      visibleWhen: [
        {
          field: 'http.compositeType',
          is: ['CREATE_AND_UPDATE', 'CREATE_AND_IGNORE'],
        },
      ],
    },
    { fieldId: 'http.compositeMethodCreate' },
    { fieldId: 'http.relativeUriCreate' },
    { fieldId: 'http.responseIdPathCreate' },
    { fieldId: 'http.responsePathCreate' },
    {
      id: 'upateExistingData',
      type: 'labeltitle',
      label: 'Upate Existing Data',
      visibleWhen: [
        {
          field: 'http.compositeType',
          is: ['CREATE_AND_UPDATE', 'UPDATE_AND_IGNORE'],
        },
      ],
    },
    { fieldId: 'http.compositeMethodUpdate' },
    { fieldId: 'http.relativeUriUpdate' },
    { fieldId: 'http.responseIdPathUpdate' },
    { fieldId: 'http.responsePathUpdate' },
    {
      id: 'ignoreExistingData',
      type: 'labeltitle',
      label: 'Ignore Existing Data',
      visibleWhen: [
        {
          field: 'http.compositeType',
          is: ['CREATE_AND_IGNORE', 'UPDATE_AND_IGNORE'],
        },
      ],
    },
    { fieldId: 'http.existingDataId' },
    {
      id: 'mediatypeInformation',
      type: 'labeltitle',
      label: 'Media type information',
    },
    { fieldId: 'http.successMediaType' },
    { fieldId: 'http.errorMediaType' },
    { fieldId: 'http.sampleFile' },
    { fieldId: 'http.columnDelimiter' },
    { fieldId: 'http.includeHeader' },
    { fieldId: 'http.customHeaderRows' },
    {
      id: 'dataMapped',
      type: 'labeltitle',
      label: 'How should the data be mapped?',
    },
    { fieldId: 'file.parentOption' },
    { fieldId: 'file.childRecords' },
  ],
  fieldSets: [
    {
      header: 'Advanced',
      collapsed: true,
      fields: [
        { fieldId: 'http.rowDelimiter' },
        { fieldId: 'http.replaceTabWithSpace' },
        { fieldId: 'http.replaceNewLineWithSpace' },
        { fieldId: 'http.ignoreEmptyNodes' },
        { fieldId: 'http.concurrencyIdLockTemplate' },
        { fieldId: 'http.dataUriTemplate' },
        { fieldId: 'http.configureAsyncHelper' },
      ],
    },
    {
      header: 'Hooks (Optional, Developers Only)',
      collapsed: false,
      fields: [{ formId: 'hooks' }],
    },
  ],
};
