export default {
  fields: [
    { fieldId: 'mapping.' },
    { fieldId: 'mapping.' },
    { fieldId: 'mapping.' },
    { fieldId: 'mapping.' },
    { fieldId: 'mapping.' },
    { fieldId: 'mapping.' },
    { fieldId: 'mapping.' },
    { fieldId: 'mapping.' },
    { fieldId: 'mapping.' },
    { fieldId: 'mapping.' },
    { fieldId: 'mapping.' },
    { fieldId: 'mapping.' },
    { fieldId: 'mapping.' },
    { fieldId: 'mapping.' },
    { fieldId: 'mapping.' },
    { fieldId: 'mapping.lists[*].generate' },
    { fieldId: 'mapping.lists[*].' },
    { fieldId: 'mapping.lists[*].' },
    { fieldId: 'mapping.lists[*].' },
    { fieldId: 'mapping.lists[*].' },
    { fieldId: 'mapping.lists[*].' },
    { fieldId: 'mapping.lists[*].' },
    { fieldId: 'mapping.lists[*].' },
    { fieldId: 'mapping.lists[*].' },
    { fieldId: 'mapping.lists[*].' },
    { fieldId: 'mapping.lists[*].' },
    { fieldId: 'mapping.lists[*].' },
    { fieldId: 'mapping.lists[*].' },
    { fieldId: 'mapping.lists[*].' },
    { fieldId: 'mapping.lists[*].' },
    { fieldId: 'mapping.lists[*].' },
  ],
  fieldSets: [],
};
