export default {
  fields: [
    { fieldId: 'netsuite.operation' },
    { fieldId: 'netsuite.customFieldMetadata' },
    { fieldId: 'netsuite.recordType' },
    { fieldId: 'netsuite.recordTypeId' },
    { fieldId: 'netsuite.retryUpdateAsAdd' },
    { fieldId: 'netsuite.batchSize' },
    { fieldId: 'netsuite.internalIdLookup.extract' },
    { fieldId: 'netsuite.internalIdLookup.searchField' },
    { fieldId: 'netsuite.internalIdLookup.expression' },
    { fieldId: 'netsuite.lookups' },
    { fieldId: 'netsuite.lookups[*].map' },
    { fieldId: 'netsuite.lookups[*].default' },
    { fieldId: 'netsuite.lookups[*].recordType' },
    { fieldId: 'netsuite.lookups[*].searchField' },
    { fieldId: 'netsuite.lookups[*].expression' },
    { fieldId: 'netsuite.lookups[*].resultField' },
    { fieldId: 'netsuite.lookups[*].includeInactive' },
    { fieldId: 'netsuite.lookups[*].allowFailures' },
    { fieldId: 'netsuite.preferences.ignoreReadOnlyFields' },
    { fieldId: 'netsuite.preferences.warningAsError' },
    { fieldId: 'netsuite.preferences.skipCustomMetadataRequests' },
    { fieldId: 'netsuite.file.name' },
    { fieldId: 'netsuite.file.fileType' },
    { fieldId: 'netsuite.file.folder' },
    { fieldId: 'netsuite.file.internalId' },
  ],
  fieldSets: [],
};
