export default {
  fields: [
    { formId: 'common' },
    {
      id: 'importData',
      type: 'labeltitle',
      label: 'What would you like the data imported?',
    },
    { fieldId: 'rest.method' },
    { fieldId: 'rest.headers' },
    { fieldId: 'rest.compositeType' },
    { fieldId: 'rest.relativeUri' },
    { fieldId: 'rest.successPath' },
    { fieldId: 'rest.successValues' },
    { fieldId: 'rest.responseIdPath' },
    { fieldId: 'rest.createNewData' },
    { fieldId: 'rest.compositeMethodCreate' },
    { fieldId: 'rest.relativeUriCreate' },
    { fieldId: 'rest.successPathCreate' },
    { fieldId: 'rest.successValuesCreate' },
    { fieldId: 'rest.responseIdPathCreate' },
    { fieldId: 'rest.upateExistingData' },
    { fieldId: 'rest.compositeMethodUpdate' },
    { fieldId: 'rest.relativeUriUpdate' },
    { fieldId: 'rest.successPathUpdate' },
    { fieldId: 'rest.successValuesUpdate' },
    { fieldId: 'rest.responseIdPathUpdate' },
    { fieldId: 'rest.ignoreExistingData' },
    { fieldId: 'rest.existingDataId' },
    {
      id: 'sampleData',
      type: 'labeltitle',
      label: 'Do you have sample data?',
    },
    { fieldId: 'rest.ifSoPleasePasteItHere' },
    {
      id: 'dataMapped',
      type: 'labeltitle',
      label: 'How should the data be mapped?',
    },
    { fieldId: 'rest.parentOption' },
    { fieldId: 'rest.childRecords' },
  ],
  fieldSets: [
    {
      header: 'Advanced',
      collapsed: true,
      fields: [
        { fieldId: 'rest.concurrencyIdLockTemplate' },
        { fieldId: 'rest.dataUriTemplate' },
      ],
    },
    {
      header: 'Hooks (Optional, Developers Only)',
      collapsed: false,
      fields: [{ formId: 'hooks' }],
    },
  ],
};
