export default {
  fields: [
    { fieldId: 'salesforce.operation' },
    { fieldId: 'salesforce.api' },
    { fieldId: 'salesforce.soap.headers.allOrNone' },
    { fieldId: 'salesforce.soap.batchSize' },
    { fieldId: 'salesforce.sObjectType' },
    { fieldId: 'salesforce.idLookup.extract' },
    { fieldId: 'salesforce.idLookup.whereClause' },
    { fieldId: 'salesforce.upsert.externalIdField' },
    { fieldId: 'salesforce.upsertpicklistvalues.fullName' },
    { fieldId: 'salesforce.upsertpicklistvalues.visibleLines' },
    { fieldId: 'salesforce.removeNonSubmittableFields' },
    { fieldId: 'salesforce.lookups[*].allowFailures' },
    { fieldId: 'salesforce.lookups' },
    { fieldId: 'salesforce.lookups[*].map' },
    { fieldId: 'salesforce.lookups[*].default' },
    { fieldId: 'salesforce.lookups[*].sObjectType' },
    { fieldId: 'salesforce.lookups[*].resultField' },
    { fieldId: 'salesforce.lookups[*].whereClause' },
    { fieldId: 'salesforce.document.id' },
    { fieldId: 'salesforce.document.name' },
    { fieldId: 'salesforce.document.folderId' },
    { fieldId: 'salesforce.document.contentType' },
    { fieldId: 'salesforce.document.developerName' },
    { fieldId: 'salesforce.document.isInternalUseOnly' },
    { fieldId: 'salesforce.document.isPublic' },
    { fieldId: 'salesforce.attachment.id' },
    { fieldId: 'salesforce.attachment.name' },
    { fieldId: 'salesforce.attachment.parentId' },
    { fieldId: 'salesforce.attachment.contentType' },
    { fieldId: 'salesforce.attachment.isPrivate' },
    { fieldId: 'salesforce.attachment.description' },
    { fieldId: 'salesforce.contentVersion.id' },
    { fieldId: 'salesforce.contentVersion.title' },
    { fieldId: 'salesforce.contentVersion.pathOnClient' },
    { fieldId: 'salesforce.contentVersion.tagCsv' },
    { fieldId: 'salesforce.contentVersion.contentLocation' },
  ],
  fieldSets: [],
};
