export default [
  { name: 'YYMMDD', value: 'YYMMDD' },
  { name: 'MMDDYY', value: 'MMDDYY' },
  { name: 'DDMMYY', value: 'DDMMYY' },
  { name: 'YY-MM-DD', value: 'YY-MM-DD' },
  { name: 'YYYY-MM-DD', value: 'YYYY-MM-DD' },
  { name: 'YYYY-MM-DDTHH:mm:ssZ', value: 'YYYY-MM-DDTHH:mm:ssZ' },
  { name: 'YYYY-MM-DDTHH:mm:ss.SSSZZ', value: 'YYYY-MM-DDTHH:mm:ss.SSSZZ' },
  { name: 'HHmmss', value: 'HHmmss' },
  { name: 'DD-Mon-YY', value: 'DD-Mon-YY' },
  { name: 'DD-Mon-YYYY', value: 'DD-Mon-YYYY' },
  { name: 'DD-Mon-YYYY hh:mm:ss', value: 'DD-Mon-YYYY hh:mm:ss' },
  { name: 'DD-Mon-YYYY hh-mm-ss', value: 'DD-Mon-YYYY hh-mm-ss' },
  { name: 'DD.MM.YY', value: 'DD.MM.YY' },
  { name: 'DD.MM.YYYY', value: 'DD.MM.YYYY' },
  { name: 'DD.MM.YYYY hh:mm:ss', value: 'DD.MM.YYYY hh:mm:ss' },
  { name: 'DD.MM.YYYY hh-mm-ss', value: 'DD.MM.YYYY hh-mm-ss' },
  { name: 'DD-MONTH-YY', value: 'DD-MONTH-YY' },
  { name: 'DD-MONTH-YYYY', value: 'DD-MONTH-YYYY' },
  { name: 'DD-MONTH-YYYY hh:mm:ss', value: 'DD-MONTH-YYYY hh:mm:ss' },
  { name: 'DD-MONTH-YYYY hh-mm-ss', value: 'DD-MONTH-YYYY hh-mm-ss' },
  { name: 'DD MONTH, YY', value: 'DD MONTH, YY' },
  { name: 'DD MONTH, YYYY', value: 'DD MONTH, YYYY' },
  { name: 'DD MONTH, YYYY hh:mm:ss', value: 'DD MONTH, YYYY hh:mm:ss' },
  { name: 'DD MONTH, YYYY hh-mm-ss', value: 'DD MONTH, YYYY hh-mm-ss' },
  { name: 'DDMMYYYY', value: 'DDMMYYYY' },
  { name: 'DDMMYYYY hh:mm:ss', value: 'DDMMYYYY hh:mm:ss' },
  { name: 'DDMMYYYY hh-mm-ss', value: 'DDMMYYYY hh-mm-ss' },
  { name: 'DD-MM-YY', value: 'DD-MM-YY' },
  { name: 'DD-MM-YYYY', value: 'DD-MM-YYYY' },
  { name: 'DD-MM-YYYY hh:mm:ss', value: 'DD-MM-YYYY hh:mm:ss' },
  { name: 'DD-MM-YYYY hh-mm-ss', value: 'DD-MM-YYYY hh-mm-ss' },
  { name: 'YYYYMMDD', value: 'YYYYMMDD' },
  { name: 'YYYYMMDD hh:mm:ss', value: 'YYYYMMDD hh:mm:ss' },
  { name: 'YYYYMMDD hh-mm-ss', value: 'YYYYMMDD hh-mm-ss' },
  { name: 'MMDDYYYY', value: 'MMDDYYYY' },
  { name: 'MMDDYYYY hh:mm:ss', value: 'MMDDYYYY hh:mm:ss' },
  { name: 'MMDDYYYY hh-mm-ss', value: 'MMDDYYYY hh-mm-ss' },
  { name: 'YYYY-MM-DD hh:mm:ss', value: 'YYYY-MM-DD hh:mm:ss' },
  { name: 'MM/DD/YYYY', value: 'MM/DD/YYYY' },
];
