export default [
  ['abs', 'ABS'],
  ['add', 'ADD'],
  ['and', 'AND'],
  ['avg', 'AVG'],
  ['base64Encode', 'BASE64 ENCODE'],
  ['base64htmlEncode', 'BASE64 HTML ENCODE'],
  ['capitalize', 'CAPITALIZE'],
  ['capitalizeAll', 'CAPITALIZE ALL'],
  ['ceil', 'CEIL'],
  ['compare', 'COMPARE'],
  ['contains', 'CONTAINS'],
  ['dateAdd', 'DATE ADD'],
  ['dateFormat', 'DATE FORMAT'],
  ['decodeURI', 'DECODEURI'],
  ['divide', 'DIVIDE'],
  ['each', 'EACH'],
  ['encodeURI', 'ENCODE URI'],
  ['encodeURIhtml', 'ENCODE URI AND HTML'],
  ['floor', 'FLOOR'],
  ['getValue', 'GET VALUE'],
  ['ifEven', 'IF EVEN'],
  ['if_else', 'IF/ELSE'],
  ['join', 'JOIN'],
  ['jsonEncode', 'JSON ENCODE'],
  ['jsonSerialize', 'JSON SERIALIZE'],
  ['lowercase', 'LOWER CASE'],
  ['multiply', 'MULTIPLY'],
  ['neither', 'NEITHER'],
  ['or', 'OR'],
  ['random', 'RANDOM'],
  ['regexMatch', 'REGEXP MATCH'],
  ['regexReplace', 'REGEXP REPLACE'],
  ['replace', 'REPLACE'],
  ['round', 'ROUND'],
  ['sortnumbers', 'SORT NUMBERS'],
  ['sortstrings', 'SORT STRINGS'],
  ['split', 'SPLIT'],
  ['substring', 'SUBSTRING'],
  ['subtract', 'SUBTRACT'],
  ['sum', 'SUM'],
  ['timeStamp', 'TIME STAMP'],
  ['toExponential', 'TO EXPONENTIAL'],
  ['toFixed', 'TO FIXED'],
  ['toPrecision', 'TO PRECISION'],
  ['trim', 'TRIM'],
  ['unless', 'UNLESS'],
  ['uppercase', 'UPPER CASE'],
  ['with', 'WITH'],
];
