export default [
  {
    id: 'Name',
    name: '/name',
    type: 'text',
    label: 'Name',
    description: '',
    placeholder: '',
    defaultValue: '',
    options: [],
    visible: true,
    required: true,
    disabled: false,
    visibleWhen: [],
    requiredWhen: [],
    disabledWhen: [],
    omitWhenHidden: true,
    valueDelimiter: '',
    useChangesAsValues: false,
    shouldMatchRegex: false,
    hasMinLength: false,
    hasMaxLength: false,
    hasNumericalRange: false,
    shouldCompareTo: false,
  },
  {
    id: 'description',
    name: '/description',
    type: 'textarea',
    label: 'Description',
    description: '',
    placeholder: '',
    defaultValue: '',
  },
  {
    id: 'method',
    name: '/http/method',
    type: 'select',
    label: 'HTTP method',
    description: '',
    placeholder: '',
    defaultValue: '',
    options: [
      {
        items: [
          {
            value: 'GET',
          },
          {
            value: 'POST',
          },
        ],
      },
    ],
    visible: true,
    required: true,
    disabled: false,
    visibleWhen: [],
    requiredWhen: [],
    disabledWhen: [],
  },
  {
    id: 'relativeUri',
    name: '/http/relativeURI',
    type: 'relativeUri',
    label: 'Relative URI',
    visible: true,
    required: true,
    validWhen: {
      lengthIsGreaterThan: {
        length: 3,
        message: 'The value must have more than 3 characterrs',
      },
      lengthIsLessThan: {
        length: 6,
        message: 'The value must less than 6 characters',
      },
      fallsWithinNumericalRange: {
        min: 150,
        max: 80000,
        message: 'The value must be more than 150 and less than 80000',
      },
      matchesRegEx: {
        pattern: '^[\\d]+$',
        message: 'Only numbers allowed',
      },
      isNot: {
        values: ['2500', '4001'],
        message: 'The value cannot be 2500 nor 4001',
      },
    },
  },
  {
    id: 'body',
    name: '/http/body',
    type: 'text',
    multiline: true,
    rowsMax: 5,
    label: 'HTTP Body',
    visibleWhen: [
      {
        id: 'isPost',
        field: 'method',
        is: ['POST'],
      },
    ],
    description: '',
    placeholder: '',
    defaultValue: '',
  },
];
