// This is a sample file and is used for development purpose
// TODO (Aditya): Delete the file after use

export default [
  {
    group: 'Body Field',
    id: 'alldayevent',
    name: 'All Day',
    type: 'checkbox',
  },
  {
    group: 'Body Field',
    id: 'company.internalid',
    name: 'Company (InternalId)',
    type: 'select',
  },
  {
    group: 'Body Field',
    id: 'company',
    name: 'Company (Name)',
    type: 'select',
  },
  {
    group: 'Body Field',
    id: 'contact.internalid',
    name: 'Contact (InternalId)',
    type: 'select',
  },
  {
    group: 'Body Field',
    id: 'contact',
    name: 'Contact (Name)',
    type: 'select',
  },
  {
    group: 'Body Field',
    id: 'customform.internalid',
    name: 'Custom Form (InternalId)',
    type: 'select',
  },
  {
    group: 'Body Field',
    id: 'customform',
    name: 'Custom Form (Name)',
    type: 'select',
  },
  {
    group: 'Body Field',
    id: 'startdate',
    name: 'Date',
    type: 'date',
  },
  {
    group: 'Body Field',
    id: '_eml_nkey_',
    name: 'Email Login Key',
    type: 'text',
  },
  {
    group: 'Body Field',
    id: 'endbydate',
    name: 'End By',
    type: 'date',
  },
  {
    group: 'Body Field',
    id: 'endtime',
    name: 'End Time',
    type: 'timeofday',
  },
  {
    group: 'Body Field',
    id: 'accesslevel.internalid',
    name: 'Event Access (InternalId)',
    type: 'select',
  },
  {
    group: 'Body Field',
    id: 'accesslevel',
    name: 'Event Access (Name)',
    type: 'select',
  },
  {
    group: 'Body Field',
    id: 'externalid',
    name: 'ExternalId',
    type: 'text',
  },
  {
    group: 'Body Field',
    id: '_week_dow_6',
    name: 'Friday',
    type: 'checkbox',
  },
  {
    group: 'Body Field',
    id: 'celigo_ignore_mandatory_fields',
    name: 'Ignore Mandatory Fields',
    type: 'checkbox',
  },
  {
    group: 'Body Field',
    id: 'celigo_initializeValues',
    name: 'Initialize Values',
    type: 'text',
  },
  {
    group: 'Body Field',
    id: 'internalid',
    name: 'Internal ID',
    type: 'text',
  },
  {
    group: 'Body Field',
    id: 'relateditem.internalid',
    name: 'Item (InternalId)',
    type: 'select',
  },
  {
    group: 'Body Field',
    id: 'relateditem',
    name: 'Item (Name)',
    type: 'select',
  },
  {
    group: 'Body Field',
    id: 'location',
    name: 'Location',
    type: 'text',
  },
  {
    group: 'Body Field',
    id: 'mfgrouting.internalid',
    name: 'Manufacturing Routing (InternalId)',
    type: 'select',
  },
  {
    group: 'Body Field',
    id: 'mfgrouting',
    name: 'Manufacturing Routing (Name)',
    type: 'select',
  },
  {
    group: 'Body Field',
    id: '_week_dow_2',
    name: 'Monday',
    type: 'checkbox',
  },
  {
    group: 'Body Field',
    id: 'noenddate',
    name: 'No End Date',
    type: 'checkbox',
  },
  {
    group: 'Body Field',
    id: 'sendemail',
    name: 'Notify Attendees by Email',
    type: 'checkbox',
  },
  {
    group: 'Body Field',
    id: 'organizer.internalid',
    name: 'Organizer (InternalId)',
    type: 'select',
  },
  {
    group: 'Body Field',
    id: 'organizer',
    name: 'Organizer (Name)',
    type: 'select',
  },
  {
    group: 'Body Field',
    id: 'celigo_write_log',
    name: 'Print Nlapi Debug Logs',
    type: 'checkbox',
  },
  {
    group: 'Body Field',
    id: 'reminderminutes.internalid',
    name: 'Reminder (InternalId)',
    type: 'select',
  },
  {
    group: 'Body Field',
    id: 'reminderminutes',
    name: 'Reminder (Name)',
    type: 'select',
  },
  {
    group: 'Body Field',
    id: 'remindertype.internalid',
    name: 'Reminder Type (InternalId)',
    type: 'select',
  },
  {
    group: 'Body Field',
    id: 'remindertype',
    name: 'Reminder Type (Name)',
    type: 'select',
  },
  {
    group: 'Body Field',
    id: 'timedevent',
    name: 'Reserve Time',
    type: 'checkbox',
  },
  {
    group: 'Body Field',
    id: '_week_dow_7',
    name: 'Saturday',
    type: 'checkbox',
  },
  {
    group: 'Body Field',
    id: 'starttime',
    name: 'Start Time',
    type: 'timeofday',
  },
  {
    group: 'Body Field',
    id: 'status.internalid',
    name: 'Status (InternalId)',
    type: 'select',
  },
  {
    group: 'Body Field',
    id: 'status',
    name: 'Status (Name)',
    type: 'select',
  },
  {
    group: 'Body Field',
    id: '_week_dow_1',
    name: 'Sunday',
    type: 'checkbox',
  },
  {
    group: 'Body Field',
    id: 'supportcase.internalid',
    name: 'Support Case (InternalId)',
    type: 'select',
  },
  {
    group: 'Body Field',
    id: 'supportcase',
    name: 'Support Case (Name)',
    type: 'select',
  },
  {
    group: 'Body Field',
    id: '_week_dow_5',
    name: 'Thursday',
    type: 'checkbox',
  },
  {
    group: 'Body Field',
    id: 'title',
    name: 'Title',
    type: 'text',
  },
  {
    group: 'Body Field',
    id: 'transaction.internalid',
    name: 'Transaction (InternalId)',
    type: 'select',
  },
  {
    group: 'Body Field',
    id: 'transaction',
    name: 'Transaction (Name)',
    type: 'select',
  },
  {
    group: 'Body Field',
    id: '_week_dow_3',
    name: 'Tuesday',
    type: 'checkbox',
  },
  {
    group: 'Body Field',
    id: 'celigo_recordmode_dynamic',
    name: 'Use Dynamic Mode',
    type: 'checkbox',
  },
  {
    group: 'Body Field',
    id: '_week_dow_4',
    name: 'Wednesday',
    type: 'checkbox',
  },
  {
    group: 'Body Field',
    id: '_frequency',
    name: 'Yearly Event',
    type: 'radio',
  },
  {
    group: 'Body Field',
    id: '_day_mode',
    name: '_day_mode',
    type: 'radio',
  },
  {
    group: 'Body Field',
    id: '_day_period',
    name: '_day_period',
    type: 'integer',
  },
  {
    group: 'Body Field',
    id: '_month_dom',
    name: '_month_dom',
    type: 'integer',
  },
  {
    group: 'Body Field',
    id: '_month_dom_period',
    name: '_month_dom_period',
    type: 'integer',
  },
  {
    group: 'Body Field',
    id: '_month_dow.internalid',
    name: '_month_dow (InternalId)',
    type: 'select',
  },
  {
    group: 'Body Field',
    id: '_month_dow',
    name: '_month_dow (Name)',
    type: 'select',
  },
  {
    group: 'Body Field',
    id: '_month_dowim.internalid',
    name: '_month_dowim (InternalId)',
    type: 'select',
  },
  {
    group: 'Body Field',
    id: '_month_dowim',
    name: '_month_dowim (Name)',
    type: 'select',
  },
  {
    group: 'Body Field',
    id: '_month_dowim_period',
    name: '_month_dowim_period',
    type: 'integer',
  },
  {
    group: 'Body Field',
    id: '_month_mode',
    name: '_month_mode',
    type: 'radio',
  },
  {
    group: 'Body Field',
    id: '_week_period',
    name: '_week_period',
    type: 'integer',
  },
  {
    group: 'Body Field',
    id: '_year_dom',
    name: '_year_dom',
    type: 'integer',
  },
  {
    group: 'Body Field',
    id: '_year_dow.internalid',
    name: '_year_dow (InternalId)',
    type: 'select',
  },
  {
    group: 'Body Field',
    id: '_year_dow',
    name: '_year_dow (Name)',
    type: 'select',
  },
  {
    group: 'Body Field',
    id: '_year_dowim.internalid',
    name: '_year_dowim (InternalId)',
    type: 'select',
  },
  {
    group: 'Body Field',
    id: '_year_dowim',
    name: '_year_dowim (Name)',
    type: 'select',
  },
  {
    group: 'Body Field',
    id: '_year_dowim_month.internalid',
    name: '_year_dowim_month (InternalId)',
    type: 'select',
  },
  {
    group: 'Body Field',
    id: '_year_dowim_month',
    name: '_year_dowim_month (Name)',
    type: 'select',
  },
  {
    group: 'Body Field',
    id: '_year_mode',
    name: '_year_mode',
    type: 'radio',
  },
  {
    group: 'Body Field',
    id: '_year_month.internalid',
    name: '_year_month (InternalId)',
    type: 'select',
  },
  {
    group: 'Body Field',
    id: '_year_month',
    name: '_year_month (Name)',
    type: 'select',
  },
  {
    group: 'Body Field',
    id: 'enddate',
    name: 'enddate',
    type: 'text',
  },
  {
    group: 'Body Field',
    id: 'endtimepicker.internalid',
    name: 'endtimepicker (InternalId)',
    type: 'select',
  },
  {
    group: 'Body Field',
    id: 'endtimepicker',
    name: 'endtimepicker (Name)',
    type: 'select',
  },
  {
    group: 'Body Field',
    id: 'message',
    name: 'message',
    type: 'richtext',
  },
  {
    group: 'Body Field',
    id: 'r1',
    name: 'r1',
    type: 'fieldset_inline',
  },
  {
    group: 'Body Field',
    id: 'r2',
    name: 'r2',
    type: 'fieldset_inline',
  },
  {
    group: 'Body Field',
    id: 'row1spacer',
    name: 'row1spacer',
    type: 'textarea',
  },
  {
    group: 'Body Field',
    id: 'row2spacer',
    name: 'row2spacer',
    type: 'textarea',
  },
  {
    group: 'Body Field',
    id: 'starttimepicker.internalid',
    name: 'starttimepicker (InternalId)',
    type: 'select',
  },
  {
    group: 'Body Field',
    id: 'starttimepicker',
    name: 'starttimepicker (Name)',
    type: 'select',
  },
  {
    group: 'Attendees',
    id: 'attendee[*].attendance.internalid',
    name: 'Attendees : Attendance (InternalId)',
    type: 'select',
    sublist: 'attendee',
  },
  {
    group: 'Attendees',
    id: 'attendee[*].attendance',
    name: 'Attendees : Attendance (Name)',
    type: 'select',
    sublist: 'attendee',
  },
  {
    group: 'Attendees',
    id: 'attendee[*].availability',
    name: 'Attendees : Availability',
    type: 'text',
    sublist: 'attendee',
  },
  {
    group: 'Attendees',
    id: 'attendee[*].celigo_createline',
    name: 'Attendees : Create Line',
    type: 'checkbox',
    sublist: 'attendee',
  },
  {
    group: 'Attendees',
    id: 'attendee[*].sendemail',
    name: 'Attendees : Email',
    type: 'checkbox',
    sublist: 'attendee',
  },
  {
    group: 'Body Field',
    id: 'celigo_groupLinesBy_attendee',
    name: 'Attendees : Group Lines By',
    type: 'text',
  },
  {
    group: 'Attendees',
    id: 'attendee[*].line',
    name: 'Attendees : Line ID',
    type: 'integer',
    sublist: 'attendee',
  },
  {
    group: 'Attendees',
    id: 'attendee[*].linenum',
    name: 'Attendees : Line Number',
    type: 'integer',
    sublist: 'attendee',
  },
  {
    group: 'Body Field',
    id: 'celigo_replaceAllLines_attendee',
    name: 'Attendees : Replace All Lines',
    type: 'checkbox',
    mandatory: true,
    hardCodedValue: 'T',
    hardCodedText: 'Yes',
  },
  {
    group: 'Attendees',
    id: 'attendee[*].response.internalid',
    name: 'Attendees : Response (InternalId)',
    type: 'select',
    sublist: 'attendee',
  },
  {
    group: 'Attendees',
    id: 'attendee[*].response',
    name: 'Attendees : Response (Name)',
    type: 'select',
    sublist: 'attendee',
  },
  {
    group: 'Attendees',
    id: 'attendee[*].attendee.internalid',
    name: 'Attendees : Send Invitation to (InternalId)',
    type: 'select',
    sublist: 'attendee',
  },
  {
    group: 'Attendees',
    id: 'attendee[*].attendee',
    name: 'Attendees : Send Invitation to (Name)',
    type: 'select',
    sublist: 'attendee',
  },
  {
    group: 'Files',
    id: 'mediaitem[*].mediaitem.internalid',
    name: 'Files : Attach File (InternalId)',
    type: 'select',
    sublist: 'mediaitem',
  },
  {
    group: 'Files',
    id: 'mediaitem[*].mediaitem',
    name: 'Files : Attach File (Name)',
    type: 'select',
    sublist: 'mediaitem',
  },
  {
    group: 'Files',
    id: 'mediaitem[*].celigo_createline',
    name: 'Files : Create Line',
    type: 'checkbox',
    sublist: 'mediaitem',
  },
  {
    group: 'Files',
    id: 'mediaitem[*].filetype',
    name: 'Files : File Type',
    type: 'text',
    sublist: 'mediaitem',
  },
  {
    group: 'Files',
    id: 'mediaitem[*].folder',
    name: 'Files : Folder',
    type: 'text',
    sublist: 'mediaitem',
  },
  {
    group: 'Body Field',
    id: 'celigo_groupLinesBy_mediaitem',
    name: 'Files : Group Lines By',
    type: 'text',
  },
  {
    group: 'Files',
    id: 'mediaitem[*].lastmodifieddate',
    name: 'Files : Last Modified',
    type: 'datetime',
    sublist: 'mediaitem',
  },
  {
    group: 'Files',
    id: 'mediaitem[*].line',
    name: 'Files : Line ID',
    type: 'integer',
    sublist: 'mediaitem',
  },
  {
    group: 'Files',
    id: 'mediaitem[*].linenum',
    name: 'Files : Line Number',
    type: 'integer',
    sublist: 'mediaitem',
  },
  {
    group: 'Body Field',
    id: 'celigo_replaceAllLines_mediaitem',
    name: 'Files : Replace All Lines',
    type: 'checkbox',
    mandatory: true,
    hardCodedValue: 'T',
    hardCodedText: 'Yes',
  },
  {
    group: 'Files',
    id: 'mediaitem[*].filesize',
    name: 'Files : Size (kB)',
    type: 'float',
    sublist: 'mediaitem',
  },
  {
    group: 'Resources',
    id: 'resource[*].availability',
    name: 'Resources : Availability',
    type: 'text',
    sublist: 'resource',
  },
  {
    group: 'Resources',
    id: 'resource[*].celigo_createline',
    name: 'Resources : Create Line',
    type: 'checkbox',
    sublist: 'resource',
  },
  {
    group: 'Body Field',
    id: 'celigo_groupLinesBy_resource',
    name: 'Resources : Group Lines By',
    type: 'text',
  },
  {
    group: 'Resources',
    id: 'resource[*].line',
    name: 'Resources : Line ID',
    type: 'integer',
    sublist: 'resource',
  },
  {
    group: 'Resources',
    id: 'resource[*].linenum',
    name: 'Resources : Line Number',
    type: 'integer',
    sublist: 'resource',
  },
  {
    group: 'Resources',
    id: 'resource[*].location',
    name: 'Resources : Location',
    type: 'text',
    sublist: 'resource',
  },
  {
    group: 'Body Field',
    id: 'celigo_replaceAllLines_resource',
    name: 'Resources : Replace All Lines',
    type: 'checkbox',
    mandatory: true,
    hardCodedValue: 'T',
    hardCodedText: 'Yes',
  },
  {
    group: 'Resources',
    id: 'resource[*].resource.internalid',
    name: 'Resources : Resource (InternalId)',
    type: 'select',
    sublist: 'resource',
  },
  {
    group: 'Resources',
    id: 'resource[*].resource',
    name: 'Resources : Resource (Name)',
    type: 'select',
    sublist: 'resource',
  },
  {
    group: 'Time Tracking',
    id: 'timeitem[*].isbillable',
    name: 'Time Tracking : Billable',
    type: 'checkbox',
    sublist: 'timeitem',
  },
  {
    group: 'Time Tracking',
    id: 'timeitem[*].class.internalid',
    name: 'Time Tracking : Class (InternalId)',
    type: 'select',
    sublist: 'timeitem',
  },
  {
    group: 'Time Tracking',
    id: 'timeitem[*].class',
    name: 'Time Tracking : Class (Name)',
    type: 'select',
    sublist: 'timeitem',
  },
  {
    group: 'Time Tracking',
    id: 'timeitem[*].celigo_createline',
    name: 'Time Tracking : Create Line',
    type: 'checkbox',
    sublist: 'timeitem',
  },
  {
    group: 'Time Tracking',
    id: 'timeitem[*].customer.internalid',
    name: 'Time Tracking : Customer:Job (InternalId)',
    type: 'select',
    sublist: 'timeitem',
  },
  {
    group: 'Time Tracking',
    id: 'timeitem[*].customer',
    name: 'Time Tracking : Customer:Job (Name)',
    type: 'select',
    sublist: 'timeitem',
  },
  {
    group: 'Time Tracking',
    id: 'timeitem[*].trandate',
    name: 'Time Tracking : Date',
    type: 'date',
    sublist: 'timeitem',
  },
  {
    group: 'Time Tracking',
    id: 'timeitem[*].department.internalid',
    name: 'Time Tracking : Department (InternalId)',
    type: 'select',
    sublist: 'timeitem',
  },
  {
    group: 'Time Tracking',
    id: 'timeitem[*].department',
    name: 'Time Tracking : Department (Name)',
    type: 'select',
    sublist: 'timeitem',
  },
  {
    group: 'Time Tracking',
    id: 'timeitem[*].hours',
    name: 'Time Tracking : Duration',
    type: 'timetrack',
    sublist: 'timeitem',
  },
  {
    group: 'Time Tracking',
    id: 'timeitem[*].employee.internalid',
    name: 'Time Tracking : Employee (InternalId)',
    type: 'select',
    sublist: 'timeitem',
  },
  {
    group: 'Time Tracking',
    id: 'timeitem[*].employee',
    name: 'Time Tracking : Employee (Name)',
    type: 'select',
    sublist: 'timeitem',
  },
  {
    group: 'Body Field',
    id: 'celigo_groupLinesBy_timeitem',
    name: 'Time Tracking : Group Lines By',
    type: 'text',
  },
  {
    group: 'Time Tracking',
    id: 'timeitem[*].line',
    name: 'Time Tracking : Line ID',
    type: 'integer',
    sublist: 'timeitem',
  },
  {
    group: 'Time Tracking',
    id: 'timeitem[*].linenum',
    name: 'Time Tracking : Line Number',
    type: 'integer',
    sublist: 'timeitem',
  },
  {
    group: 'Time Tracking',
    id: 'timeitem[*].location.internalid',
    name: 'Time Tracking : Location (InternalId)',
    type: 'select',
    sublist: 'timeitem',
  },
  {
    group: 'Time Tracking',
    id: 'timeitem[*].location',
    name: 'Time Tracking : Location (Name)',
    type: 'select',
    sublist: 'timeitem',
  },
  {
    group: 'Time Tracking',
    id: 'timeitem[*].memo',
    name: 'Time Tracking : Memo',
    type: 'textarea',
    sublist: 'timeitem',
  },
  {
    group: 'Body Field',
    id: 'celigo_replaceAllLines_timeitem',
    name: 'Time Tracking : Replace All Lines',
    type: 'checkbox',
    mandatory: true,
    hardCodedValue: 'T',
    hardCodedText: 'Yes',
  },
  {
    group: 'Time Tracking',
    id: 'timeitem[*].item.internalid',
    name: 'Time Tracking : Service Item (InternalId)',
    type: 'select',
    sublist: 'timeitem',
  },
  {
    group: 'Time Tracking',
    id: 'timeitem[*].item',
    name: 'Time Tracking : Service Item (Name)',
    type: 'select',
    sublist: 'timeitem',
  },
  {
    group: 'Time Tracking',
    id: 'timeitem[*].timetype.internalid',
    name: 'Time Tracking : Type (InternalId)',
    type: 'select',
    sublist: 'timeitem',
  },
  {
    group: 'Time Tracking',
    id: 'timeitem[*].timetype',
    name: 'Time Tracking : Type (Name)',
    type: 'select',
    sublist: 'timeitem',
  },
  {
    group: 'User Notes',
    id: 'usernotes[*].celigo_createline',
    name: 'User Notes : Create Line',
    type: 'checkbox',
    sublist: 'usernotes',
  },
  {
    group: 'User Notes',
    id: 'usernotes[*].notedate',
    name: 'User Notes : Date',
    type: 'date',
    sublist: 'usernotes',
  },
  {
    group: 'User Notes',
    id: 'usernotes[*].direction.internalid',
    name: 'User Notes : Direction (InternalId)',
    type: 'select',
    sublist: 'usernotes',
  },
  {
    group: 'User Notes',
    id: 'usernotes[*].direction',
    name: 'User Notes : Direction (Name)',
    type: 'select',
    sublist: 'usernotes',
  },
  {
    group: 'User Notes',
    id: 'usernotes[*].externalid',
    name: 'User Notes : ExternalId',
    type: 'text',
    sublist: 'usernotes',
  },
  {
    group: 'Body Field',
    id: 'celigo_groupLinesBy_usernotes',
    name: 'User Notes : Group Lines By',
    type: 'text',
  },
  {
    group: 'User Notes',
    id: 'usernotes[*].internalid',
    name: 'User Notes : Internal ID',
    type: 'text',
    sublist: 'usernotes',
  },
  {
    group: 'User Notes',
    id: 'usernotes[*].line',
    name: 'User Notes : Line ID',
    type: 'integer',
    sublist: 'usernotes',
  },
  {
    group: 'User Notes',
    id: 'usernotes[*].linenum',
    name: 'User Notes : Line Number',
    type: 'integer',
    sublist: 'usernotes',
  },
  {
    group: 'User Notes',
    id: 'usernotes[*].note',
    name: 'User Notes : Memo',
    type: 'textarea',
    sublist: 'usernotes',
  },
  {
    group: 'Body Field',
    id: 'celigo_replaceAllLines_usernotes',
    name: 'User Notes : Replace All Lines',
    type: 'checkbox',
    mandatory: true,
    hardCodedValue: 'T',
    hardCodedText: 'Yes',
  },
  {
    group: 'User Notes',
    id: 'usernotes[*].time',
    name: 'User Notes : Time',
    type: 'timeofday',
    sublist: 'usernotes',
  },
  {
    group: 'User Notes',
    id: 'usernotes[*].title',
    name: 'User Notes : Title',
    type: 'text',
    sublist: 'usernotes',
  },
  {
    group: 'User Notes',
    id: 'usernotes[*].notetype.internalid',
    name: 'User Notes : Type (InternalId)',
    type: 'select',
    sublist: 'usernotes',
  },
  {
    group: 'User Notes',
    id: 'usernotes[*].notetype',
    name: 'User Notes : Type (Name)',
    type: 'select',
    sublist: 'usernotes',
  },
];
