// This is a sample file and is used for development purpose
// TODO (Aditya): Delete the file after use

export default [
  { id: 'Description', name: 'Account Description', type: 'textarea' },
  { id: 'Fax', name: 'Account Fax', type: 'phone' },
  { id: 'Id', name: 'Account ID', type: 'id' },
  { id: 'Name', name: 'Account Name', type: 'string' },
  { id: 'AccountNumber', name: 'Account Number', type: 'string' },
  { id: 'Phone', name: 'Account Phone', type: 'phone' },
  { id: 'Rating', name: 'Account Rating', type: 'picklist' },
  { id: 'Site', name: 'Account Site', type: 'string' },
  { id: 'AccountSource', name: 'Account Source', type: 'picklist' },
  { id: 'Type', name: 'Account Type', type: 'picklist' },
  { id: 'Active__c', name: 'Active', type: 'picklist' },
  { id: 'AnnualRevenue', name: 'Annual Revenue', type: 'currency' },
  { id: 'BillingAddress', name: 'Billing Address', type: 'address' },
  { id: 'BillingCity', name: 'Billing City', type: 'string' },
  { id: 'BillingCountry', name: 'Billing Country', type: 'string' },
  {
    id: 'BillingGeocodeAccuracy',
    name: 'Billing Geocode Accuracy',
    type: 'picklist',
  },
  { id: 'BillingLatitude', name: 'Billing Latitude', type: 'double' },
  { id: 'BillingLongitude', name: 'Billing Longitude', type: 'double' },
  { id: 'BillingState', name: 'Billing State/Province', type: 'string' },
  { id: 'BillingStreet', name: 'Billing Street', type: 'textarea' },
  { id: 'BillingPostalCode', name: 'Billing Zip/Postal Code', type: 'string' },
  { id: 'CleanStatus', name: 'Clean Status', type: 'picklist' },
  { id: 'CreatedById', name: 'Created By ID', type: 'reference' },
  { id: 'CreatedDate', name: 'Created Date', type: 'datetime' },
  { id: 'CustomerPriority__c', name: 'Customer Priority', type: 'picklist' },
  { id: 'DandbCompanyId', name: 'D&B Company ID', type: 'reference' },
  { id: 'DunsNumber', name: 'D-U-N-S Number', type: 'string' },
  { id: 'Jigsaw', name: 'Data.com Key', type: 'string' },
  { id: 'IsDeleted', name: 'Deleted', type: 'boolean' },
  { id: 'NumberOfEmployees', name: 'Employees', type: 'int' },
  { id: 'Industry', name: 'Industry', type: 'picklist' },
  { id: 'JigsawCompanyId', name: 'Jigsaw Company ID', type: 'string' },
  { id: 'LastActivityDate', name: 'Last Activity', type: 'date' },
  { id: 'LastModifiedById', name: 'Last Modified By ID', type: 'reference' },
  { id: 'LastModifiedDate', name: 'Last Modified Date', type: 'datetime' },
  { id: 'LastReferencedDate', name: 'Last Referenced Date', type: 'datetime' },
  { id: 'LastViewedDate', name: 'Last Viewed Date', type: 'datetime' },
  { id: 'MasterRecordId', name: 'Master Record ID', type: 'reference' },
  { id: 'NaicsCode', name: 'NAICS Code', type: 'string' },
  { id: 'NaicsDesc', name: 'NAICS Description', type: 'string' },
  { id: 'NumberofLocations__c', name: 'Number of Locations', type: 'double' },
  { id: 'OwnerId', name: 'Owner ID', type: 'reference' },
  { id: 'Ownership', name: 'Ownership', type: 'picklist' },
  { id: 'ParentId', name: 'Parent Account ID', type: 'reference' },
  { id: 'PhotoUrl', name: 'Photo URL', type: 'url' },
  { id: 'Sic', name: 'SIC Code', type: 'string' },
  { id: 'SicDesc', name: 'SIC Description', type: 'string' },
  { id: 'SLA__c', name: 'SLA', type: 'picklist' },
  { id: 'SLAExpirationDate__c', name: 'SLA Expiration Date', type: 'date' },
  { id: 'SLASerialNumber__c', name: 'SLA Serial Number', type: 'string' },
  { id: 'ShippingAddress', name: 'Shipping Address', type: 'address' },
  { id: 'ShippingCity', name: 'Shipping City', type: 'string' },
  { id: 'ShippingCountry', name: 'Shipping Country', type: 'string' },
  {
    id: 'ShippingGeocodeAccuracy',
    name: 'Shipping Geocode Accuracy',
    type: 'picklist',
  },
  { id: 'ShippingLatitude', name: 'Shipping Latitude', type: 'double' },
  { id: 'ShippingLongitude', name: 'Shipping Longitude', type: 'double' },
  { id: 'ShippingState', name: 'Shipping State/Province', type: 'string' },
  { id: 'ShippingStreet', name: 'Shipping Street', type: 'textarea' },
  {
    id: 'ShippingPostalCode',
    name: 'Shipping Zip/Postal Code',
    type: 'string',
  },
  { id: 'SystemModstamp', name: 'System Modstamp', type: 'datetime' },
  { id: 'TickerSymbol', name: 'Ticker Symbol', type: 'string' },
  { id: 'Tradestyle', name: 'Tradestyle', type: 'string' },
  { id: 'UpsellOpportunity__c', name: 'Upsell Opportunity', type: 'picklist' },
  { id: 'Website', name: 'Website', type: 'url' },
  { id: 'YearStarted', name: 'Year Started', type: 'string' },
];
