export default {
  // #region common
  exportName: {
    type: 'text',
    helpKey: 'export.name',
    name: '/name',
    id: 'exportName',
    label: 'Name',
    defaultValue: '{{name}}',
  },
  exportDescription: {
    type: 'text',
    helpKey: 'export.description',
    name: '/description',
    id: 'exportDescription',
    label: 'Description',
    defaultValue: '{{description}}',
  },
  exportAsynchronous: {
    type: 'checkbox',
    helpKey: 'export.asynchronous',
    name: '/asynchronous',
    id: 'exportAsynchronous',
    label: 'Asynchronous',
    defaultValue: false,
  },
  exportApiIdentifier: {
    type: 'text',
    helpKey: 'export.apiIdentifier',
    name: '/apiIdentifier',
    id: 'exportApiIdentifier',
    label: 'ApiIdentifier',
    defaultValue: '{{apiIdentifier}}',
  },
  exportType: {
    type: 'radiogroup',
    helpKey: 'export.type',
    name: '/type',
    id: 'exportType',
    label: 'Type',
    defaultValue: '{{type}}',
    options: [
      {
        items: [
          { label: 'Webhook', value: 'webhook' },
          { label: 'Distributed', value: 'distributed' },
          { label: 'Test', value: 'test' },
          { label: 'Delta', value: 'delta' },
          { label: 'Once', value: 'once' },
          { label: 'Tranlinedelta', value: 'tranlinedelta' },
          { label: 'Simple', value: 'simple' },
          { label: 'Blob', value: 'blob' },
        ],
      },
    ],
  },
  exportPageSize: {
    type: 'text',
    helpKey: 'export.pageSize',
    name: '/pageSize',
    id: 'exportPageSize',
    label: 'PageSize',
    defaultValue: '{{pageSize}}',
    validWhen: [
      {
        matchesRegEx: { pattern: '^[\\d]+$', message: 'Only numbers allowed' },
      },
    ],
  },
  exportDataURITemplate: {
    type: 'text',
    helpKey: 'export.dataURITemplate',
    name: '/dataURITemplate',
    id: 'exportDataURITemplate',
    label: 'DataURITemplate',
    defaultValue: '{{dataURITemplate}}',
  },
  exportOneToMany: {
    type: 'checkbox',
    helpKey: 'export.oneToMany',
    name: '/oneToMany',
    id: 'exportOneToMany',
    label: 'OneToMany',
    defaultValue: false,
  },
  exportPathToMany: {
    type: 'text',
    helpKey: 'export.pathToMany',
    name: '/pathToMany',
    id: 'exportPathToMany',
    label: 'PathToMany',
    defaultValue: '{{pathToMany}}',
  },
  exportSampleData: {
    type: 'text',
    helpKey: 'export.sampleData',
    name: '/sampleData',
    id: 'exportSampleData',
    label: 'SampleData',
    defaultValue: '{{sampleData}}',
  },
  exportOriginSampleData: {
    type: 'text',
    helpKey: 'export.originSampleData',
    name: '/originSampleData',
    id: 'exportOriginSampleData',
    label: 'OriginSampleData',
    defaultValue: '{{originSampleData}}',
  },
  exportAssistant: {
    type: 'radiogroup',
    helpKey: 'export.assistant',
    name: '/assistant',
    id: 'exportAssistant',
    label: 'Assistant',
    defaultValue: '{{assistant}}',
    options: [
      {
        items: [
          { label: '3dcart', value: '3dcart' },
          { label: 'Accelo', value: 'accelo' },
          { label: 'Adp', value: 'adp' },
          { label: 'Amazonaws', value: 'amazonaws' },
          { label: 'Amazonmws', value: 'amazonmws' },
          { label: 'Anaplan', value: 'anaplan' },
          { label: 'Ariba', value: 'ariba' },
          { label: 'Asana', value: 'asana' },
          { label: 'Atera', value: 'atera' },
          { label: 'Authorize.net', value: 'authorize.net' },
          { label: 'Avalara', value: 'avalara' },
          { label: 'Banking', value: 'banking' },
          { label: 'Bigcommerce', value: 'bigcommerce' },
          { label: 'Bill.com', value: 'bill.com' },
          { label: 'Box', value: 'box' },
          { label: 'Braintree', value: 'braintree' },
          { label: 'Campaignmonitor', value: 'campaignmonitor' },
          { label: 'Certify', value: 'certify' },
          { label: 'Chargebee', value: 'chargebee' },
          { label: 'Chargify', value: 'chargify' },
          { label: 'Clover', value: 'clover' },
          { label: 'Dcl', value: 'dcl' },
          { label: 'Desk', value: 'desk' },
          { label: 'Dnb', value: 'dnb' },
          { label: 'Docusign', value: 'docusign' },
          { label: 'Doubleclick', value: 'doubleclick' },
          { label: 'Dropbox', value: 'dropbox' },
          { label: 'Ebay', value: 'ebay' },
          { label: 'Ebay-xml', value: 'ebay-xml' },
          { label: 'Eloquent', value: 'eloquent' },
          { label: 'Etsy', value: 'etsy' },
          { label: 'Eventbrite', value: 'eventbrite' },
          { label: 'Exacterp', value: 'exacterp' },
          { label: 'Expensify', value: 'expensify' },
          { label: 'Facebookads', value: 'facebookads' },
          { label: 'Fieldaware', value: 'fieldaware' },
          { label: 'Freshbooks', value: 'freshbooks' },
          { label: 'Freshdesk', value: 'freshdesk' },
          { label: 'Ftp', value: 'ftp' },
          { label: 'Github', value: 'github' },
          { label: 'Gooddata', value: 'gooddata' },
          { label: 'Google', value: 'google' },
          { label: 'Googleanalytics', value: 'googleanalytics' },
          { label: 'Googlecontacts', value: 'googlecontacts' },
          { label: 'Googledrive', value: 'googledrive' },
          { label: 'Googlemail', value: 'googlemail' },
          { label: 'Googlesheets', value: 'googlesheets' },
          { label: 'Googleshopping', value: 'googleshopping' },
          { label: 'Harvest', value: 'harvest' },
          { label: 'Hoovers', value: 'hoovers' },
          { label: 'Hubspot', value: 'hubspot' },
          { label: 'Hybris', value: 'hybris' },
          { label: 'Insightly', value: 'insightly' },
          { label: 'Integratorio', value: 'integratorio' },
          { label: 'Jet', value: 'jet' },
          { label: 'Jira', value: 'jira' },
          { label: 'Jobvite', value: 'jobvite' },
          { label: 'Lightspeed', value: 'lightspeed' },
          { label: 'Linkedin', value: 'linkedin' },
          { label: 'Liquidplanner', value: 'liquidplanner' },
          { label: 'Magento', value: 'magento' },
          { label: 'Mailchimp', value: 'mailchimp' },
          { label: 'Mediaocean', value: 'mediaocean' },
          { label: 'Namely', value: 'namely' },
          { label: 'Netsuite', value: 'netsuite' },
          { label: 'Newegg', value: 'newegg' },
          { label: 'Newrelic', value: 'newrelic' },
          { label: 'Okta', value: 'okta' },
          { label: 'Openair', value: 'openair' },
          { label: 'Osn', value: 'osn' },
          { label: 'Other', value: 'other' },
          { label: 'Paychex', value: 'paychex' },
          { label: 'Paylocity', value: 'paylocity' },
          { label: 'Paypal', value: 'paypal' },
          { label: 'Pulseway', value: 'pulseway' },
          { label: 'Quickbooks', value: 'quickbooks' },
          { label: 'Recurly', value: 'recurly' },
          { label: 'Replicon', value: 'replicon' },
          { label: 'S3', value: 's3' },
          { label: 'Sageone', value: 'sageone' },
          { label: 'Salesforce', value: 'salesforce' },
          { label: 'Servicenow', value: 'servicenow' },
          { label: 'Shiphawk', value: 'shiphawk' },
          { label: 'Shipstation', value: 'shipstation' },
          { label: 'Shipwire', value: 'shipwire' },
          { label: 'Shopify', value: 'shopify' },
          { label: 'Skubana', value: 'skubana' },
          { label: 'Slack', value: 'slack' },
          { label: 'Smartsheet', value: 'smartsheet' },
          { label: 'Snapfulfil', value: 'snapfulfil' },
          { label: 'Splunk', value: 'splunk' },
          { label: 'Spreecommerce', value: 'spreecommerce' },
          { label: 'Squareup', value: 'squareup' },
          { label: 'Steelbrick', value: 'steelbrick' },
          { label: 'Stripe', value: 'stripe' },
          { label: 'Surveymonkey', value: 'surveymonkey' },
          { label: 'Svb', value: 'svb' },
          { label: 'Tableau', value: 'tableau' },
          { label: 'Tesco', value: 'tesco' },
          { label: 'Travis', value: 'travis' },
          { label: 'Tsheets', value: 'tsheets' },
          { label: 'Twilio', value: 'twilio' },
          { label: 'Walmart', value: 'walmart' },
          { label: 'Wiser', value: 'wiser' },
          { label: 'Woocommerce', value: 'woocommerce' },
          { label: 'Wrike', value: 'wrike' },
          { label: 'Xcart', value: 'xcart' },
          { label: 'Yahoo', value: 'yahoo' },
          { label: 'Yammer', value: 'yammer' },
          { label: 'Zendesk', value: 'zendesk' },
          { label: 'Zoho', value: 'zoho' },
          { label: 'Zuora', value: 'zuora' },
          { label: 'Coupa', value: 'coupa' },
          { label: 'Taxjar', value: 'taxjar' },
          { label: 'Quip', value: 'quip' },
          { label: 'Allbound', value: 'allbound' },
          { label: 'Zohocrm', value: 'zohocrm' },
          { label: 'Zohodesk', value: 'zohodesk' },
          { label: 'Microsoftoffice365', value: 'microsoftoffice365' },
          { label: 'Microsoftdynamics365', value: 'microsoftdynamics365' },
          { label: 'Pitneybowes', value: 'pitneybowes' },
          { label: 'Mysql', value: 'mysql' },
          { label: 'Postgresql', value: 'postgresql' },
          { label: 'Mssql', value: 'mssql' },
          { label: 'Greenhouse', value: 'greenhouse' },
          { label: 'Shippo', value: 'shippo' },
          { label: 'Gusto', value: 'gusto' },
          { label: 'Easypost', value: 'easypost' },
          { label: 'Segment', value: 'segment' },
          { label: 'Zohobooks', value: 'zohobooks' },
          {
            label: 'Microsoftbusinesscentral',
            value: 'microsoftbusinesscentral',
          },
          {
            label: 'Microsoftoutlookcalendar',
            value: 'microsoftoutlookcalendar',
          },
          { label: 'Microsoftoutlookmail', value: 'microsoftoutlookmail' },
          {
            label: 'Microsoftoutlookcontacts',
            value: 'microsoftoutlookcontacts',
          },
          { label: 'Microsoftonenote', value: 'microsoftonenote' },
          { label: 'Wish', value: 'wish' },
          { label: 'Pdffiller', value: 'pdffiller' },
          { label: 'Signnow', value: 'signnow' },
          { label: 'Acton', value: 'acton' },
          { label: 'Acumatica', value: 'acumatica' },
          { label: 'Mongodb', value: 'mongodb' },
          { label: 'Zohomail', value: 'zohomail' },
          { label: 'Zoom', value: 'zoom' },
          { label: 'Myobessentials', value: 'myobessentials' },
          { label: 'Nimble', value: 'nimble' },
          { label: 'Bronto', value: 'bronto' },
          { label: 'Strata', value: 'strata' },
          { label: 'Returnly', value: 'returnly' },
          { label: 'Activecampaign', value: 'activecampaign' },
          { label: 'Klaviyo', value: 'klaviyo' },
          { label: 'Postmark', value: 'postmark' },
          { label: 'Powerbi', value: 'powerbi' },
          { label: 'Procurify', value: 'procurify' },
          { label: 'Mailgun', value: 'mailgun' },
          { label: 'Zimbra', value: 'zimbra' },
          { label: 'Merchantesolutions', value: 'merchantesolutions' },
          { label: 'Aptrinsic', value: 'aptrinsic' },
          { label: 'Cardknox', value: 'cardknox' },
          { label: 'Skuvault', value: 'skuvault' },
          { label: 'Nextag', value: 'nextag' },
          { label: 'Concur', value: 'concur' },
          { label: 'Oandav20fxtrade', value: 'oandav20fxtrade' },
          { label: 'Oandaexchangerates', value: 'oandaexchangerates' },
          { label: 'Spreecommerce', value: 'spreecommerce' },
          { label: 'Tophatter', value: 'tophatter' },
          { label: 'Concurv4', value: 'concurv4' },
          { label: 'Sugarcrm', value: 'sugarcrm' },
          { label: 'Marketo', value: 'marketo' },
          { label: 'Grms', value: 'grms' },
          { label: 'Retailops', value: 'retailops' },
          { label: 'Sharepoint', value: 'sharepoint' },
          { label: 'Parseur', value: 'parseur' },
          { label: 'Authorize.net', value: 'authorize.net' },
          { label: 'Firstdata', value: 'firstdata' },
          { label: 'Propack', value: 'propack' },
          { label: 'Outreach', value: 'outreach' },
          { label: 'Ramplogistics', value: 'ramplogistics' },
          { label: 'Constantcontactv3', value: 'constantcontactv3' },
          { label: 'Constantcontactv2', value: 'constantcontactv2' },
          { label: 'Concurall', value: 'concurall' },
          { label: 'Dunandbradstreet', value: 'dunandbradstreet' },
          { label: 'Trinet', value: 'trinet' },
          { label: 'Pacejet', value: 'pacejet' },
          { label: 'Solidcommerce', value: 'solidcommerce' },
          { label: 'Intercom', value: 'intercom' },
          { label: 'Bamboohr', value: 'bamboohr' },
        ],
      },
    ],
  },
  exportAssistantMetadata: {
    type: 'text',
    helpKey: 'export.assistantMetadata',
    name: '/assistantMetadata',
    id: 'exportAssistantMetadata',
    label: 'AssistantMetadata',
    defaultValue: '{{assistantMetadata}}',
  },
  exportIsLookup: {
    type: 'checkbox',
    helpKey: 'export.isLookup',
    name: '/isLookup',
    id: 'exportIsLookup',
    label: 'IsLookup',
    defaultValue: false,
  },
  exportUseTechAdaptorForm: {
    type: 'checkbox',
    helpKey: 'export.useTechAdaptorForm',
    name: '/useTechAdaptorForm',
    id: 'exportUseTechAdaptorForm',
    label: 'UseTechAdaptorForm',
    defaultValue: false,
  },
  exportAdaptorType: {
    type: 'text',
    helpKey: 'export.adaptorType',
    name: '/adaptorType',
    id: 'exportAdaptorType',
    label: 'AdaptorType',
    defaultValue: '{{adaptorType}}',
  },
  // #endregion common
  // #region inputFilter
  exportInputFilterType: {
    type: 'radiogroup',
    helpKey: 'export.inputFilter.type',
    name: '/inputFilter/type',
    id: 'exportInputFilterType',
    label: 'InputFilter type',
    defaultValue: '{{inputFilter.type}}',
    options: [
      {
        items: [
          { label: 'Expression', value: 'expression' },
          { label: 'Script', value: 'script' },
        ],
      },
    ],
  },
  exportInputFilterExpressionVersion: {
    type: 'radiogroup',
    helpKey: 'export.inputFilter.expression.version',
    name: '/inputFilter/expression/version',
    id: 'exportInputFilterExpressionVersion',
    label: 'InputFilter expression version',
    defaultValue: '{{inputFilter.expression.version}}',
    options: [{ items: [{ label: '1', value: '1' }] }],
  },
  exportInputFilterExpressionRules: {
    type: 'text',
    helpKey: 'export.inputFilter.expression.rules',
    name: '/inputFilter/expression/rules',
    id: 'exportInputFilterExpressionRules',
    label: 'InputFilter expression rules',
    defaultValue: '{{inputFilter.expression.rules}}',
  },
  exportInputFilterScript_scriptId: {
    type: 'text',
    helpKey: 'export.inputFilter.script._scriptId',
    name: '/inputFilter/script/_scriptId',
    id: 'exportInputFilterScript_scriptId',
    label: 'InputFilter script _scriptId',
    defaultValue: '{{inputFilter.script._scriptId}}',
  },
  exportInputFilterScriptFunction: {
    type: 'text',
    helpKey: 'export.inputFilter.script.function',
    name: '/inputFilter/script/function',
    id: 'exportInputFilterScriptFunction',
    label: 'InputFilter script function',
    defaultValue: '{{inputFilter.script.function}}',
  },
  // #endregion inputFilter
  // #region test
  exportTestLimit: {
    type: 'text',
    helpKey: 'export.test.limit',
    name: '/test/limit',
    id: 'exportTestLimit',
    label: 'Test limit',
    defaultValue: '{{test.limit}}',
    validWhen: [
      {
        matchesRegEx: { pattern: '^[\\d]+$', message: 'Only numbers allowed' },
      },
    ],
  },
  // #endregion test
  // #region delta
  exportDeltaDateField: {
    type: 'text',
    helpKey: 'export.delta.dateField',
    name: '/delta/dateField',
    id: 'exportDeltaDateField',
    label: 'Delta dateField',
    defaultValue: '{{delta.dateField}}',
  },
  exportDeltaDateFormat: {
    type: 'text',
    helpKey: 'export.delta.dateFormat',
    name: '/delta/dateFormat',
    id: 'exportDeltaDateFormat',
    label: 'Delta dateFormat',
    defaultValue: '{{delta.dateFormat}}',
  },
  exportDeltaStartDate: {
    type: 'text',
    helpKey: 'export.delta.startDate',
    name: '/delta/startDate',
    id: 'exportDeltaStartDate',
    label: 'Delta startDate',
    defaultValue: '{{delta.startDate}}',
  },
  exportDeltaLagOffset: {
    type: 'text',
    helpKey: 'export.delta.lagOffset',
    name: '/delta/lagOffset',
    id: 'exportDeltaLagOffset',
    label: 'Delta lagOffset',
    defaultValue: '{{delta.lagOffset}}',
    validWhen: [
      {
        matchesRegEx: { pattern: '^[\\d]+$', message: 'Only numbers allowed' },
      },
    ],
  },
  exportDeltaEndDateField: {
    type: 'text',
    helpKey: 'export.delta.endDateField',
    name: '/delta/endDateField',
    id: 'exportDeltaEndDateField',
    label: 'Delta endDateField',
    defaultValue: '{{delta.endDateField}}',
  },
  // #endregion delta
  // #region once
  exportOnceBooleanField: {
    type: 'text',
    helpKey: 'export.once.booleanField',
    name: '/once/booleanField',
    id: 'exportOnceBooleanField',
    label: 'Once booleanField',
    defaultValue: '{{once.booleanField}}',
  },
  // #endregion once
  // #region valueDelta
  exportValueDeltaExportedField: {
    type: 'text',
    helpKey: 'export.valueDelta.exportedField',
    name: '/valueDelta/exportedField',
    id: 'exportValueDeltaExportedField',
    label: 'ValueDelta exportedField',
    defaultValue: '{{valueDelta.exportedField}}',
  },
  exportValueDeltaPendingField: {
    type: 'text',
    helpKey: 'export.valueDelta.pendingField',
    name: '/valueDelta/pendingField',
    id: 'exportValueDeltaPendingField',
    label: 'ValueDelta pendingField',
    defaultValue: '{{valueDelta.pendingField}}',
  },
  // #endregion valueDelta
  // #region webhook
  exportWebhookProvider: {
    type: 'radiogroup',
    helpKey: 'export.webhook.provider',
    name: '/webhook/provider',
    id: 'exportWebhookProvider',
    label: 'Webhook provider',
    defaultValue: '{{webhook.provider}}',
    options: [
      {
        items: [
          { label: 'Github', value: 'github' },
          { label: 'Shopify', value: 'shopify' },
          { label: 'Travis', value: 'travis' },
          { label: 'Travis-org', value: 'travis-org' },
          { label: 'Slack', value: 'slack' },
          { label: 'Dropbox', value: 'dropbox' },
          { label: 'Helpscout', value: 'helpscout' },
          { label: 'Errorception', value: 'errorception' },
          { label: 'Box', value: 'box' },
          { label: 'Stripe', value: 'stripe' },
          { label: 'Aha', value: 'aha' },
          { label: 'Jira', value: 'jira' },
          { label: 'Pagerduty', value: 'pagerduty' },
          { label: 'Postmark', value: 'postmark' },
          { label: 'Mailchimp', value: 'mailchimp' },
          { label: 'Intercom', value: 'intercom' },
          { label: 'Activecampaign', value: 'activecampaign' },
          { label: 'Segment', value: 'segment' },
          { label: 'Recurly', value: 'recurly' },
          { label: 'Shipwire', value: 'shipwire' },
          { label: 'Surveymonkey', value: 'surveymonkey' },
          { label: 'Parseur', value: 'parseur' },
          { label: 'Mailparser-io', value: 'mailparser-io' },
          { label: 'Integrator-extension', value: 'integrator-extension' },
          { label: 'Custom', value: 'custom' },
        ],
      },
    ],
  },
  exportWebhookVerify: {
    type: 'radiogroup',
    helpKey: 'export.webhook.verify',
    name: '/webhook/verify',
    id: 'exportWebhookVerify',
    label: 'Webhook verify',
    defaultValue: '{{webhook.verify}}',
    options: [
      {
        items: [
          { label: 'Token', value: 'token' },
          { label: 'Hmac', value: 'hmac' },
          { label: 'Basic', value: 'basic' },
          { label: 'Publickey', value: 'publickey' },
          { label: 'Secret_url', value: 'secret_url' },
        ],
      },
    ],
  },
  exportWebhookToken: {
    type: 'text',
    helpKey: 'export.webhook.token',
    name: '/webhook/token',
    id: 'exportWebhookToken',
    label: 'Webhook token',
    defaultValue: '{{webhook.token}}',
  },
  exportWebhookPath: {
    type: 'text',
    helpKey: 'export.webhook.path',
    name: '/webhook/path',
    id: 'exportWebhookPath',
    label: 'Webhook path',
    defaultValue: '{{webhook.path}}',
  },
  exportWebhookAlgorithm: {
    type: 'radiogroup',
    helpKey: 'export.webhook.algorithm',
    name: '/webhook/algorithm',
    id: 'exportWebhookAlgorithm',
    label: 'Webhook algorithm',
    defaultValue: '{{webhook.algorithm}}',
    options: [
      {
        items: [
          { label: 'Sha1', value: 'sha1' },
          { label: 'Sha256', value: 'sha256' },
        ],
      },
    ],
  },
  exportWebhookEncoding: {
    type: 'radiogroup',
    helpKey: 'export.webhook.encoding',
    name: '/webhook/encoding',
    id: 'exportWebhookEncoding',
    label: 'Webhook encoding',
    defaultValue: '{{webhook.encoding}}',
    options: [
      {
        items: [
          { label: 'Hex', value: 'hex' },
          { label: 'Base64', value: 'base64' },
        ],
      },
    ],
  },
  exportWebhookKey: {
    type: 'text',
    helpKey: 'export.webhook.key',
    name: '/webhook/key',
    id: 'exportWebhookKey',
    label: 'Webhook key',
    defaultValue: '{{webhook.key}}',
  },
  exportWebhookHeader: {
    type: 'text',
    helpKey: 'export.webhook.header',
    name: '/webhook/header',
    id: 'exportWebhookHeader',
    label: 'Webhook header',
    defaultValue: '{{webhook.header}}',
  },
  exportWebhookUsername: {
    type: 'text',
    helpKey: 'export.webhook.username',
    name: '/webhook/username',
    id: 'exportWebhookUsername',
    label: 'Webhook username',
    defaultValue: '{{webhook.username}}',
  },
  exportWebhookPassword: {
    type: 'text',
    helpKey: 'export.webhook.password',
    name: '/webhook/password',
    id: 'exportWebhookPassword',
    label: 'Webhook password',
    defaultValue: '{{webhook.password}}',
  },
  // #endregion webhook
  // #region distributed
  exportDistributedBearerToken: {
    type: 'text',
    helpKey: 'export.distributed.bearerToken',
    name: '/distributed/bearerToken',
    id: 'exportDistributedBearerToken',
    label: 'Distributed bearerToken',
    defaultValue: '{{distributed.bearerToken}}',
  },
  // #endregion distributed
  // #region hooks
  exportHooksPreSavePageFunction: {
    type: 'text',
    helpKey: 'export.hooks.preSavePage.function',
    name: '/hooks/preSavePage/function',
    id: 'exportHooksPreSavePageFunction',
    label: 'Hooks preSavePage function',
    defaultValue: '{{hooks.preSavePage.function}}',
  },
  exportHooksPreSavePage_scriptId: {
    type: 'text',
    helpKey: 'export.hooks.preSavePage._scriptId',
    name: '/hooks/preSavePage/_scriptId',
    id: 'exportHooksPreSavePage_scriptId',
    label: 'Hooks preSavePage _scriptId',
    defaultValue: '{{hooks.preSavePage._scriptId}}',
  },
  exportHooksPreSavePage_stackId: {
    type: 'text',
    helpKey: 'export.hooks.preSavePage._stackId',
    name: '/hooks/preSavePage/_stackId',
    id: 'exportHooksPreSavePage_stackId',
    label: 'Hooks preSavePage _stackId',
    defaultValue: '{{hooks.preSavePage._stackId}}',
  },
  exportHooksPreSavePageConfiguration: {
    type: 'text',
    helpKey: 'export.hooks.preSavePage.configuration',
    name: '/hooks/preSavePage/configuration',
    id: 'exportHooksPreSavePageConfiguration',
    label: 'Hooks preSavePage configuration',
    defaultValue: '{{hooks.preSavePage.configuration}}',
  },
  // #endregion hooks
  // #region transform
  exportTransformType: {
    type: 'radiogroup',
    helpKey: 'export.transform.type',
    name: '/transform/type',
    id: 'exportTransformType',
    label: 'Transform type',
    defaultValue: '{{transform.type}}',
    options: [
      {
        items: [
          { label: 'Expression', value: 'expression' },
          { label: 'Script', value: 'script' },
        ],
      },
    ],
  },
  exportTransformExpressionVersion: {
    type: 'radiogroup',
    helpKey: 'export.transform.expression.version',
    name: '/transform/expression/version',
    id: 'exportTransformExpressionVersion',
    label: 'Transform expression version',
    defaultValue: '{{transform.expression.version}}',
    options: [{ items: [{ label: '1', value: '1' }] }],
  },
  exportTransformExpressionRules: {
    type: 'text',
    helpKey: 'export.transform.expression.rules',
    name: '/transform/expression/rules',
    id: 'exportTransformExpressionRules',
    label: 'Transform expression rules',
    defaultValue: '{{transform.expression.rules}}',
  },
  exportTransformScript_scriptId: {
    type: 'text',
    helpKey: 'export.transform.script._scriptId',
    name: '/transform/script/_scriptId',
    id: 'exportTransformScript_scriptId',
    label: 'Transform script _scriptId',
    defaultValue: '{{transform.script._scriptId}}',
  },
  exportTransformScriptFunction: {
    type: 'text',
    helpKey: 'export.transform.script.function',
    name: '/transform/script/function',
    id: 'exportTransformScriptFunction',
    label: 'Transform script function',
    defaultValue: '{{transform.script.function}}',
  },
  // #endregion transform
  // #region parsers[*]
  'exportParsers[*]Version': {
    type: 'text',
    helpKey: 'export.parsers[*].version',
    name: '/parsers[*]/version',
    id: 'exportParsers[*]Version',
    label: 'Parsers[*] version',
    defaultValue: '{{parsers[*].version}}',
  },
  'exportParsers[*]Type': {
    type: 'text',
    helpKey: 'export.parsers[*].type',
    name: '/parsers[*]/type',
    id: 'exportParsers[*]Type',
    label: 'Parsers[*] type',
    defaultValue: '{{parsers[*].type}}',
  },
  'exportParsers[*]Rules': {
    type: 'text',
    helpKey: 'export.parsers[*].rules',
    name: '/parsers[*]/rules',
    id: 'exportParsers[*]Rules',
    label: 'Parsers[*] rules',
    defaultValue: '{{parsers[*].rules}}',
  },
  // #endregion parsers[*]
  // #region filter
  exportFilterType: {
    type: 'radiogroup',
    helpKey: 'export.filter.type',
    name: '/filter/type',
    id: 'exportFilterType',
    label: 'Filter type',
    defaultValue: '{{filter.type}}',
    options: [
      {
        items: [
          { label: 'Expression', value: 'expression' },
          { label: 'Script', value: 'script' },
        ],
      },
    ],
  },
  exportFilterExpressionVersion: {
    type: 'radiogroup',
    helpKey: 'export.filter.expression.version',
    name: '/filter/expression/version',
    id: 'exportFilterExpressionVersion',
    label: 'Filter expression version',
    defaultValue: '{{filter.expression.version}}',
    options: [{ items: [{ label: '1', value: '1' }] }],
  },
  exportFilterExpressionRules: {
    type: 'text',
    helpKey: 'export.filter.expression.rules',
    name: '/filter/expression/rules',
    id: 'exportFilterExpressionRules',
    label: 'Filter expression rules',
    defaultValue: '{{filter.expression.rules}}',
  },
  exportFilterScript_scriptId: {
    type: 'text',
    helpKey: 'export.filter.script._scriptId',
    name: '/filter/script/_scriptId',
    id: 'exportFilterScript_scriptId',
    label: 'Filter script _scriptId',
    defaultValue: '{{filter.script._scriptId}}',
  },
  exportFilterScriptFunction: {
    type: 'text',
    helpKey: 'export.filter.script.function',
    name: '/filter/script/function',
    id: 'exportFilterScriptFunction',
    label: 'Filter script function',
    defaultValue: '{{filter.script.function}}',
  },
  // #endregion filter
  // #region file
  exportFileEncoding: {
    type: 'radiogroup',
    helpKey: 'export.file.encoding',
    name: '/file/encoding',
    id: 'exportFileEncoding',
    label: 'File encoding',
    defaultValue: '{{file.encoding}}',
    options: [
      {
        items: [
          { label: 'Utf8', value: 'utf8' },
          { label: 'Win1252', value: 'win1252' },
          { label: 'Utf-16le', value: 'utf-16le' },
        ],
      },
    ],
  },
  exportFileType: {
    type: 'radiogroup',
    helpKey: 'export.file.type',
    name: '/file/type',
    id: 'exportFileType',
    label: 'File type',
    defaultValue: '{{file.type}}',
    options: [
      {
        items: [
          { label: 'Csv', value: 'csv' },
          { label: 'Json', value: 'json' },
          { label: 'Xlsx', value: 'xlsx' },
          { label: 'Xml', value: 'xml' },
          { label: 'Filedefinition', value: 'filedefinition' },
        ],
      },
    ],
  },
  exportFileOutput: {
    type: 'radiogroup',
    helpKey: 'export.file.output',
    name: '/file/output',
    id: 'exportFileOutput',
    label: 'File output',
    defaultValue: '{{file.output}}',
    options: [
      {
        items: [
          { label: 'Records', value: 'records' },
          { label: 'Metadata', value: 'metadata' },
          { label: 'BlobKeys', value: 'blobKeys' },
        ],
      },
    ],
  },
  exportFileSkipDelete: {
    type: 'checkbox',
    helpKey: 'export.file.skipDelete',
    name: '/file/skipDelete',
    id: 'exportFileSkipDelete',
    label: 'File skipDelete',
    defaultValue: false,
  },
  exportFileCompressionFormat: {
    type: 'radiogroup',
    helpKey: 'export.file.compressionFormat',
    name: '/file/compressionFormat',
    id: 'exportFileCompressionFormat',
    label: 'File compressionFormat',
    defaultValue: '{{file.compressionFormat}}',
    options: [{ items: [{ label: 'Gzip', value: 'gzip' }] }],
  },
  exportFileCsvColumnDelimiter: {
    type: 'text',
    helpKey: 'export.file.csv.columnDelimiter',
    name: '/file/csv/columnDelimiter',
    id: 'exportFileCsvColumnDelimiter',
    label: 'File csv columnDelimiter',
    defaultValue: '{{file.csv.columnDelimiter}}',
  },
  exportFileCsvRowDelimiter: {
    type: 'text',
    helpKey: 'export.file.csv.rowDelimiter',
    name: '/file/csv/rowDelimiter',
    id: 'exportFileCsvRowDelimiter',
    label: 'File csv rowDelimiter',
    defaultValue: '{{file.csv.rowDelimiter}}',
  },
  exportFileCsvKeyColumnss: {
    type: 'text',
    keyName: 'name',
    valueName: 'value',
    valueType: 'array',
    helpKey: 'export.file.csv.keyColumnss',
    name: '/file/csv/keyColumnss',
    id: 'exportFileCsvKeyColumnss',
    label: 'File csv keyColumns',
    defaultValue: '{{file.csv.keyColumns}}',
    validWhen: [],
  },
  exportFileCsvHasHeaderRow: {
    type: 'checkbox',
    helpKey: 'export.file.csv.hasHeaderRow',
    name: '/file/csv/hasHeaderRow',
    id: 'exportFileCsvHasHeaderRow',
    label: 'File csv hasHeaderRow',
    defaultValue: false,
  },
  exportFileCsvTrimSpaces: {
    type: 'checkbox',
    helpKey: 'export.file.csv.trimSpaces',
    name: '/file/csv/trimSpaces',
    id: 'exportFileCsvTrimSpaces',
    label: 'File csv trimSpaces',
    defaultValue: false,
  },
  exportFileCsvRowsToSkip: {
    type: 'text',
    helpKey: 'export.file.csv.rowsToSkip',
    name: '/file/csv/rowsToSkip',
    id: 'exportFileCsvRowsToSkip',
    label: 'File csv rowsToSkip',
    defaultValue: '{{file.csv.rowsToSkip}}',
    validWhen: [
      {
        matchesRegEx: { pattern: '^[\\d]+$', message: 'Only numbers allowed' },
      },
    ],
  },
  exportFileJsonResourcePath: {
    type: 'text',
    helpKey: 'export.file.json.resourcePath',
    name: '/file/json/resourcePath',
    id: 'exportFileJsonResourcePath',
    label: 'File json resourcePath',
    defaultValue: '{{file.json.resourcePath}}',
  },
  exportFileXlsxHasHeaderRow: {
    type: 'checkbox',
    helpKey: 'export.file.xlsx.hasHeaderRow',
    name: '/file/xlsx/hasHeaderRow',
    id: 'exportFileXlsxHasHeaderRow',
    label: 'File xlsx hasHeaderRow',
    defaultValue: false,
  },
  exportFileXlsxKeyColumnss: {
    type: 'text',
    keyName: 'name',
    valueName: 'value',
    valueType: 'array',
    helpKey: 'export.file.xlsx.keyColumnss',
    name: '/file/xlsx/keyColumnss',
    id: 'exportFileXlsxKeyColumnss',
    label: 'File xlsx keyColumns',
    defaultValue: '{{file.xlsx.keyColumns}}',
    validWhen: [],
  },
  exportFileXmlResourcePath: {
    type: 'text',
    helpKey: 'export.file.xml.resourcePath',
    name: '/file/xml/resourcePath',
    id: 'exportFileXmlResourcePath',
    label: 'File xml resourcePath',
    defaultValue: '{{file.xml.resourcePath}}',
  },
  exportFileFileDefinitionResourcePath: {
    type: 'text',
    helpKey: 'export.file.fileDefinition.resourcePath',
    name: '/file/fileDefinition/resourcePath',
    id: 'exportFileFileDefinitionResourcePath',
    label: 'File fileDefinition resourcePath',
    defaultValue: '{{file.fileDefinition.resourcePath}}',
  },
  exportFileFileDefinition_fileDefinitionId: {
    type: 'text',
    helpKey: 'export.file.fileDefinition._fileDefinitionId',
    name: '/file/fileDefinition/_fileDefinitionId',
    id: 'exportFileFileDefinition_fileDefinitionId',
    label: 'File fileDefinition _fileDefinitionId',
    defaultValue: '{{file.fileDefinition._fileDefinitionId}}',
  },
  exportFilePurgeInternalBackup: {
    type: 'checkbox',
    helpKey: 'export.file.purgeInternalBackup',
    name: '/file/purgeInternalBackup',
    id: 'exportFilePurgeInternalBackup',
    label: 'File purgeInternalBackup',
    defaultValue: false,
  },
  // #endregion file
  // #region rest
  exportRestRelativeURI: {
    type: 'text',
    helpKey: 'export.rest.relativeURI',
    name: '/rest/relativeURI',
    id: 'exportRestRelativeURI',
    label: 'Rest relativeURI',
    defaultValue: '{{rest.relativeURI}}',
  },
  exportRestMethod: {
    type: 'radiogroup',
    helpKey: 'export.rest.method',
    name: '/rest/method',
    id: 'exportRestMethod',
    label: 'Rest method',
    defaultValue: '{{rest.method}}',
    options: [
      {
        items: [
          { label: 'GET', value: 'GET' },
          { label: 'POST', value: 'POST' },
          { label: 'PUT', value: 'PUT' },
        ],
      },
    ],
  },
  exportRestPostBody: {
    type: 'text',
    helpKey: 'export.rest.postBody',
    name: '/rest/postBody',
    id: 'exportRestPostBody',
    label: 'Rest postBody',
    defaultValue: '{{rest.postBody}}',
  },
  exportRestResourcePath: {
    type: 'text',
    helpKey: 'export.rest.resourcePath',
    name: '/rest/resourcePath',
    id: 'exportRestResourcePath',
    label: 'Rest resourcePath',
    defaultValue: '{{rest.resourcePath}}',
  },
  exportRestHeaders: {
    type: 'keyvalue',
    keyName: 'name',
    valueName: 'value',
    valueType: 'keyvalue',
    helpKey: 'export.rest.headers',
    name: '/rest/headers',
    id: 'exportRestHeaders',
    label: 'Rest headers',
    defaultValue: '{{rest.headers}}',
  },
  exportRestAllowUndefinedResource: {
    type: 'checkbox',
    helpKey: 'export.rest.allowUndefinedResource',
    name: '/rest/allowUndefinedResource',
    id: 'exportRestAllowUndefinedResource',
    label: 'Rest allowUndefinedResource',
    defaultValue: false,
  },
  exportRestPagingMethod: {
    type: 'radiogroup',
    helpKey: 'export.rest.pagingMethod',
    name: '/rest/pagingMethod',
    id: 'exportRestPagingMethod',
    label: 'Rest pagingMethod',
    defaultValue: '{{rest.pagingMethod}}',
    options: [
      {
        items: [
          { label: 'Nextpageurl', value: 'nextpageurl' },
          { label: 'Pageargument', value: 'pageargument' },
          { label: 'Relativeuri', value: 'relativeuri' },
          { label: 'Linkheader', value: 'linkheader' },
          { label: 'Skipargument', value: 'skipargument' },
          { label: 'Token', value: 'token' },
          { label: 'Postbody', value: 'postbody' },
        ],
      },
    ],
  },
  exportRestNextPagePath: {
    type: 'text',
    helpKey: 'export.rest.nextPagePath',
    name: '/rest/nextPagePath',
    id: 'exportRestNextPagePath',
    label: 'Rest nextPagePath',
    defaultValue: '{{rest.nextPagePath}}',
  },
  exportRestLinkHeaderRelation: {
    type: 'text',
    helpKey: 'export.rest.linkHeaderRelation',
    name: '/rest/linkHeaderRelation',
    id: 'exportRestLinkHeaderRelation',
    label: 'Rest linkHeaderRelation',
    defaultValue: '{{rest.linkHeaderRelation}}',
  },
  exportRestNextPageRelativeURI: {
    type: 'text',
    helpKey: 'export.rest.nextPageRelativeURI',
    name: '/rest/nextPageRelativeURI',
    id: 'exportRestNextPageRelativeURI',
    label: 'Rest nextPageRelativeURI',
    defaultValue: '{{rest.nextPageRelativeURI}}',
  },
  exportRestPageArgument: {
    type: 'text',
    helpKey: 'export.rest.pageArgument',
    name: '/rest/pageArgument',
    id: 'exportRestPageArgument',
    label: 'Rest pageArgument',
    defaultValue: '{{rest.pageArgument}}',
  },
  exportRestPagingPostBody: {
    type: 'text',
    helpKey: 'export.rest.pagingPostBody',
    name: '/rest/pagingPostBody',
    id: 'exportRestPagingPostBody',
    label: 'Rest pagingPostBody',
    defaultValue: '{{rest.pagingPostBody}}',
  },
  exportRestMaxPagePath: {
    type: 'text',
    helpKey: 'export.rest.maxPagePath',
    name: '/rest/maxPagePath',
    id: 'exportRestMaxPagePath',
    label: 'Rest maxPagePath',
    defaultValue: '{{rest.maxPagePath}}',
  },
  exportRestMaxCountPath: {
    type: 'text',
    helpKey: 'export.rest.maxCountPath',
    name: '/rest/maxCountPath',
    id: 'exportRestMaxCountPath',
    label: 'Rest maxCountPath',
    defaultValue: '{{rest.maxCountPath}}',
  },
  exportRestSkipArgument: {
    type: 'text',
    helpKey: 'export.rest.skipArgument',
    name: '/rest/skipArgument',
    id: 'exportRestSkipArgument',
    label: 'Rest skipArgument',
    defaultValue: '{{rest.skipArgument}}',
  },
  exportRestBlobFormat: {
    type: 'text',
    helpKey: 'export.rest.blobFormat',
    name: '/rest/blobFormat',
    id: 'exportRestBlobFormat',
    label: 'Rest blobFormat',
    defaultValue: '{{rest.blobFormat}}',
  },
  exportRestSuccessPath: {
    type: 'text',
    helpKey: 'export.rest.successPath',
    name: '/rest/successPath',
    id: 'exportRestSuccessPath',
    label: 'Rest successPath',
    defaultValue: '{{rest.successPath}}',
  },
  exportRestSuccessValuess: {
    type: 'text',
    keyName: 'name',
    valueName: 'value',
    valueType: 'array',
    helpKey: 'export.rest.successValuess',
    name: '/rest/successValuess',
    id: 'exportRestSuccessValuess',
    label: 'Rest successValues',
    defaultValue: '{{rest.successValues}}',
    validWhen: [],
  },
  exportRestLastPageStatusCode: {
    type: 'text',
    helpKey: 'export.rest.lastPageStatusCode',
    name: '/rest/lastPageStatusCode',
    id: 'exportRestLastPageStatusCode',
    label: 'Rest lastPageStatusCode',
    defaultValue: '{{rest.lastPageStatusCode}}',
    validWhen: [
      {
        matchesRegEx: { pattern: '^[\\d]+$', message: 'Only numbers allowed' },
      },
    ],
  },
  exportRestLastPagePath: {
    type: 'text',
    helpKey: 'export.rest.lastPagePath',
    name: '/rest/lastPagePath',
    id: 'exportRestLastPagePath',
    label: 'Rest lastPagePath',
    defaultValue: '{{rest.lastPagePath}}',
  },
  exportRestLastPageValue: {
    type: 'text',
    helpKey: 'export.rest.lastPageValue',
    name: '/rest/lastPageValue',
    id: 'exportRestLastPageValue',
    label: 'Rest lastPageValue',
    defaultValue: '{{rest.lastPageValue}}',
  },
  exportRestOnceRelativeURI: {
    type: 'text',
    helpKey: 'export.rest.once.relativeURI',
    name: '/rest/once/relativeURI',
    id: 'exportRestOnceRelativeURI',
    label: 'Rest once relativeURI',
    defaultValue: '{{rest.once.relativeURI}}',
  },
  exportRestOnceMethod: {
    type: 'radiogroup',
    helpKey: 'export.rest.once.method',
    name: '/rest/once/method',
    id: 'exportRestOnceMethod',
    label: 'Rest once method',
    defaultValue: '{{rest.once.method}}',
    options: [
      {
        items: [
          { label: 'PUT', value: 'PUT' },
          { label: 'POST', value: 'POST' },
        ],
      },
    ],
  },
  exportRestOncePostBody: {
    type: 'text',
    helpKey: 'export.rest.once.postBody',
    name: '/rest/once/postBody',
    id: 'exportRestOncePostBody',
    label: 'Rest once postBody',
    defaultValue: '{{rest.once.postBody}}',
  },
  // #endregion rest
  // #region ftp
  exportFtpDirectoryPath: {
    type: 'text',
    helpKey: 'export.ftp.directoryPath',
    name: '/ftp/directoryPath',
    id: 'exportFtpDirectoryPath',
    label: 'Ftp directoryPath',
    defaultValue: '{{ftp.directoryPath}}',
  },
  exportFtpFileNameStartsWith: {
    type: 'text',
    helpKey: 'export.ftp.fileNameStartsWith',
    name: '/ftp/fileNameStartsWith',
    id: 'exportFtpFileNameStartsWith',
    label: 'Ftp fileNameStartsWith',
    defaultValue: '{{ftp.fileNameStartsWith}}',
  },
  exportFtpFileNameEndsWith: {
    type: 'text',
    helpKey: 'export.ftp.fileNameEndsWith',
    name: '/ftp/fileNameEndsWith',
    id: 'exportFtpFileNameEndsWith',
    label: 'Ftp fileNameEndsWith',
    defaultValue: '{{ftp.fileNameEndsWith}}',
  },
  exportFtpBackupDirectoryPath: {
    type: 'text',
    helpKey: 'export.ftp.backupDirectoryPath',
    name: '/ftp/backupDirectoryPath',
    id: 'exportFtpBackupDirectoryPath',
    label: 'Ftp backupDirectoryPath',
    defaultValue: '{{ftp.backupDirectoryPath}}',
  },
  // #endregion ftp
  // #region http
  exportHttpSuccessMediaType: {
    type: 'radiogroup',
    helpKey: 'export.http.successMediaType',
    name: '/http/successMediaType',
    id: 'exportHttpSuccessMediaType',
    label: 'Http successMediaType',
    defaultValue: '{{http.successMediaType}}',
    options: [
      {
        items: [
          { label: 'Xml', value: 'xml' },
          { label: 'Csv', value: 'csv' },
          { label: 'Json', value: 'json' },
        ],
      },
    ],
  },
  exportHttpErrorMediaType: {
    type: 'radiogroup',
    helpKey: 'export.http.errorMediaType',
    name: '/http/errorMediaType',
    id: 'exportHttpErrorMediaType',
    label: 'Http errorMediaType',
    defaultValue: '{{http.errorMediaType}}',
    options: [
      {
        items: [
          { label: 'Xml', value: 'xml' },
          { label: 'Json', value: 'json' },
        ],
      },
    ],
  },
  exportHttpRelativeURI: {
    type: 'text',
    helpKey: 'export.http.relativeURI',
    name: '/http/relativeURI',
    id: 'exportHttpRelativeURI',
    label: 'Http relativeURI',
    defaultValue: '{{http.relativeURI}}',
  },
  exportHttpMethod: {
    type: 'radiogroup',
    helpKey: 'export.http.method',
    name: '/http/method',
    id: 'exportHttpMethod',
    label: 'Http method',
    defaultValue: '{{http.method}}',
    options: [
      {
        items: [
          { label: 'GET', value: 'GET' },
          { label: 'PUT', value: 'PUT' },
          { label: 'POST', value: 'POST' },
          { label: 'PATCH', value: 'PATCH' },
          { label: 'DELETE', value: 'DELETE' },
        ],
      },
    ],
  },
  exportHttpBody: {
    type: 'text',
    helpKey: 'export.http.body',
    name: '/http/body',
    id: 'exportHttpBody',
    label: 'Http body',
    defaultValue: '{{http.body}}',
  },
  exportHttpHeaders: {
    type: 'keyvalue',
    keyName: 'name',
    valueName: 'value',
    valueType: 'keyvalue',
    helpKey: 'export.http.headers',
    name: '/http/headers',
    id: 'exportHttpHeaders',
    label: 'Http headers',
    defaultValue: '{{http.headers}}',
  },
  exportHttpPagingMethod: {
    type: 'radiogroup',
    helpKey: 'export.http.paging.method',
    name: '/http/paging/method',
    id: 'exportHttpPagingMethod',
    label: 'Http paging method',
    defaultValue: '{{http.paging.method}}',
    options: [
      {
        items: [
          { label: 'Token', value: 'token' },
          { label: 'Skip', value: 'skip' },
          { label: 'Page', value: 'page' },
          { label: 'Url', value: 'url' },
          { label: 'Linkheader', value: 'linkheader' },
          { label: 'Relativeuri', value: 'relativeuri' },
        ],
      },
    ],
  },
  exportHttpPagingSkip: {
    type: 'text',
    helpKey: 'export.http.paging.skip',
    name: '/http/paging/skip',
    id: 'exportHttpPagingSkip',
    label: 'Http paging skip',
    defaultValue: '{{http.paging.skip}}',
    validWhen: [
      {
        matchesRegEx: { pattern: '^[\\d]+$', message: 'Only numbers allowed' },
      },
    ],
  },
  exportHttpPagingPage: {
    type: 'text',
    helpKey: 'export.http.paging.page',
    name: '/http/paging/page',
    id: 'exportHttpPagingPage',
    label: 'Http paging page',
    defaultValue: '{{http.paging.page}}',
    validWhen: [
      {
        matchesRegEx: { pattern: '^[\\d]+$', message: 'Only numbers allowed' },
      },
    ],
  },
  exportHttpPagingToken: {
    type: 'text',
    helpKey: 'export.http.paging.token',
    name: '/http/paging/token',
    id: 'exportHttpPagingToken',
    label: 'Http paging token',
    defaultValue: '{{http.paging.token}}',
  },
  exportHttpPagingPath: {
    type: 'text',
    helpKey: 'export.http.paging.path',
    name: '/http/paging/path',
    id: 'exportHttpPagingPath',
    label: 'Http paging path',
    defaultValue: '{{http.paging.path}}',
  },
  exportHttpPagingRelativeURI: {
    type: 'text',
    helpKey: 'export.http.paging.relativeURI',
    name: '/http/paging/relativeURI',
    id: 'exportHttpPagingRelativeURI',
    label: 'Http paging relativeURI',
    defaultValue: '{{http.paging.relativeURI}}',
  },
  exportHttpPagingPathAfterFirstRequest: {
    type: 'text',
    helpKey: 'export.http.paging.pathAfterFirstRequest',
    name: '/http/paging/pathAfterFirstRequest',
    id: 'exportHttpPagingPathAfterFirstRequest',
    label: 'Http paging pathAfterFirstRequest',
    defaultValue: '{{http.paging.pathAfterFirstRequest}}',
  },
  exportHttpPagingResourcePath: {
    type: 'text',
    helpKey: 'export.http.paging.resourcePath',
    name: '/http/paging/resourcePath',
    id: 'exportHttpPagingResourcePath',
    label: 'Http paging resourcePath',
    defaultValue: '{{http.paging.resourcePath}}',
  },
  exportHttpPagingMaxPagePath: {
    type: 'text',
    helpKey: 'export.http.paging.maxPagePath',
    name: '/http/paging/maxPagePath',
    id: 'exportHttpPagingMaxPagePath',
    label: 'Http paging maxPagePath',
    defaultValue: '{{http.paging.maxPagePath}}',
  },
  exportHttpPagingMaxCountPath: {
    type: 'text',
    helpKey: 'export.http.paging.maxCountPath',
    name: '/http/paging/maxCountPath',
    id: 'exportHttpPagingMaxCountPath',
    label: 'Http paging maxCountPath',
    defaultValue: '{{http.paging.maxCountPath}}',
  },
  exportHttpPagingLastPageStatusCode: {
    type: 'text',
    helpKey: 'export.http.paging.lastPageStatusCode',
    name: '/http/paging/lastPageStatusCode',
    id: 'exportHttpPagingLastPageStatusCode',
    label: 'Http paging lastPageStatusCode',
    defaultValue: '{{http.paging.lastPageStatusCode}}',
    validWhen: [
      {
        matchesRegEx: { pattern: '^[\\d]+$', message: 'Only numbers allowed' },
      },
    ],
  },
  exportHttpPagingLastPagePath: {
    type: 'text',
    helpKey: 'export.http.paging.lastPagePath',
    name: '/http/paging/lastPagePath',
    id: 'exportHttpPagingLastPagePath',
    label: 'Http paging lastPagePath',
    defaultValue: '{{http.paging.lastPagePath}}',
  },
  exportHttpPagingLastPageValuess: {
    type: 'text',
    keyName: 'name',
    valueName: 'value',
    valueType: 'array',
    helpKey: 'export.http.paging.lastPageValuess',
    name: '/http/paging/lastPageValuess',
    id: 'exportHttpPagingLastPageValuess',
    label: 'Http paging lastPageValues',
    defaultValue: '{{http.paging.lastPageValues}}',
    validWhen: [],
  },
  exportHttpPagingLinkHeaderRelation: {
    type: 'text',
    helpKey: 'export.http.paging.linkHeaderRelation',
    name: '/http/paging/linkHeaderRelation',
    id: 'exportHttpPagingLinkHeaderRelation',
    label: 'Http paging linkHeaderRelation',
    defaultValue: '{{http.paging.linkHeaderRelation}}',
  },
  exportHttp_asyncHelperId: {
    type: 'text',
    helpKey: 'export.http._asyncHelperId',
    name: '/http/_asyncHelperId',
    id: 'exportHttp_asyncHelperId',
    label: 'Http _asyncHelperId',
    defaultValue: '{{http._asyncHelperId}}',
  },
  exportHttpOnceRelativeURI: {
    type: 'text',
    helpKey: 'export.http.once.relativeURI',
    name: '/http/once/relativeURI',
    id: 'exportHttpOnceRelativeURI',
    label: 'Http once relativeURI',
    defaultValue: '{{http.once.relativeURI}}',
  },
  exportHttpOnceMethod: {
    type: 'radiogroup',
    helpKey: 'export.http.once.method',
    name: '/http/once/method',
    id: 'exportHttpOnceMethod',
    label: 'Http once method',
    defaultValue: '{{http.once.method}}',
    options: [
      {
        items: [
          { label: 'GET', value: 'GET' },
          { label: 'PUT', value: 'PUT' },
          { label: 'POST', value: 'POST' },
          { label: 'PATCH', value: 'PATCH' },
          { label: 'DELETE', value: 'DELETE' },
        ],
      },
    ],
  },
  exportHttpOnceBody: {
    type: 'text',
    helpKey: 'export.http.once.body',
    name: '/http/once/body',
    id: 'exportHttpOnceBody',
    label: 'Http once body',
    defaultValue: '{{http.once.body}}',
  },
  exportHttpResponseResourcePath: {
    type: 'text',
    helpKey: 'export.http.response.resourcePath',
    name: '/http/response/resourcePath',
    id: 'exportHttpResponseResourcePath',
    label: 'Http response resourcePath',
    defaultValue: '{{http.response.resourcePath}}',
  },
  exportHttpResponseResourceIdPath: {
    type: 'text',
    helpKey: 'export.http.response.resourceIdPath',
    name: '/http/response/resourceIdPath',
    id: 'exportHttpResponseResourceIdPath',
    label: 'Http response resourceIdPath',
    defaultValue: '{{http.response.resourceIdPath}}',
  },
  exportHttpResponseSuccessPath: {
    type: 'text',
    helpKey: 'export.http.response.successPath',
    name: '/http/response/successPath',
    id: 'exportHttpResponseSuccessPath',
    label: 'Http response successPath',
    defaultValue: '{{http.response.successPath}}',
  },
  exportHttpResponseSuccessValuess: {
    type: 'text',
    keyName: 'name',
    valueName: 'value',
    valueType: 'array',
    helpKey: 'export.http.response.successValuess',
    name: '/http/response/successValuess',
    id: 'exportHttpResponseSuccessValuess',
    label: 'Http response successValues',
    defaultValue: '{{http.response.successValues}}',
    validWhen: [],
  },
  exportHttpResponseErrorPath: {
    type: 'text',
    helpKey: 'export.http.response.errorPath',
    name: '/http/response/errorPath',
    id: 'exportHttpResponseErrorPath',
    label: 'Http response errorPath',
    defaultValue: '{{http.response.errorPath}}',
  },
  exportHttpResponseBlobFormat: {
    type: 'text',
    helpKey: 'export.http.response.blobFormat',
    name: '/http/response/blobFormat',
    id: 'exportHttpResponseBlobFormat',
    label: 'Http response blobFormat',
    defaultValue: '{{http.response.blobFormat}}',
  },
  // #endregion http
  // #region netsuite
  exportNetsuiteType: {
    type: 'radiogroup',
    helpKey: 'export.netsuite.type',
    name: '/netsuite/type',
    id: 'exportNetsuiteType',
    label: 'Netsuite type',
    defaultValue: '{{netsuite.type}}',
    options: [
      {
        items: [
          { label: 'Search', value: 'search' },
          { label: 'BasicSearch', value: 'basicSearch' },
          { label: 'Metadata', value: 'metadata' },
          { label: 'Selectoption', value: 'selectoption' },
          { label: 'Restlet', value: 'restlet' },
          { label: 'GetList', value: 'getList' },
          { label: 'GetServerTime', value: 'getServerTime' },
          { label: 'Distributed', value: 'distributed' },
        ],
      },
    ],
  },
  exportNetsuiteSearchess: {
    type: 'text',
    keyName: 'name',
    valueName: 'value',
    valueType: 'array',
    helpKey: 'export.netsuite.searchess',
    name: '/netsuite/searchess',
    id: 'exportNetsuiteSearchess',
    label: 'Netsuite searches',
    defaultValue: '{{netsuite.searches}}',
    validWhen: [],
  },
  exportNetsuiteMetadata: {
    type: 'text',
    helpKey: 'export.netsuite.metadata',
    name: '/netsuite/metadata',
    id: 'exportNetsuiteMetadata',
    label: 'Netsuite metadata',
    defaultValue: '{{netsuite.metadata}}',
  },
  exportNetsuiteSelectoption: {
    type: 'text',
    helpKey: 'export.netsuite.selectoption',
    name: '/netsuite/selectoption',
    id: 'exportNetsuiteSelectoption',
    label: 'Netsuite selectoption',
    defaultValue: '{{netsuite.selectoption}}',
  },
  exportNetsuiteCustomFieldMetadata: {
    type: 'text',
    helpKey: 'export.netsuite.customFieldMetadata',
    name: '/netsuite/customFieldMetadata',
    id: 'exportNetsuiteCustomFieldMetadata',
    label: 'Netsuite customFieldMetadata',
    defaultValue: '{{netsuite.customFieldMetadata}}',
  },
  exportNetsuiteSkipGrouping: {
    type: 'checkbox',
    helpKey: 'export.netsuite.skipGrouping',
    name: '/netsuite/skipGrouping',
    id: 'exportNetsuiteSkipGrouping',
    label: 'Netsuite skipGrouping',
    defaultValue: false,
  },
  exportNetsuiteStatsOnly: {
    type: 'checkbox',
    helpKey: 'export.netsuite.statsOnly',
    name: '/netsuite/statsOnly',
    id: 'exportNetsuiteStatsOnly',
    label: 'Netsuite statsOnly',
    defaultValue: false,
  },
  exportNetsuiteInternalId: {
    type: 'text',
    helpKey: 'export.netsuite.internalId',
    name: '/netsuite/internalId',
    id: 'exportNetsuiteInternalId',
    label: 'Netsuite internalId',
    defaultValue: '{{netsuite.internalId}}',
  },
  exportNetsuiteRestletRecordType: {
    type: 'text',
    helpKey: 'export.netsuite.restlet.recordType',
    name: '/netsuite/restlet/recordType',
    id: 'exportNetsuiteRestletRecordType',
    label: 'Netsuite restlet recordType',
    defaultValue: '{{netsuite.restlet.recordType}}',
  },
  exportNetsuiteRestletSearchId: {
    type: 'text',
    helpKey: 'export.netsuite.restlet.searchId',
    name: '/netsuite/restlet/searchId',
    id: 'exportNetsuiteRestletSearchId',
    label: 'Netsuite restlet searchId',
    defaultValue: '{{netsuite.restlet.searchId}}',
  },
  'exportNetsuiteRestletCriteria[*]Field': {
    type: 'text',
    helpKey: 'export.netsuite.restlet.criteria[*].field',
    name: '/netsuite/restlet/criteria[*]/field',
    id: 'exportNetsuiteRestletCriteria[*]Field',
    label: 'Netsuite restlet criteria[*] field',
    defaultValue: '{{netsuite.restlet.criteria[*].field}}',
  },
  'exportNetsuiteRestletCriteria[*]Join': {
    type: 'text',
    helpKey: 'export.netsuite.restlet.criteria[*].join',
    name: '/netsuite/restlet/criteria[*]/join',
    id: 'exportNetsuiteRestletCriteria[*]Join',
    label: 'Netsuite restlet criteria[*] join',
    defaultValue: '{{netsuite.restlet.criteria[*].join}}',
  },
  'exportNetsuiteRestletCriteria[*]Operator': {
    type: 'text',
    helpKey: 'export.netsuite.restlet.criteria[*].operator',
    name: '/netsuite/restlet/criteria[*]/operator',
    id: 'exportNetsuiteRestletCriteria[*]Operator',
    label: 'Netsuite restlet criteria[*] operator',
    defaultValue: '{{netsuite.restlet.criteria[*].operator}}',
  },
  'exportNetsuiteRestletCriteria[*]SearchValue': {
    type: 'text',
    helpKey: 'export.netsuite.restlet.criteria[*].searchValue',
    name: '/netsuite/restlet/criteria[*]/searchValue',
    id: 'exportNetsuiteRestletCriteria[*]SearchValue',
    label: 'Netsuite restlet criteria[*] searchValue',
    defaultValue: '{{netsuite.restlet.criteria[*].searchValue}}',
  },
  'exportNetsuiteRestletCriteria[*]SearchValue2': {
    type: 'text',
    helpKey: 'export.netsuite.restlet.criteria[*].searchValue2',
    name: '/netsuite/restlet/criteria[*]/searchValue2',
    id: 'exportNetsuiteRestletCriteria[*]SearchValue2',
    label: 'Netsuite restlet criteria[*] searchValue2',
    defaultValue: '{{netsuite.restlet.criteria[*].searchValue2}}',
  },
  exportNetsuiteRestletBatchSize: {
    type: 'text',
    helpKey: 'export.netsuite.restlet.batchSize',
    name: '/netsuite/restlet/batchSize',
    id: 'exportNetsuiteRestletBatchSize',
    label: 'Netsuite restlet batchSize',
    defaultValue: '{{netsuite.restlet.batchSize}}',
    validWhen: [
      {
        matchesRegEx: { pattern: '^[\\d]+$', message: 'Only numbers allowed' },
      },
    ],
  },
  exportNetsuiteRestletHooksBatchSize: {
    type: 'text',
    helpKey: 'export.netsuite.restlet.hooks.batchSize',
    name: '/netsuite/restlet/hooks/batchSize',
    id: 'exportNetsuiteRestletHooksBatchSize',
    label: 'Netsuite restlet hooks batchSize',
    defaultValue: '{{netsuite.restlet.hooks.batchSize}}',
    validWhen: [
      {
        matchesRegEx: { pattern: '^[\\d]+$', message: 'Only numbers allowed' },
      },
    ],
  },
  exportNetsuiteRestletHooksPreSendFileInternalId: {
    type: 'text',
    helpKey: 'export.netsuite.restlet.hooks.preSend.fileInternalId',
    name: '/netsuite/restlet/hooks/preSend/fileInternalId',
    id: 'exportNetsuiteRestletHooksPreSendFileInternalId',
    label: 'Netsuite restlet hooks preSend fileInternalId',
    defaultValue: '{{netsuite.restlet.hooks.preSend.fileInternalId}}',
  },
  exportNetsuiteRestletHooksPreSendFunction: {
    type: 'text',
    helpKey: 'export.netsuite.restlet.hooks.preSend.function',
    name: '/netsuite/restlet/hooks/preSend/function',
    id: 'exportNetsuiteRestletHooksPreSendFunction',
    label: 'Netsuite restlet hooks preSend function',
    defaultValue: '{{netsuite.restlet.hooks.preSend.function}}',
  },
  exportNetsuiteRestletHooksPreSendConfiguration: {
    type: 'text',
    helpKey: 'export.netsuite.restlet.hooks.preSend.configuration',
    name: '/netsuite/restlet/hooks/preSend/configuration',
    id: 'exportNetsuiteRestletHooksPreSendConfiguration',
    label: 'Netsuite restlet hooks preSend configuration',
    defaultValue: '{{netsuite.restlet.hooks.preSend.configuration}}',
  },
  exportNetsuiteDistributedRecordType: {
    type: 'text',
    helpKey: 'export.netsuite.distributed.recordType',
    name: '/netsuite/distributed/recordType',
    id: 'exportNetsuiteDistributedRecordType',
    label: 'Netsuite distributed recordType',
    defaultValue: '{{netsuite.distributed.recordType}}',
  },
  exportNetsuiteDistributedExecutionContexts: {
    type: 'text',
    keyName: 'name',
    valueName: 'value',
    valueType: 'array',
    helpKey: 'export.netsuite.distributed.executionContexts',
    name: '/netsuite/distributed/executionContexts',
    id: 'exportNetsuiteDistributedExecutionContexts',
    label: 'Netsuite distributed executionContext',
    defaultValue: '{{netsuite.distributed.executionContext}}',
    validWhen: [],
  },
  exportNetsuiteDistributedDisabled: {
    type: 'checkbox',
    helpKey: 'export.netsuite.distributed.disabled',
    name: '/netsuite/distributed/disabled',
    id: 'exportNetsuiteDistributedDisabled',
    label: 'Netsuite distributed disabled',
    defaultValue: false,
  },
  exportNetsuiteDistributedExecutionTypes: {
    type: 'text',
    keyName: 'name',
    valueName: 'value',
    valueType: 'array',
    helpKey: 'export.netsuite.distributed.executionTypes',
    name: '/netsuite/distributed/executionTypes',
    id: 'exportNetsuiteDistributedExecutionTypes',
    label: 'Netsuite distributed executionType',
    defaultValue: '{{netsuite.distributed.executionType}}',
    validWhen: [],
  },
  exportNetsuiteDistributedQualifier: {
    type: 'text',
    helpKey: 'export.netsuite.distributed.qualifier',
    name: '/netsuite/distributed/qualifier',
    id: 'exportNetsuiteDistributedQualifier',
    label: 'Netsuite distributed qualifier',
    defaultValue: '{{netsuite.distributed.qualifier}}',
  },
  exportNetsuiteDistributedHooksPreSendFileInternalId: {
    type: 'text',
    helpKey: 'export.netsuite.distributed.hooks.preSend.fileInternalId',
    name: '/netsuite/distributed/hooks/preSend/fileInternalId',
    id: 'exportNetsuiteDistributedHooksPreSendFileInternalId',
    label: 'Netsuite distributed hooks preSend fileInternalId',
    defaultValue: '{{netsuite.distributed.hooks.preSend.fileInternalId}}',
  },
  exportNetsuiteDistributedHooksPreSendFunction: {
    type: 'text',
    helpKey: 'export.netsuite.distributed.hooks.preSend.function',
    name: '/netsuite/distributed/hooks/preSend/function',
    id: 'exportNetsuiteDistributedHooksPreSendFunction',
    label: 'Netsuite distributed hooks preSend function',
    defaultValue: '{{netsuite.distributed.hooks.preSend.function}}',
  },
  exportNetsuiteDistributedHooksPreSendConfiguration: {
    type: 'text',
    helpKey: 'export.netsuite.distributed.hooks.preSend.configuration',
    name: '/netsuite/distributed/hooks/preSend/configuration',
    id: 'exportNetsuiteDistributedHooksPreSendConfiguration',
    label: 'Netsuite distributed hooks preSend configuration',
    defaultValue: '{{netsuite.distributed.hooks.preSend.configuration}}',
  },
  exportNetsuiteDistributedSublists: {
    type: 'text',
    helpKey: 'export.netsuite.distributed.sublists',
    name: '/netsuite/distributed/sublists',
    id: 'exportNetsuiteDistributedSublists',
    label: 'Netsuite distributed sublists',
    defaultValue: '{{netsuite.distributed.sublists}}',
  },
  exportNetsuiteDistributedForceReload: {
    type: 'checkbox',
    helpKey: 'export.netsuite.distributed.forceReload',
    name: '/netsuite/distributed/forceReload',
    id: 'exportNetsuiteDistributedForceReload',
    label: 'Netsuite distributed forceReload',
    defaultValue: false,
  },
  exportNetsuiteDistributedIoEnvironment: {
    type: 'text',
    helpKey: 'export.netsuite.distributed.ioEnvironment',
    name: '/netsuite/distributed/ioEnvironment',
    id: 'exportNetsuiteDistributedIoEnvironment',
    label: 'Netsuite distributed ioEnvironment',
    defaultValue: '{{netsuite.distributed.ioEnvironment}}',
  },
  exportNetsuiteDistributedLastSyncedDate: {
    type: 'text',
    helpKey: 'export.netsuite.distributed.lastSyncedDate',
    name: '/netsuite/distributed/lastSyncedDate',
    id: 'exportNetsuiteDistributedLastSyncedDate',
    label: 'Netsuite distributed lastSyncedDate',
    defaultValue: '{{netsuite.distributed.lastSyncedDate}}',
  },
  exportNetsuiteDistributedSettings: {
    type: 'text',
    helpKey: 'export.netsuite.distributed.settings',
    name: '/netsuite/distributed/settings',
    id: 'exportNetsuiteDistributedSettings',
    label: 'Netsuite distributed settings',
    defaultValue: '{{netsuite.distributed.settings}}',
  },
  'exportNetsuiteGetList[*]Type': {
    type: 'text',
    helpKey: 'export.netsuite.getList[*].type',
    name: '/netsuite/getList[*]/type',
    id: 'exportNetsuiteGetList[*]Type',
    label: 'Netsuite getList[*] type',
    defaultValue: '{{netsuite.getList[*].type}}',
  },
  'exportNetsuiteGetList[*]TypeId': {
    type: 'text',
    helpKey: 'export.netsuite.getList[*].typeId',
    name: '/netsuite/getList[*]/typeId',
    id: 'exportNetsuiteGetList[*]TypeId',
    label: 'Netsuite getList[*] typeId',
    defaultValue: '{{netsuite.getList[*].typeId}}',
  },
  'exportNetsuiteGetList[*]InternalId': {
    type: 'text',
    helpKey: 'export.netsuite.getList[*].internalId',
    name: '/netsuite/getList[*]/internalId',
    id: 'exportNetsuiteGetList[*]InternalId',
    label: 'Netsuite getList[*] internalId',
    defaultValue: '{{netsuite.getList[*].internalId}}',
  },
  'exportNetsuiteGetList[*]ExternalId': {
    type: 'text',
    helpKey: 'export.netsuite.getList[*].externalId',
    name: '/netsuite/getList[*]/externalId',
    id: 'exportNetsuiteGetList[*]ExternalId',
    label: 'Netsuite getList[*] externalId',
    defaultValue: '{{netsuite.getList[*].externalId}}',
  },
  exportNetsuiteSearchPreferencesBodyFieldsOnly: {
    type: 'checkbox',
    helpKey: 'export.netsuite.searchPreferences.bodyFieldsOnly',
    name: '/netsuite/searchPreferences/bodyFieldsOnly',
    id: 'exportNetsuiteSearchPreferencesBodyFieldsOnly',
    label: 'Netsuite searchPreferences bodyFieldsOnly',
    defaultValue: false,
  },
  exportNetsuiteSearchPreferencesPageSize: {
    type: 'text',
    helpKey: 'export.netsuite.searchPreferences.pageSize',
    name: '/netsuite/searchPreferences/pageSize',
    id: 'exportNetsuiteSearchPreferencesPageSize',
    label: 'Netsuite searchPreferences pageSize',
    defaultValue: '{{netsuite.searchPreferences.pageSize}}',
    validWhen: [
      {
        matchesRegEx: { pattern: '^[\\d]+$', message: 'Only numbers allowed' },
      },
    ],
  },
  exportNetsuiteSearchPreferencesReturnSearchColumns: {
    type: 'checkbox',
    helpKey: 'export.netsuite.searchPreferences.returnSearchColumns',
    name: '/netsuite/searchPreferences/returnSearchColumns',
    id: 'exportNetsuiteSearchPreferencesReturnSearchColumns',
    label: 'Netsuite searchPreferences returnSearchColumns',
    defaultValue: false,
  },
  // #endregion netsuite
  // #region rdbms
  exportRdbmsQuery: {
    type: 'text',
    helpKey: 'export.rdbms.query',
    name: '/rdbms/query',
    id: 'exportRdbmsQuery',
    label: 'Rdbms query',
    defaultValue: '{{rdbms.query}}',
  },
  exportRdbmsOnceQuery: {
    type: 'text',
    helpKey: 'export.rdbms.once.query',
    name: '/rdbms/once/query',
    id: 'exportRdbmsOnceQuery',
    label: 'Rdbms once query',
    defaultValue: '{{rdbms.once.query}}',
  },
  // #endregion rdbms
  // #region s3
  exportS3Region: {
    type: 'radiogroup',
    helpKey: 'export.s3.region',
    name: '/s3/region',
    id: 'exportS3Region',
    label: 'S3 region',
    defaultValue: '{{s3.region}}',
    options: [
      {
        items: [
          { label: 'Us-east-1', value: 'us-east-1' },
          { label: 'Us-east-2', value: 'us-east-2' },
          { label: 'Us-west-1', value: 'us-west-1' },
          { label: 'Us-west-2', value: 'us-west-2' },
          { label: 'Ca-central-1', value: 'ca-central-1' },
          { label: 'Ap-south-1', value: 'ap-south-1' },
          { label: 'Ap-northeast-2', value: 'ap-northeast-2' },
          { label: 'Ap-southeast-1', value: 'ap-southeast-1' },
          { label: 'Ap-southeast-2', value: 'ap-southeast-2' },
          { label: 'Ap-northeast-1', value: 'ap-northeast-1' },
          { label: 'Eu-central-1', value: 'eu-central-1' },
          { label: 'Eu-west-1', value: 'eu-west-1' },
          { label: 'Eu-west-2', value: 'eu-west-2' },
          { label: 'Sa-east-1', value: 'sa-east-1' },
          { label: 'Cn-north-1', value: 'cn-north-1' },
        ],
      },
    ],
  },
  exportS3Bucket: {
    type: 'text',
    helpKey: 'export.s3.bucket',
    name: '/s3/bucket',
    id: 'exportS3Bucket',
    label: 'S3 bucket',
    defaultValue: '{{s3.bucket}}',
  },
  exportS3KeyStartsWith: {
    type: 'text',
    helpKey: 'export.s3.keyStartsWith',
    name: '/s3/keyStartsWith',
    id: 'exportS3KeyStartsWith',
    label: 'S3 keyStartsWith',
    defaultValue: '{{s3.keyStartsWith}}',
  },
  exportS3KeyEndsWith: {
    type: 'text',
    helpKey: 'export.s3.keyEndsWith',
    name: '/s3/keyEndsWith',
    id: 'exportS3KeyEndsWith',
    label: 'S3 keyEndsWith',
    defaultValue: '{{s3.keyEndsWith}}',
  },
  exportS3BackupBucket: {
    type: 'text',
    helpKey: 'export.s3.backupBucket',
    name: '/s3/backupBucket',
    id: 'exportS3BackupBucket',
    label: 'S3 backupBucket',
    defaultValue: '{{s3.backupBucket}}',
  },
  // #endregion s3
  // #region salesforce
  exportSalesforceType: {
    type: 'radiogroup',
    helpKey: 'export.salesforce.type',
    name: '/salesforce/type',
    id: 'exportSalesforceType',
    label: 'Salesforce type',
    defaultValue: '{{salesforce.type}}',
    options: [{ items: [{ label: 'Soql', value: 'soql' }] }],
  },
  exportSalesforceSObjectType: {
    type: 'text',
    helpKey: 'export.salesforce.sObjectType',
    name: '/salesforce/sObjectType',
    id: 'exportSalesforceSObjectType',
    label: 'Salesforce sObjectType',
    defaultValue: '{{salesforce.sObjectType}}',
  },
  exportSalesforceId: {
    type: 'text',
    helpKey: 'export.salesforce.id',
    name: '/salesforce/id',
    id: 'exportSalesforceId',
    label: 'Salesforce id',
    defaultValue: '{{salesforce.id}}',
  },
  exportSalesforceApi: {
    type: 'radiogroup',
    helpKey: 'export.salesforce.api',
    name: '/salesforce/api',
    id: 'exportSalesforceApi',
    label: 'Salesforce api',
    defaultValue: '{{salesforce.api}}',
    options: [
      {
        items: [
          { label: 'Rest', value: 'rest' },
          { label: 'Soap', value: 'soap' },
        ],
      },
    ],
  },
  exportSalesforceSoqlQuery: {
    type: 'text',
    helpKey: 'export.salesforce.soql.query',
    name: '/salesforce/soql/query',
    id: 'exportSalesforceSoqlQuery',
    label: 'Salesforce soql query',
    defaultValue: '{{salesforce.soql.query}}',
  },
  exportSalesforceDistributedReferencedFieldss: {
    type: 'text',
    keyName: 'name',
    valueName: 'value',
    valueType: 'array',
    helpKey: 'export.salesforce.distributed.referencedFieldss',
    name: '/salesforce/distributed/referencedFieldss',
    id: 'exportSalesforceDistributedReferencedFieldss',
    label: 'Salesforce distributed referencedFields',
    defaultValue: '{{salesforce.distributed.referencedFields}}',
    validWhen: [],
  },
  exportSalesforceDistributedDisabled: {
    type: 'checkbox',
    helpKey: 'export.salesforce.distributed.disabled',
    name: '/salesforce/distributed/disabled',
    id: 'exportSalesforceDistributedDisabled',
    label: 'Salesforce distributed disabled',
    defaultValue: false,
  },
  exportSalesforceDistributedConnectorId: {
    type: 'text',
    helpKey: 'export.salesforce.distributed.connectorId',
    name: '/salesforce/distributed/connectorId',
    id: 'exportSalesforceDistributedConnectorId',
    label: 'Salesforce distributed connectorId',
    defaultValue: '{{salesforce.distributed.connectorId}}',
  },
  exportSalesforceDistributedUserDefinedReferencedFieldss: {
    type: 'text',
    keyName: 'name',
    valueName: 'value',
    valueType: 'array',
    helpKey: 'export.salesforce.distributed.userDefinedReferencedFieldss',
    name: '/salesforce/distributed/userDefinedReferencedFieldss',
    id: 'exportSalesforceDistributedUserDefinedReferencedFieldss',
    label: 'Salesforce distributed userDefinedReferencedFields',
    defaultValue: '{{salesforce.distributed.userDefinedReferencedFields}}',
    validWhen: [],
  },
  exportSalesforceDistributedQualifier: {
    type: 'text',
    helpKey: 'export.salesforce.distributed.qualifier',
    name: '/salesforce/distributed/qualifier',
    id: 'exportSalesforceDistributedQualifier',
    label: 'Salesforce distributed qualifier',
    defaultValue: '{{salesforce.distributed.qualifier}}',
  },
  'exportSalesforceDistributedRelatedLists[*]ReferencedFieldss': {
    type: 'text',
    keyName: 'name',
    valueName: 'value',
    valueType: 'array',
    helpKey: 'export.salesforce.distributed.relatedLists[*].referencedFieldss',
    name: '/salesforce/distributed/relatedLists[*]/referencedFieldss',
    id: 'exportSalesforceDistributedRelatedLists[*]ReferencedFieldss',
    label: 'Salesforce distributed relatedLists[*] referencedFields',
    defaultValue: '{{salesforce.distributed.relatedLists[*].referencedFields}}',
    validWhen: [],
  },
  'exportSalesforceDistributedRelatedLists[*]ParentField': {
    type: 'text',
    helpKey: 'export.salesforce.distributed.relatedLists[*].parentField',
    name: '/salesforce/distributed/relatedLists[*]/parentField',
    id: 'exportSalesforceDistributedRelatedLists[*]ParentField',
    label: 'Salesforce distributed relatedLists[*] parentField',
    defaultValue: '{{salesforce.distributed.relatedLists[*].parentField}}',
  },
  'exportSalesforceDistributedRelatedLists[*]SObjectType': {
    type: 'text',
    helpKey: 'export.salesforce.distributed.relatedLists[*].sObjectType',
    name: '/salesforce/distributed/relatedLists[*]/sObjectType',
    id: 'exportSalesforceDistributedRelatedLists[*]SObjectType',
    label: 'Salesforce distributed relatedLists[*] sObjectType',
    defaultValue: '{{salesforce.distributed.relatedLists[*].sObjectType}}',
  },
  'exportSalesforceDistributedRelatedLists[*]Filter': {
    type: 'text',
    helpKey: 'export.salesforce.distributed.relatedLists[*].filter',
    name: '/salesforce/distributed/relatedLists[*]/filter',
    id: 'exportSalesforceDistributedRelatedLists[*]Filter',
    label: 'Salesforce distributed relatedLists[*] filter',
    defaultValue: '{{salesforce.distributed.relatedLists[*].filter}}',
  },
  'exportSalesforceDistributedRelatedLists[*]OrderBy': {
    type: 'text',
    helpKey: 'export.salesforce.distributed.relatedLists[*].orderBy',
    name: '/salesforce/distributed/relatedLists[*]/orderBy',
    id: 'exportSalesforceDistributedRelatedLists[*]OrderBy',
    label: 'Salesforce distributed relatedLists[*] orderBy',
    defaultValue: '{{salesforce.distributed.relatedLists[*].orderBy}}',
  },
  'exportSalesforceDistributedRelatedLists[*]UserDefined': {
    type: 'text',
    helpKey: 'export.salesforce.distributed.relatedLists[*].userDefined',
    name: '/salesforce/distributed/relatedLists[*]/userDefined',
    id: 'exportSalesforceDistributedRelatedLists[*]UserDefined',
    label: 'Salesforce distributed relatedLists[*] userDefined',
    defaultValue: '{{salesforce.distributed.relatedLists[*].userDefined}}',
  },
  // #endregion salesforce
  // #region wrapper
  exportWrapperFunction: {
    type: 'text',
    helpKey: 'export.wrapper.function',
    name: '/wrapper/function',
    id: 'exportWrapperFunction',
    label: 'Wrapper function',
    defaultValue: '{{wrapper.function}}',
  },
  exportWrapperConfiguration: {
    type: 'text',
    helpKey: 'export.wrapper.configuration',
    name: '/wrapper/configuration',
    id: 'exportWrapperConfiguration',
    label: 'Wrapper configuration',
    defaultValue: '{{wrapper.configuration}}',
  },
  // #endregion wrapper
  // #region mongodb
  exportMongodbMethod: {
    type: 'radiogroup',
    helpKey: 'export.mongodb.method',
    name: '/mongodb/method',
    id: 'exportMongodbMethod',
    label: 'Mongodb method',
    defaultValue: '{{mongodb.method}}',
    options: [{ items: [{ label: 'Find', value: 'find' }] }],
  },
  exportMongodbCollection: {
    type: 'text',
    helpKey: 'export.mongodb.collection',
    name: '/mongodb/collection',
    id: 'exportMongodbCollection',
    label: 'Mongodb collection',
    defaultValue: '{{mongodb.collection}}',
  },
  exportMongodbFilter: {
    type: 'text',
    helpKey: 'export.mongodb.filter',
    name: '/mongodb/filter',
    id: 'exportMongodbFilter',
    label: 'Mongodb filter',
    defaultValue: '{{mongodb.filter}}',
  },
  exportMongodbProjection: {
    type: 'text',
    helpKey: 'export.mongodb.projection',
    name: '/mongodb/projection',
    id: 'exportMongodbProjection',
    label: 'Mongodb projection',
    defaultValue: '{{mongodb.projection}}',
  },
  // #endregion mongodb
  // #region as2
  exportAs2FileKey: {
    type: 'text',
    helpKey: 'export.as2.fileKey',
    name: '/as2/fileKey',
    id: 'exportAs2FileKey',
    label: 'As2 fileKey',
    defaultValue: '{{as2.fileKey}}',
  },
  // #endregion as2
};
