export default {
  fields: [
    { fieldId: 'type' },
    { fieldId: 'name' },
    { fieldId: 'assistant' },
    { fieldId: 'as2.as2Id' },
    { fieldId: 'as2.partnerId' },
    { fieldId: 'as2.encrypted' },
    { fieldId: 'as2.concurrencylevel' },
    { fieldId: 'as2.unencrypted' },
    { fieldId: 'as2.encrypteds' },
  ],
  fieldSets: [
    {
      header: 'content.based.flow.router',
      collapsed: false,
      fields: [
        { fieldId: 'as2.contentBasedFlowRouter.function' },
        { fieldId: 'as2.contentBasedFlowRouter._scriptId' },
      ],
    },
    {
      header: 'partner.station.info',
      collapsed: false,
      fields: [
        { fieldId: 'as2.partnerStationInfo.as2URI' },
        { fieldId: 'as2.partnerStationInfo.mdn.mdnURL' },
        { fieldId: 'as2.partnerStationInfo.mdn.signatureProtocol' },
        { fieldId: 'as2.partnerStationInfo.mdn.mdnSigning' },
        { fieldId: 'as2.partnerStationInfo.auth.failStatusCode' },
        { fieldId: 'as2.partnerStationInfo.auth.failPath' },
        { fieldId: 'as2.partnerStationInfo.auth.failValuess' },
        { fieldId: 'as2.partnerStationInfo.auth.basic.username' },
        { fieldId: 'as2.partnerStationInfo.auth.basic.password' },
        { fieldId: 'as2.partnerStationInfo.auth.token.token' },
        { fieldId: 'as2.partnerStationInfo.auth.token.location' },
        { fieldId: 'as2.partnerStationInfo.auth.token.headerName' },
        { fieldId: 'as2.partnerStationInfo.auth.token.scheme' },
        { fieldId: 'as2.partnerStationInfo.auth.token.paramName' },
        { fieldId: 'as2.partnerStationInfo.auth.token.refreshMethod' },
        { fieldId: 'as2.partnerStationInfo.auth.token.refresh.relativeURI' },
        { fieldId: 'as2.partnerStationInfo.auth.token.refresh.body' },
        { fieldId: 'as2.partnerStationInfo.auth.token.refreshTokenPath' },
        { fieldId: 'as2.partnerStationInfo.auth.token.refreshMediaType' },
        { fieldId: 'as2.partnerStationInfo.auth.token.refreshHeaders' },
        { fieldId: 'as2.partnerStationInfo.auth.token.refresh.token' },
        { fieldId: 'as2.partnerStationInfo.rateLimit.failStatusCode' },
        { fieldId: 'as2.partnerStationInfo.rateLimit.failPath' },
        { fieldId: 'as2.partnerStationInfo.rateLimit.failValuess' },
        { fieldId: 'as2.partnerStationInfo.rateLimit.limit' },
        { fieldId: 'as2.partnerStationInfo.SMIMEVersion' },
        { fieldId: 'as2.partnerStationInfo.encryptionType' },
        { fieldId: 'as2.partnerStationInfo.signing' },
        { fieldId: 'as2.partnerStationInfo.encoding' },
      ],
    },
    {
      header: 'user.station.info',
      collapsed: false,
      fields: [
        { fieldId: 'as2.userStationInfo.mdn.mdnURL' },
        { fieldId: 'as2.userStationInfo.mdn.signatureProtocol' },
        { fieldId: 'as2.userStationInfo.mdn.mdnSigning' },
        { fieldId: 'as2.userStationInfo.encryptionType' },
        { fieldId: 'as2.userStationInfo.signing' },
        { fieldId: 'as2.userStationInfo.encoding' },
      ],
    },
  ],
};
