export default {
  fields: [
    { fieldId: 'type' },
    { fieldId: 'name' },
    { fieldId: 'http.mediaType' },
    { fieldId: 'http.baseURI' },
    { fieldId: 'http.disableStrictSSL' },
    { fieldId: 'http.concurrencyLevel' },
    { fieldId: 'http.retryHeader' },
    { fieldId: 'http.headers' },
    { fieldId: 'http.unencrypted' },
    { fieldId: 'http.encrypted' },
    { fieldId: 'http.encrypteds' },
  ],
  fieldSets: [
    {
      header: 'ping',
      collapsed: false,
      fields: [
        { fieldId: 'http.ping.relativeURI' },
        { fieldId: 'http.ping.method' },
        { fieldId: 'http.ping.body' },
        { fieldId: 'http.ping.successPath' },
        { fieldId: 'http.ping.successValuess' },
        { fieldId: 'http.ping.errorPath' },
      ],
    },
    {
      header: 'auth',
      collapsed: false,
      fields: [
        { fieldId: 'http.auth.fail.status.code' },
        { fieldId: 'http.auth.fail.path' },
        { fieldId: 'http.auth.fail.valuess' },
        { fieldId: 'http.auth.basic.username' },
        { fieldId: 'http.auth.basic.password' },
        { fieldId: 'http.auth.oauth.authuURI' },
        { fieldId: 'http.auth.oauth.tokenURI' },
        { fieldId: 'http.auth.oauth.scopes' },
        { fieldId: 'http.auth.oauth.scopeDelimiter' },
        { fieldId: 'http.auth.oauth.accessTokenPath' },
        { fieldId: 'http.auth.oauth.grantType' },
        { fieldId: 'http.auth.oauth.username' },
        { fieldId: 'http.auth.oauth.password' },
        { fieldId: 'http.auth.token.token' },
        { fieldId: 'http.auth.token.location' },
        { fieldId: 'http.auth.token.headerName' },
        { fieldId: 'http.auth.token.scheme' },
        { fieldId: 'http.auth.token.paramName' },
        { fieldId: 'http.auth.token.refreshMethod' },
        { fieldId: 'http.auth.token.refreshRelativeURI' },
        { fieldId: 'http.auth.token.refreshBody' },
        { fieldId: 'http.auth.token.refreshTokenPath' },
        { fieldId: 'http.auth.token.refreshMediaType' },
        { fieldId: 'http.auth.token.refreshHeaders' },
        { fieldId: 'http.auth.token.refreshToken' },
      ],
    },
    {
      header: 'rate.limit',
      collapsed: false,
      fields: [
        { fieldId: 'http.rateLimit.failStatusCode' },
        { fieldId: 'http.rateLimit.failPath' },
        { fieldId: 'http.rateLimit.failValuess' },
        { fieldId: 'http.rateLimit.limit' },
      ],
    },
  ],
};
