export default {
  fields: [
    { fieldId: 'type' },
    { fieldId: 'name' },
    { fieldId: 'assistant' },
    { fieldId: 'netsuite.account' },
    { fieldId: 'netsuite.tokenId' },
    { fieldId: 'netsuite.tokenSecret' },
    { fieldId: 'netsuite.environment' },
    { fieldId: 'netsuite.roleId' },
    { fieldId: 'netsuite.email' },
    { fieldId: 'netsuite.password' },
    { fieldId: 'netsuite.requestLevelCredentials' },
    { fieldId: 'netsuite.dataCenterURLs' },
    { fieldId: 'netsuite.accountName' },
    { fieldId: 'netsuite.roleName' },
    { fieldId: 'netsuite.concurrencyLevelRESTlet' },
    { fieldId: 'netsuite.concurrencyLevelWebServices' },
    { fieldId: 'netsuite.concurrencyLevel' },
    { fieldId: 'netsuite.wsdlVersion' },
    { fieldId: 'netsuite.applicationId' },
  ],
  fieldSets: [],
};
