export default {
  fields: [
    { id: 'exportName' },
    { id: 'exportDescription' },
    { id: 'exportAsynchronous' },
    { id: 'exportApiIdentifier' },
    { id: 'exportType' },
    { id: 'exportPageSize' },
    { id: 'exportDataURITemplate' },
    { id: 'exportOneToMany' },
    { id: 'exportPathToMany' },
    { id: 'exportSampleData' },
    { id: 'exportOriginSampleData' },
    { id: 'exportAssistant' },
    { id: 'exportAssistantMetadata' },
    { id: 'exportIsLookup' },
    { id: 'exportUseTechAdaptorForm' },
    { id: 'exportAdaptorType' },
    { id: 'exportNetsuiteSearchess' },
    { id: 'exportNetsuiteMetadata' },
    { id: 'exportNetsuiteSelectoption' },
    { id: 'exportNetsuiteCustomFieldMetadata' },
    { id: 'exportNetsuiteSkipGrouping' },
    { id: 'exportNetsuiteStatsOnly' },
    { id: 'exportNetsuiteInternalId' },
  ],
  fieldSets: [
    {
      header: 'restlet',
      collapsed: false,
      fields: [
        { id: 'exportNetsuiteRestletRecordType' },
        { id: 'exportNetsuiteRestletSearchId' },
        { id: 'exportNetsuiteRestletCriteria[*]Field' },
        { id: 'exportNetsuiteRestletCriteria[*]Join' },
        { id: 'exportNetsuiteRestletCriteria[*]Operator' },
        { id: 'exportNetsuiteRestletCriteria[*]SearchValue' },
        { id: 'exportNetsuiteRestletCriteria[*]SearchValue2' },
        { id: 'exportNetsuiteRestletBatchSize' },
        { id: 'exportNetsuiteRestletHooksBatchSize' },
        { id: 'exportNetsuiteRestletHooksPreSendFileInternalId' },
        { id: 'exportNetsuiteRestletHooksPreSendFunction' },
        { id: 'exportNetsuiteRestletHooksPreSendConfiguration' },
      ],
    },
    {
      header: 'distributed',
      collapsed: false,
      fields: [
        { id: 'exportNetsuiteDistributedRecordType' },
        { id: 'exportNetsuiteDistributedExecutionContexts' },
        { id: 'exportNetsuiteDistributedDisabled' },
        { id: 'exportNetsuiteDistributedExecutionTypes' },
        { id: 'exportNetsuiteDistributedQualifier' },
        { id: 'exportNetsuiteDistributedHooksPreSendFileInternalId' },
        { id: 'exportNetsuiteDistributedHooksPreSendFunction' },
        { id: 'exportNetsuiteDistributedHooksPreSendConfiguration' },
        { id: 'exportNetsuiteDistributedSublists' },
        { id: 'exportNetsuiteDistributedForceReload' },
        { id: 'exportNetsuiteDistributedIoEnvironment' },
        { id: 'exportNetsuiteDistributedLastSyncedDate' },
        { id: 'exportNetsuiteDistributedSettings' },
      ],
    },
    {
      header: 'getList[*]',
      collapsed: false,
      fields: [
        { id: 'exportNetsuiteGetList[*]TypeId' },
        { id: 'exportNetsuiteGetList[*]InternalId' },
        { id: 'exportNetsuiteGetList[*]ExternalId' },
      ],
    },
    {
      header: 'searchPreferences',
      collapsed: false,
      fields: [
        { id: 'exportNetsuiteSearchPreferencesBodyFieldsOnly' },
        { id: 'exportNetsuiteSearchPreferencesPageSize' },
        { id: 'exportNetsuiteSearchPreferencesReturnSearchColumns' },
      ],
    },
  ],
};
