export const initialLayouts = {
  lg: [
    {
      i: '3',
      x: 0,
      y: 1,
      w: 2,
      h: 4,
      minW: 1,
      minH: 4,
      moved: false,
      static: false,
    },
    {
      i: '1',
      x: 0,
      y: 2,
      w: 1,
      h: 4,
      minW: 1,
      minH: 4,
      moved: false,
      static: false,
    },
    {
      i: '2',
      x: 1,
      y: 2,
      w: 1,
      h: 4,
      minW: 1,
      minH: 4,
      moved: false,
      static: false,
    },
    {
      i: '0',
      x: 2,
      y: 1,
      w: 1,
      h: 4,
      minW: 1,
      minH: 4,
      moved: false,
      static: false,
    },
    {
      i: '5',
      x: 0,
      y: 0,
      w: 1,
      h: 2,
      minW: 1,
      minH: 2,
      moved: false,
      static: false,
    },
    {
      i: '6',
      x: 1,
      y: 0,
      w: 1,
      h: 2,
      minW: 1,
      minH: 2,
      moved: false,
      static: false,
    },
  ],
  md: [
    {
      i: '3',
      x: 0,
      y: 1,
      w: 2,
      h: 4,
      minW: 1,
      minH: 4,
      moved: false,
      static: false,
    },
    {
      i: '1',
      x: 0,
      y: 2,
      w: 1,
      h: 4,
      minW: 1,
      minH: 4,
      moved: false,
      static: false,
    },
    {
      i: '2',
      x: 1,
      y: 2,
      w: 1,
      h: 4,
      minW: 1,
      minH: 4,
      moved: false,
      static: false,
    },
    {
      i: '0',
      x: 2,
      y: 1,
      w: 1,
      h: 4,
      minW: 1,
      minH: 4,
      moved: false,
      static: false,
    },
    {
      i: '5',
      x: 0,
      y: 0,
      w: 1,
      h: 2,
      minW: 1,
      minH: 2,
      moved: false,
      static: false,
    },
    {
      i: '6',
      x: 1,
      y: 0,
      w: 1,
      h: 2,
      minW: 1,
      minH: 2,
      moved: false,
      static: false,
    },
  ],
  sm: [
    {
      i: '3',
      x: 0,
      y: 1,
      w: 2,
      h: 4,
      minW: 1,
      minH: 4,
      moved: false,
      static: false,
    },
    {
      i: '1',
      x: 0,
      y: 2,
      w: 1,
      h: 4,
      minW: 1,
      minH: 4,
      moved: false,
      static: false,
    },
    {
      i: '2',
      x: 1,
      y: 2,
      w: 1,
      h: 4,
      minW: 1,
      minH: 4,
      moved: false,
      static: false,
    },
    {
      i: '0',
      x: 2,
      y: 1,
      w: 1,
      h: 4,
      minW: 1,
      minH: 4,
      moved: false,
      static: false,
    },
    {
      i: '5',
      x: 0,
      y: 0,
      w: 1,
      h: 2,
      minW: 1,
      minH: 2,
      moved: false,
      static: false,
    },
    {
      i: '6',
      x: 1,
      y: 0,
      w: 1,
      h: 2,
      minW: 1,
      minH: 2,
      moved: false,
      static: false,
    },
  ],
  xs: [
    {
      i: '3',
      x: 0,
      y: 1,
      w: 2,
      h: 4,
      minW: 1,
      minH: 4,
      moved: false,
      static: false,
    },
    {
      i: '1',
      x: 0,
      y: 2,
      w: 1,
      h: 4,
      minW: 1,
      minH: 4,
      moved: false,
      static: false,
    },
    {
      i: '2',
      x: 1,
      y: 2,
      w: 1,
      h: 4,
      minW: 1,
      minH: 4,
      moved: false,
      static: false,
    },
    {
      i: '0',
      x: 2,
      y: 1,
      w: 1,
      h: 4,
      minW: 1,
      minH: 4,
      moved: false,
      static: false,
    },
    {
      i: '5',
      x: 0,
      y: 0,
      w: 1,
      h: 2,
      minW: 1,
      minH: 2,
      moved: false,
      static: false,
    },
    {
      i: '6',
      x: 1,
      y: 0,
      w: 1,
      h: 2,
      minW: 1,
      minH: 2,
      moved: false,
      static: false,
    },
  ],
  xxs: [
    {
      i: '3',
      x: 0,
      y: 1,
      w: 2,
      h: 4,
      minW: 1,
      minH: 4,
      moved: false,
      static: false,
    },
    {
      i: '1',
      x: 0,
      y: 2,
      w: 1,
      h: 4,
      minW: 1,
      minH: 4,
      moved: false,
      static: false,
    },
    {
      i: '2',
      x: 1,
      y: 2,
      w: 1,
      h: 4,
      minW: 1,
      minH: 4,
      moved: false,
      static: false,
    },
    {
      i: '0',
      x: 2,
      y: 1,
      w: 1,
      h: 4,
      minW: 1,
      minH: 4,
      moved: false,
      static: false,
    },
    {
      i: '5',
      x: 0,
      y: 0,
      w: 1,
      h: 2,
      minW: 1,
      minH: 2,
      moved: false,
      static: false,
    },
    {
      i: '6',
      x: 1,
      y: 0,
      w: 1,
      h: 2,
      minW: 1,
      minH: 2,
      moved: false,
      static: false,
    },
  ],
};

export const initialGraphTypes = [
  { id: '0', type: 'Line', dataType: 'connections', color: '#FAB840', integrationId: 'demo0'},
  { id: '1', type: 'Line', dataType: 'connections', color: '#3F5089', integrationId: 'demo1'},
  { id: '2', type: 'Line', dataType: 'connections', color: '#FAB840', integrationId: 'demo2' },
  { id: '3', type: 'Bar', dataType: 'Records', color: ['#05B39C', '#D93535'], integrationId: 'none' },
];
